### ISSUE TITLE
Snip Spotify artwork sometimes blank and different from Spotify app

### ISSUE THREAD

**Issue by alimamak** [dlrudie/Snip#100]
![snip-error](https://cloud.githubusercontent.com/assets/11730365/14701230/dccb371e-07d6-11e6-9646-12ed45772671.jpg)

I use Snip with OBS. I like to display the cover artwork but lately is't been buggy. Most of the time it's a blank artwork so the current song will have the previous cover artwork. 

The other problem is sometimes the artwork displayed is different from the artwork on Spotify. This track is the example on the attached screenshot  (https://open.spotify.com/track/6Xrw10Wcr1PmLXHvJkTxFO)

These 2 tracks are another example that have a blank artwork:
https://open.spotify.com/track/6mM3zAPOuNkNDytJCDGz96
https://open.spotify.com/track/45gJ4ncmYXXqPlFn8btmrr

One thing i noticed is that when a song has an artwork, the song output text will follow the format i set
like this “People Everyday - Unplugged”  by  Arrested Development, but it uses this format; Bob Marley & The Wailers - I Shot The Sheriff - Live At The Lyceum, London/1975 when no artwork

Hope you can understand the issue. English is not my native language :)

**Comment by dlrudie** [comment]
This is known. It has to do with the search result returned by my query versus what you are actually playing. It's currently not ideal and I do plan to look into solutions for it.

**Comment by dlrudie** [comment]
Unfortunately none of these songs are available in my region so I can't test them.

**Comment by foxmajik** [comment]
Thank you for explaining this.

I've found your tool very useful and I hope you'll keep us up to date with the Spotify API as it changes.
