### ISSUE TITLE
"Spotify" in Name of Song Track

### ISSUE THREAD

**Issue by RockGuitarist1** [dlrudie/Snip#104]
Whenever playing a track, the word "Spotify" is in the track name, like this:
http://prntscr.com/az0rvh

I checked my output settings, but the word "Spotify" is no where in it.
http://prntscr.com/az0s8c

**Comment by dlrudie** [comment]
Highlight Spotify in the taskbar and make sure when playing it actually doesn't have Spotify in the name.

**Comment by RockGuitarist1** [comment]
It does. Anyway to prevent that?

**Comment by dlrudie** [comment]
You moused over Spotify, not Snip, correct?

![spotify-taskbar](https://cloud.githubusercontent.com/assets/1780069/18232687/cfd211d4-729a-11e6-89c2-9379a5fe1f08.png)

**Comment by RockGuitarist1** [comment]
Correct.

**Comment by dlrudie** [comment]
I don't know what to tell you then. You're using the latest version of Spotify?

**Comment by RockGuitarist1** [comment]
Yes. I am not sure why Spotify would be appearing in the song title in Spotify.

**Comment by dlrudie** [comment]
Closing because I can't duplicate this and it doesn't appear to be an issue with Snip directly.
