### ISSUE TITLE
Can't write \ and ~ when hotkeys are enabled

### ISSUE THREAD

**Issue by Irolan** [dlrudie/Snip#107]
The keyboard has a QUERTZ layout. \ is written by pressing Alt Gr + [ß/?] and ~ by Alt Gr + [+/*].
When Snip has hotkeys enabled, these symbols can no longer be written. All other Alt Gr combinations work. Apparently Snip thinks Alt Gr is part of a hotkey combination.

**Comment by dlrudie** [comment]
I don't even know how to being to look into this. I have no such keyboard layout. I do have a future plan to allow customization of hotkeys. That may allow a solution itself.

**Comment by dlrudie** [comment]
No updates.
