### ISSUE TITLE
Let Snip work with MusicBee

### ISSUE THREAD

**Issue by clethrill** [dlrudie/Snip#109]
MusicBee http://getmusicbee.com/ is an awesome music program that has an API and tonnes of information would love to see snip work with it.

**Comment by dlrudie** [comment]
I'll look into adding support for this as long as it's not a website-based player.

**Comment by dlrudie** [comment]
I did some initial digging into supporting this. The API provided appears to only be for making a plugin for MusicBee itself.

**Comment by clethrill** [comment]
Damn, that's a shame. I did find a musicbee plugin which did something to what I wanted. Keep up the good work though.

**Comment by Robijnvogel** [comment]
@clethrill do you mean [this musicbee plugin](http://musicbee.wikia.com/wiki/Now_Playing_to_External_Files) that outputs "now playing info" in a user-configured format to a user-configured file-path on your local machine?
It's a workaround, but loading that information from that file should be child's play for a Discord plugin.
