### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#110]
Is it possible to get the "trackID" (or whatever it's called) on Spotify in a separate text file (when Spotify is chosen) ?
Eg. The part after /track/ here: https://open.spotify.com/track/4eU274e7gXhJxDOQwolXUH

I use separate files (track, artist, album) + artwork in different situations and for one place I would really like to combine artist + track + a link to that particular track using something like: 
```
<?php
$myfile = fopen("Snip_Spotify_TrackID.txt", "r") or die("Error!");
echo fread($myfile,filesize("Snip_Spotify_TrackID.txt"));
fclose($myfile);
?> 
```
...and then add "a href"  to it of course, if I would need that.

/Michael

**Comment by dlrudie** [comment]
This is doable.

**Comment by murko69** [comment]
That sounds great! Keeping my fingers crossed it will be implemented some day :)

**Comment by murko69** [comment]
Sorry to re-open this one. I just wanted to say thanks for an awesome feature and also ask something related to it.
I was thinking about using the link directly in the output-window and wonder if there already is or possible to create a function for it. The "trackID" that is!

todays defaults:
track: $t
artist: $a
album: $l

I was thinking of using the first field (track) like this:
`<a href="https://open.spotify.com/track/$ti" target="_blank">$t<a>`
(giving "$ti" works for trackID of course)

If this doesn't work I'll upload the file "Snip_TrackId" instead, as I thought of doing first, and fetch the info from there.

**Comment by murko69** [comment]
Never mind this last part (if you don't think it's a good idea yourself). I'm using my first example from this issue and it works just fine :)
