### ISSUE TITLE
Snip.txt not created

### ISSUE THREAD

**Issue by jzhengx** [dlrudie/Snip#115]
I have a track playing on iTunes and ran Snip.exe but there isn't a Snip.txt that's created. Spotify was also attempted but yielded the same result.

**Comment by dlrudie** [comment]
The Snip.txt file will be located in the same directory as Snip.exe. If it's not automatically creating it try creating the file itself and then seeing if Snip will update that file.

**Comment by Dfrost72** [comment]
So I tried creating a Snip txt since it wasn't pulling any txt from me just playing music on spotify what can I do?

**Comment by dlrudie** [comment]
Make sure you extract Snip from the .7z file. Run Snip. Make sure the media player you use is selected. Play a song. Snip.txt will be created in the same directory as Snip.exe.
