### ISSUE TITLE
Spotify - Artist - Track while streaming, snip can't save output format properly

### ISSUE THREAD

**Issue by viperver1** [dlrudie/Snip#118]
Tried streaming then this happens:
[img]http://imgur.com/F9AzvOI[/img]

Also I set my output format with "" marks on my song title in Output Format and hasn't shown it properly too. I need this fixed so I can stream without having Spotify mentioned in the track that is currently playing in my OBS.

**Comment by fikaelk** [comment]
Im using a old version of spotify and when i hover over the app spotify is in the name. Could you add option to remove the first 8 chars?
