### ISSUE TITLE
Not issue , just question (Second Separator)

### ISSUE THREAD

**Issue by M4dDan** [dlrudie/Snip#121]
There is a way to add another separator at the end? If i have scrolling text when the scroll start the second cycle aren't any space from title and artist , this is really bad to see.

Ty for any anwser.

**Comment by murko69** [comment]
Wouldn't this be fixable manually if you used separate files for track/artist instead of using the one file (with the separator built in)? I don't know since I haven't yet tried it, but it doesn't seem impossible :)

You are presenting "track - artist" in some HTML marquee today or what do you meen with scroller?

**Comment by M4dDan** [comment]
i mean i use it in obs with horizontal scrolling , for save space... the syntax is track - artist

but when the text scroll i see like track - artisttrack-artist etc etc. i need a separator after the track for show track - artist - track - artist

**Comment by dlrudie** [comment]
Just add spaces after the artist or before the track.

**Comment by M4dDan** [comment]
how ?the file be rewrited every track.. and delete all if i add some space or other characters XD

sorry my english and ty for help ^^

**Comment by murko69** [comment]
I guess what he ment was something like this: https://i.snag.gy/9kDYVo.jpg

**Comment by M4dDan** [comment]
it work ^^ thank you all for the help

**Comment by murko69** [comment]
Great! :)
I'm thinking @dlrudie will be so happy to hear that, he'll put up 5.6.0 with latest commits right away......... :P

**Comment by dlrudie** [comment]
@M4dDan Glad it worked for you.

@murko69 :) I'll see about getting a new version of with the commits today. I have a few errands to run and then I'll throw a build together.

**Comment by DMCK96** [comment]
Leaving spaces like this no longer works in the newest version. They just get deleted once writing to the txt file.
