### ISSUE TITLE
History

### ISSUE THREAD

**Issue by Nameless009** [dlrudie/Snip#122]
New songs could go up not down.
(sorry for bad English)

**Comment by dlrudie** [comment]
Is there any particular reason why this feature would be needed?

**Comment by dlrudie** [comment]
This would add a bit of code overhead as prepending text isn't really a supported capability in most languages. You would have to either read the old contents into memory, erase the contents of the file, add your new content, and then write the contents from memory back into the file. Alternatively you could move the current file to a temporary file, create a new file with the new text, append the temporary file to the new file, and then erase the temporary file.

Either way it's a lot of overhead for not much gain. Sorry.
