### ISSUE TITLE
Remove certain sections of the text file?

### ISSUE THREAD

**Issue by slashiee** [dlrudie/Snip#124]
This tool is pretty useful, but I would like to see an option that can remove certain sections of the text file. I don't really want to see foobar2000 v1.3.13 beta 1 on my streams and I'm sure there's other people out there that don't like it too.

**Comment by dlrudie** [comment]
Currently Snip strips out "[foobar 2000 v#.#.#]". The fact that your version has "beta 1" appended is what's causing it not to strip it accordingly. I'll see if I can just strip from [foobar2000 until the the next occurrence of ].
