### ISSUE TITLE
Spotify: Problem with $ (dollar sign) in Track Title

### ISSUE THREAD

**Issue by FAaBbiii** [dlrudie/Snip#129]
Hi,

if a $ (dollar sign) is in the song, Snip output some Random Chars:

Example:
Spotify:
"Sucker For Pain (with Wiz Khalifa, Imagine Dragons, Logic & Ty Dolla $ign feat. X Ambassadors)"

Snip:
"Sucker For Pain (with Logic & Ty Dolla 3RpufFBpn0bfpG1IhK0cUwgn feat. X Ambassadors)"

I dont know if its a problem of Snip or the Spotify API

I'm using Snip v5.6.0

**Comment by dlrudie** [comment]
Oh wow. I know exactly what is causing this. Thank you. I'll get it fixed. :)
