### ISSUE TITLE
Ankhbot R2 integration

### ISSUE THREAD

**Issue by Smeagol001** [dlrudie/Snip#130]
Hi,
first nice little tool you got there :) 
I'd like to see an ankhbot integration for his currrent song feature if possible
since ankh is kinda cliosed source there is not an easy way to get that modifed on the bots side.
Basically ankhbot is putting out his current song  to ...\AnkhBotR2\Twitch\Files\CurrentSong.txt
and i was wondereing if you just could pharse that file into your outputfile.
If i knew how to do tha via some batch ffile or somethong i'd do that myself.

Cheers Smeagol

**Comment by dlrudie** [comment]
If you just want to link Snip.txt to that path you can use Junction from Microsoft.
https://technet.microsoft.com/en-us/sysinternals/bb896768.aspx
