### ISSUE TITLE
No support for certain characters?

### ISSUE THREAD

**Issue by winster245** [dlrudie/Snip#134]
Hi there.
I've noticed with the latest release of Snip (5.6.5) certain song titles can't be displayed or won't be displayed properly. Tested it out with VLC so far. Whenever a song starts with a special Character on the Artists name such as " * " everything else behind that won't be displayed. The same goes for like Japanese characters. They aren't recognized either.

**Comment by dlrudie** [comment]
I'll see if I can duplicate this. I only really use Spotify and iTunes myself.

**Comment by david-a** [comment]
I'm having this issue myself (VLC), even when that character is just a dot (`.`)

**Comment by dlrudie** [comment]
Can you provide a song that this happens with? Or provide the file? This way I can duplicate it easier.

**Comment by gdoolo** [comment]
I am having the same issue with VLC, when a song name contains a dot ( . ) everything else behind the dot won't be displayed.

**Comment by david-a** [comment]
you can download this song for example - Wish You Were Here by The.madpix.project 
http://jamen.do/t/1214935
nothing shows after The.madpix

**Comment by gdoolo** [comment]
I found that but don't know how to use it 
https://github.com/dlrudie/Snip/pull/133

**Comment by KingCrazy** [comment]
@dlrudie 
Trimming at "." _should_ be fixed in #133 (When testing, it seemed to be fixed)

I do not believe it fixes the special characters issue, unfortunately.

**Comment by dafattman** [comment]
I am also having the issue with anything after a . Makes it so that the full song title cannot be displayed as it gets cut off at (feat.

Example: Hyper Potions - Unbreakable (feat. Danyka Nadeau) is how it should be formatted
Actual: Hyper Potions - Unbreakable (feat.

**Comment by dlrudie** [comment]
#158 fixes this
