### ISSUE TITLE
Set Output Format issue: iTunes/:cannot read combined formats,it can only read one of them

### ISSUE THREAD

**Issue by FatherlyArson** [dlrudie/Snip#139]
Album: Monstercat 017 - Ascension
Artist: Feint/Miyoki
Song: “Phosphor (feat. Miyoki)”
i tried to combine format: $$a―$$l to get: Feint/Miyoki―Monstercat 017 - Ascension     in the artist box
i would get when i read from it in OBS : Feint/Miyoki―$$l   it would not translate the second part into album info
it would only work half way with the snaz.txt when i read from it in OBS
if snaz.txt read: “Phosphor (feat. Miyoki)” ― Feint/Miyoki 
after combining labels: $$a―$$l
it   now    read:  Feint/Miyoki―Monstercat 017 - Ascensioni―Monstercat 017 - Ascension
what happens is it adds on to the info in the snaz.txt instead of writing only in the artist.txt
i try to set a format output for artist,album,track. they all would not read the second part($$I)
i hope all of this made sense. im using this app in OBS(reading from text file) my media player used is iTunes.

**Comment by dlrudie** [comment]
I don't understand really.

If you want it to just be "Artist-Album" then just add $$l to the artist format.

It works here.

![thzvw3k](https://user-images.githubusercontent.com/1780069/27009659-9c629e0e-4e59-11e7-9640-96665fc83bf0.png)
