### ISSUE TITLE
Track number does not disappear

### ISSUE THREAD

**Issue by Alixa** [dlrudie/Snip#141]
Is it possible to remove the track number? ( In this case "746.") Because I put my music on shuffle, it becomes confusing and annoying to see random numbers popping out.
![sem titulo](https://cloud.githubusercontent.com/assets/25573996/22632225/57826190-ec0f-11e6-9d25-960d4601b1a4.png)

**Comment by dlrudie** [comment]
Which music player are you using?

If you're using Winamp and there's no ID3 tag it may just show the track like this because it doesn't know what the artist and/or track are.

Alternatively, the readme file explains how to set the titlebar in Winamp.

**Comment by dlrudie** [comment]
Closing; no further update was provided.
