### ISSUE TITLE
No Snip.exe

### ISSUE THREAD

**Issue by bodyshotking** [dlrudie/Snip#142]
I am not seeing a snip.exe file anywhere within the file system of my computer. Please help.

**Comment by CatEyesJimmy** [comment]
Same, I've looked through multiple releases of Snip and cannot locate snip.exe either.

**Comment by murko69** [comment]
You probably downloaded the source file under "Releases"?!
Download the zip file (.7z) instead. .exe file is present. I promise :)

**Comment by dlrudie** [comment]
Don't download the file titled "Source code" because that's just the source code. There won't be a .exe file in there because you have to build it yourself. Thanks @murko69.
