### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by masterfenix87x** [dlrudie/Snip#144]
everytime i restart my pc i have to uninstall snip and reinstall the app in order to get it to work.

**Comment by PinkRangerV** [comment]
won't open at all for me

**Comment by dlrudie** [comment]
There is no "uninstall" or "reinstall" of Snip. It's literally just a .exe file you double-click.

Make sure you extract it out of the .7z file and then double-click the .exe or make a shortcut to it. It should open just fine whenever you want to start it.

It does sit in the system tray and may, at times, be hidden by Windows until you click the little arrow by the clock.
