### ISSUE TITLE
I recieved an error when running this for Spotify.

### ISSUE THREAD

**Issue by Fozinator103** [dlrudie/Snip#147]
This only occured while the song is playing and forces me to close Snip.

I've tried installing a former version of Spotify as a workaround, and it didn't fix the problem.

The error states "invalid JSON string."

The details of the error is attached in this .txt file
[New Text Document.txt](https://github.com/dlrudie/Snip/files/849763/New.Text.Document.txt)

**Comment by dlrudie** [comment]
There's honestly not enough detail here for me to track anything down.

If you can find a specific song that's causing the crash then let me know.

**Comment by Fozinator103** [comment]
I'm sorry I did not follow up. I installed the latest version, and the problem was solved. I will continue to do the same with future problems.
