### ISSUE TITLE
Lost after extracting and putting into desktop for twitch streaming

### ISSUE THREAD

**Issue by joemondfrans** [dlrudie/Snip#152]
Hey, So I extracted Snip and then from my files I dragged it onto my desktop. Then I went to OBS (open Broadcast Software) and went to add it as a text file - but it wasent in the file, I then closed OBS and tried to find SNIP anywhere - when it is on my desktop and the files are no where to be found. I open Properties to see where the file is, but its not where it says its suppose to be.. PLEASE HELP NOOB HERE

**Comment by murko69** [comment]
Are you sure you downloaded the correct file and not the source code?
Either that or I just didn't understand your post :)

**Comment by joemondfrans** [comment]
I just read what I typed.... it explains it as good as I can. I downloaded snip. When I go to the file it's no where to be found.

**Comment by dlrudie** [comment]
Extract Snip to its own directory. Inside will be Snip.exe. Run that. Snip.txt will be created _after_ using Snip.
