### ISSUE TITLE
Snip only writes to Snip.txt and only in default output format

### ISSUE THREAD

**Issue by adambarker** [dlrudie/Snip#153]
Currently Snip only updates Snip.txt in the default format leaving other files blank.

Snip.txt is updated upon changing songs.
Altering 'Set Output Format' seems to have no effect. Format always remains "Artist - Track".
Selecting 'Save Information Separately' generates separate text files but they all remain blank.
Snip_Artwork.jpg is created but also remains blank.

Here are the options I have selected in Snip:
- Spotify
- Save Information Separately
- Save Album Artwork
- Empty File If No Track Playing

Using Snip 5.6.5 and Spotify desktop app for Windows 10 (version 1.0.55.487.g256699aa)

I was using this exact set up 1 month ago and the separate files and artwork were updating properly. Since that time the only thing that has updated is the Spotify desktop app.

Not sure when this happened but the window title for the Spotify desktop is now "Spotify Premium" if you are signed in to a Spotify Premium account (which I am).

**Comment by eddieha** [comment]
I ran into the same problem today! Glad to see that I'm not alone - I assume there was a change in the spotify app?

**Comment by dlrudie** [comment]
Spotify web API requires authentication now. I'll have to add that support in. Unfortunately It may be a few days to a week before I have time.

**Comment by murko69** [comment]
Have the same issues.
Glad I checked in here before I tried to figure out hat was wrong with my FTP that only updated the artwork :)

Take your time David - We'll be in the background quietly cheering you on 👍 :)

**Comment by superantek24** [comment]
@adambarker I have the same problem on all options (tested on spotify and vlc).
Anyone know what is location of snip setting files? (I'll try edit it manually).

**Comment by dlrudie** [comment]
@superantek24 Read my post above. This has already been addressed.

**Comment by SavageDrago** [comment]
Not working properly on Foobar2k or VLC. Any incomming fix? Thanks!
