### ISSUE TITLE
Snip Output Format Still Get's Glitched After Awhile Of Use After Downloading Updated Version. 

### ISSUE THREAD

**Issue by DooplisTheGhost** [dlrudie/Snip#155]
After I downloaded the newest version of Snip that added a User Client for Spotify, I noticed that after awhile, the Output format became glitched again. When I first downloaded the new version and setup the Output format to my preferences, it updated the layout of the text in OBS Studio just fine, but after awhile of using Snip with OBS Studio, the Output format became glitched again just like what it was doing before the newest update came out that was supposed to fix it. 

It's doing the same thing as before where the layout of the scrolling text in OBS Studio will say clumped together and won't even change when you go into the Snip settings and change the Output Format. 

*Update* - Right after I posted this, I paused the music in Spotify, then I went into OBS Studio and I clicked on the little eye icon that's next to the text source for my now playing music then turned it on and off a few times. Doing this made it reset the text layout back to the normal.

**Comment by dlrudie** [comment]
It's not a glitch. Basically whenever Snip can't get the track information via Spotify's search it defaults to whatever text is in the title bar.

Are you using 6.0.2?

**Comment by DooplisTheGhost** [comment]
@dlrudie Correct, I'm using version 6.02, the most recent one.

**Comment by dlrudie** [comment]
How often does this happen? Does it still happen?

**Comment by POPZSH0TZ** [comment]
I cant even use mine it says cant run on this pc never been able to use it

**Comment by POPZSH0TZ** [comment]
even snip5.6.5

**Comment by DooplisTheGhost** [comment]
@dlrudie I've noticed that it tends to happen with certain songs, Snip's output format seems to work fine with some songs, but for some songs, the output format just seems to clunk together like it was doing before.

**Comment by dlrudie** [comment]
Snip will fall back to the window title of Spotify if it can't get a good search result from Spotify's API. The best thing to do is post the songs you've identified problems with and I can try to figure out why.

**Comment by dlrudie** [comment]
Alright, I'll soon have a big change to how Spotify is handled in Snip. Results should be 100% accurate and consistent. I'm going to try to have it up and running tonight.
