### ISSUE TITLE
can't run this on my pc

### ISSUE THREAD

**Issue by POPZSH0TZ** [dlrudie/Snip#156]
when I go to run snip 5.6.5 or snip6.0.2 is says my cant run this on my pc how do I fix this

**Comment by dlrudie** [comment]
Make sure you have .NET Framework v4.5 installed.

**Comment by POPZSH0TZ** [comment]
where do I find this at?

**Comment by dlrudie** [comment]
Please keep your issue in this post. Do not post it in other places.

https://www.microsoft.com/en-us/download/details.aspx?id=30653

Also there's no reason to use 5.6.5. Remove it.

**Comment by POPZSH0TZ** [comment]
[
![screenshot_1](https://user-images.githubusercontent.com/29265008/26954566-ae52067c-4c7e-11e7-87ae-f0709cf68bea.png)
](url)

**Comment by dlrudie** [comment]
Take a screenshot of the error from Snip.

**Comment by dlrudie** [comment]
Take a screenshot of the error when you run Snip.

**Comment by POPZSH0TZ** [comment]
[
![screenshot_2](https://user-images.githubusercontent.com/29265008/26954614-f00bfdac-4c7e-11e7-8caf-8a7fd5bd82d0.png)
](url)

**Comment by dlrudie** [comment]
Are you running Snip as administrator?

**Comment by POPZSH0TZ** [comment]
when I try to run it as administrator it says the same thing

**Comment by dlrudie** [comment]
Are you running it from inside of the .7z archive or did you extract it to a directory first? Is your OS 32-bit or 64-bit?

**Comment by POPZSH0TZ** [comment]
[
![screenshot_1](https://user-images.githubusercontent.com/29265008/26954859-b61304e0-4c80-11e7-8f4b-aa7565a4aeca.png)
![screenshot_2](https://user-images.githubusercontent.com/29265008/26954861-bbbc9ba4-4c80-11e7-8769-7d79c6a2edac.png) once I click it says that an I think its 64bit


](url)

**Comment by POPZSH0TZ** [comment]
and I'm windows 10 pro

**Comment by POPZSH0TZ** [comment]
64 bit

**Comment by dlrudie** [comment]
What's your UAC setting at?

**Comment by dlrudie** [comment]
http://windowsreport.com/app-cant-run-windows-10/

**Comment by POPZSH0TZ** [comment]
UAC?

**Comment by lsteins** [comment]
im having the same issue, though 7zip couldnt extract the file an the app i used to extract it said "Error opening the archive ( check available disk space, that you have a valid password, or that the archive is not damage or partial". though i still can try to run it but it of course its say the app cant run.

**Comment by lsteins** [comment]
ok so i figured it out so the programs i was running wernt extracting the file but popzshots download this make sure its the 64 bit then extract the file to your desktop http://www.7-zip.org/

**Comment by dlrudie** [comment]
File not extracted correctly as shown in screenshot above. Snip.exe shows 0kb. Extract it correctly and try again.

**Comment by POPZSH0TZ** [comment]
well now when I open snip nothing happens

**Comment by POPZSH0TZ** [comment]
the two files it's so post to create the artworks an other one doesn't pop up?

**Comment by dlrudie** [comment]
Step 1) Download latest snip release https://github.com/dlrudie/Snip/releases/latest (Make sure you download the .7z file and not the source code)
Step 2) Using 7-Zip (linked above) extract the .7z file to somewhere on your computer
Step 3) Run Snip

Done

**Comment by POPZSH0TZ** [comment]
yeah sounds simple but after I extracted the file an go to run snip nothing happens at all

**Comment by dlrudie** [comment]
Did you look in the system tray? Because it just starts up and sits in the system tray.
