### ISSUE TITLE
Name song attached to artist name

### ISSUE THREAD

**Issue by CptSavage** [dlrudie/Snip#160]
Hi, i use snip with spotify and the name song is attached to artist name, is very annoying can you help me with this plz? I have a friend and he use snip with vlc and he have the same problem.

**Comment by dlrudie** [comment]
I don't understand. Can you post some examples of what you're talking about?

**Comment by CptSavage** [comment]
http://prntscr.com/fi7rew the name song is attached to the artist

**Comment by dlrudie** [comment]
Right-click on Snip, choose Output Format, and add a bunch of spaces.

**Comment by CptSavage** [comment]
http://prntscr.com/fifk5c still not working

**Comment by dlrudie** [comment]
If you check the Snip.txt text file you'll see it's working. The program you're opening the text file with may be removing them. This is not a problem with Snip.

**Comment by CptSavage** [comment]
I'm using obs

**Comment by CptSavage** [comment]
the txt file don't change

**Comment by CptSavage** [comment]
Changing the output don't do anything, the txt file is always the same.

**Comment by dlrudie** [comment]
You're doing something wrong then.

![8ulclt2](https://user-images.githubusercontent.com/1780069/27015929-520368a8-4edf-11e7-8c88-c9b74d0c0f4f.png)

**Comment by CptSavage** [comment]
I don't understand, now in my laptop worked but in my pc didn't work...
