### ISSUE TITLE
Playing now not updating when VPS  isnt connected

### ISSUE THREAD

**Issue by AlexHakman** [dlrudie/Snip#162]
How to reproduce this issue:

Open a vps. (Windows server 2012)
open up spotify
open up snip
play songs
(Now the snip updates)
close connection
Now snip stops updating the text file.

Can you make it like snip still updates even if i dont have a connection to my VPS?

**Comment by dlrudie** [comment]
That may be a limitation of how VPS's behave when there is no connection to them.

There's likely nothing I can change in Snip to change that behavior.  The way Snip is written is that as long as Snip is running, Spotify is running, and the local web server is running, then it will continue to update.

Unfortunately I'm not about to pay for a VPS to figure this out.

If I were you I would try to diagnose it myself. Turn off "Empty File If No Track Playing" and see what text shows up in Snip.txt.

**Comment by AlexHakman** [comment]
I have tested with spotify, winamp and vlc. Both vlc and winamp work
perfectly when not connected to a VPN. However, only spotify refuses to
work with snip.

I just thought to let you know it might be a little bug?
I fixed it by playing music with winamp now so everythink works perfect.
Snip is awesome <3

2017-06-15 1:17 GMT+02:00 David Rudie <notifications@github.com>:

**Comment by dlrudie** [comment]
I honestly wouldn't be able to figure this out without a VPS.

My guess is that it's not a bug on Snip's part but probably something to do with Spotify. Perhaps Spotify's own local webserver shuts down or stops accepting connections when disconnected from the VPS.

**Comment by dlrudie** [comment]
Try v6.9.1 and let me know.

**Comment by dlrudie** [comment]
No update.
