### ISSUE TITLE
Gap when text is scrolling

### ISSUE THREAD

**Issue by BigWhiteLee** [dlrudie/Snip#164]
Hi!
I've been trying to find a way to create a gap at the end of the text file. 
I stream often and have a "scrolling" effect on the text, but as it scrolls over, there is no gap between the track and artist. 
https://gyazo.com/a2becffedc084eb3c0cc1d9d38a13a5a
If you look in that gyazo, it'll show that there's no gap between the song and artist, which doesn't look all that good.
Is there anything I can do to rectify that? 

Thanks!

**Comment by dlrudie** [comment]
Edit output format and add spaces. :)

**Comment by BigWhiteLee** [comment]
Wow that was stupid of me. Thank you!
