### ISSUE TITLE
Spotify info not updating

### ISSUE THREAD

**Issue by deadvirusllc** [dlrudie/Snip#166]
Installed latest version after realizing spotify info wasnt updating.  Using windows 10 with spotify desktop program.

**Comment by deadvirusllc** [comment]
Downgraded to 6.05 and it works.

**Comment by dlrudie** [comment]
I would check to make sure that SpotifyWebHelper is running. While the previous version might work for now it won't in the future. I do have plans for pulling the authorization on the server soon. It would be best to try and figure out why the current version is not working.

**Comment by deadvirusllc** [comment]
Where can I find the spotify web helper?  Also, it stopped working last night 6/17 at 8:21p.m. pst.  That was the last file save time.

**Comment by deadvirusllc** [comment]
I removed spotify and snip.  Did a reinstall and all is well now.  Thank you for the response.
