### ISSUE TITLE
snip.txt not updating

### ISSUE THREAD

**Issue by AKBS** [dlrudie/Snip#167]
stuck on "switched to spotify" and wont update at all

**Comment by dlrudie** [comment]
Check to make sure SpotifyWebHelper is running in your task manager.

**Comment by bawitdaba** [comment]
I have the same issue, SpotifyWebHelper is running. I downgraded back to Snip-v5.6.5 and it works perfectly fine.

**Comment by dlrudie** [comment]
Yes, it's a private API key. You can get one [here](https://developer.spotify.com/web-api/).

Here's a quick test to check SpotifyWebHelper.

Open this link in your browser. If it says Not Found then at least I know that's the correct server port.
http://snip.spotilocal.com:4380/simplecsrf/token.json

If that doesn't work try adjusting the port between 4370 and 4380 and let me know if one of them works for you.

**Comment by bawitdaba** [comment]
Yeah that didn't work for me it says "Not Found". When I debug the application it does seem to fetch some JSON data, but nowhere near what it actually needs.

I reverted the source to 6.0.5 and that one works perfectly for me. It looks like it grabs API information directly from Spotify.com instead of using their hidden web server. If I had to guess it's likely that SpotifyWebHelper has changed.

I also moved to the Windows Store version of Spotify, not sure if that would change anything...

**Comment by dlrudie** [comment]
It saying Not Found is a good thing. That means that it connected to the port successfully. So it's correct in that regard. It just says Not Found because an Origin header was not sent with it.

You shouldn't ever downgrade. That's not going to fix anything. Especially since the Spotify code had a 100% complete rewrite for v6.1.0.

The Windows Store version may or may not be the culprit. Try the standalone version.

**Comment by AKBS** [comment]
ok so go to advanced options in Spotify App and turn on "Allow spotify to be opened from the web" . . with it disabled it doesnt run the spotifywebhelper.exe

**Comment by dlrudie** [comment]
That makes sense. That option is enabled by default in Spotify. I'll have to make a note somewhere for people to double-check that in case they disabled it for whatever reason. Thanks.

**Comment by ruskiar** [comment]
I have a similar issue and tried to troubleshoot according to your suggestions.  The snip.txt file is empty and Snip doesn't recognize that a song is playing in spotify.  The web helper is running and the option to "allow spotify to be opened from the web" is checked.  

Anything else I can try?

**Comment by sammyboy405** [comment]
Im also having the same issues.  it will not see Spotify at all.  The Web Helper is running.. Works fine with google desktop player.   But Spotify I just cant get it to latch on.  Im using Spotify Desktop Right from their website and not the store.

**Comment by deadvirusllc** [comment]
If any of you modified your windows hosts file so that you dont get ads you need to remove the following entry:            0.0.0.0 open.spotify.com

**Comment by sammyboy405** [comment]
My Host file is generic, default.

**Comment by sammyboy405** [comment]
I switch the Empty File is no track playing.   And now it says Spotify is not currently running.   It is running with webhelper as well.

**Comment by sammyboy405** [comment]
I also checked to see if it was running using http://localhost:4380/simplecsrf/token.json  And it  says Not Found   So according to the comment above it seems to be working with that.

**Comment by deadvirusllc** [comment]
Have you tried reinstalling both spotify and snip?

**Comment by ruskiar** [comment]
Reinstall of Spotify did the trick.

**Comment by sammyboy405** [comment]
​I Just reinstalled Spotify and same Issue.. Its gotta be something simple.

**Comment by dlrudie** [comment]
So if the token link above works for everyone. Does this link work as well?
https://open.spotify.com/token

Snip will get a token from the local web server as well as Spotify's service. It will also acquire an authorization token using the previous two tokens as well. All of those tokens have to be valid.

**Comment by dlrudie** [comment]
Another thing to try is running Snip as Administrator.

**Comment by dlrudie** [comment]
Okay, try running [this debug file](https://impas.se/temp/Snip-680-DEBUG.zip). It's going to open a console window. Feel free to try it out and paste the contents to [Pastebin.com](https://pastebin.com/) and provide the link.

**Comment by dlrudie** [comment]
For example this is how a properly playing Spotify looks (I had Spotify open and playing a track before starting Snip).

![bl7hvbt](https://user-images.githubusercontent.com/1780069/27668847-067238d4-5c49-11e7-81ed-d2e4df21d5f8.png)

**Comment by sammyboy405** [comment]
Yes that Token URL Worked it returned properly

**Comment by sammyboy405** [comment]
Tried Admin, Same Results.  I see you posted a Debug Version I will try it
and report back

**Comment by sammyboy405** [comment]
*Here is the Pastebin with the Results of the Debug.*


*https://pastebin.com/WEhQQYgc <https://pastebin.com/WEhQQYgc>*

**Comment by dlrudie** [comment]
Okay. Let me change a few things.

**Comment by sammyboy405** [comment]
Thanks.  This is a very useful tool for Streamers.. I Appreciate ya taking the time to tweak it

**Comment by dlrudie** [comment]
Alright, redownload the file above.

I removed some debug logging to clear it up some. I also added additional logging to call out certain reasons why it may have failed.

Post results please.

**Comment by sammyboy405** [comment]
Here you go Sir.  https://pastebin.com/08XFNpPG

**Comment by sammyboy405** [comment]
And yes WebHelper is running.  and Spotify as well.

**Comment by dlrudie** [comment]
So it most definitely cannot see your SpotifyWebHelper.exe.

**Comment by sammyboy405** [comment]
![image](https://user-images.githubusercontent.com/29761775/27669289-90f5fc3c-5c4b-11e7-9ac9-aedcc6d8952b.png)
 
It is running

**Comment by sammyboy405** [comment]
What would could be blocking access to see it? im Running Windows 10, if that matters.

**Comment by dlrudie** [comment]
Nothing. It's likely some awkward port differences.

**Comment by sammyboy405** [comment]
is there something I can run to see what port its using? would netstat tell me?

**Comment by dlrudie** [comment]
Once again. Redownload the file above and try it.

**Comment by sammyboy405** [comment]
Looks to be the same
https://pastebin.com/AwM9F6Qw

**Comment by dlrudie** [comment]
Sure then. Run this from a command prompt:

netstat -an | grep :43

If you don't have grep just look for any open ports between 4370 and 4389.

**Comment by dlrudie** [comment]
Actually, if you have curl that would make testing substantially easier.

https://bintray.com/vszakats/generic/curl/7.54.1

Download either one
curl-7.54.1-win32-mingw.7z
curl-7.54.1-win64-mingw.7z

You only need to extract whatever is in the bin folder.

Once that is done run this command from a command prompt (within the directory with curl.exe)

curl -H "Origin: https://open.spotify.com" https://snip.spotilocal.com:4370/simplecsrf/token.json
curl -H "Origin: https://open.spotify.com" https://snip.spotilocal.com:4371/simplecsrf/token.json
curl -H "Origin: https://open.spotify.com" http://snip.spotilocal.com:4380/simplecsrf/token.json
curl -H "Origin: https://open.spotify.com" http://snip.spotilocal.com:4381/simplecsrf/token.json

**Comment by dlrudie** [comment]
I went ahead and just changed the port.

Download the DEBUG snip file again and re-test it out. Thanks!

**Comment by dlrudie** [comment]
Fixed in edd4bb0

**Comment by MCHAMSTERYT2** [comment]
> ok so go to advanced options in Spotify App and turn on "Allow spotify to be opened from the web" . . with it disabled it doesnt run the spotifywebhelper.exe

I Don't Have That Setting And The Same Thing Is Happening To Me
