### ISSUE TITLE
Uppercase variables not carrying over when the information is in seperate text files

### ISSUE THREAD

**Issue by UltimaTheHawke** [dlrudie/Snip#168]
I was planning to use the new uppercase variables using different text files, which seem to be working just fine for the normal text file (Snip.txt), however it just simply appears as $$ut and $$ua.

**Comment by dlrudie** [comment]
What do you mean?

You said it appears to be working fine for Snip.txt but it appears as $$ut and $$ua. Where does it appear as such? Please clarify. Thank you!

**Comment by UltimaTheHawke** [comment]
What I mean is, Snip.txt outputs correctly, but Snip_Track and Snip_Artist don't, it just simply appears as $$ut and $$ua.

![screenshot_18](https://user-images.githubusercontent.com/8317392/27515133-bd240114-5994-11e7-954c-964fc4824453.png)
