### ISSUE TITLE
Snip isn't working with Spotify

### ISSUE THREAD

**Issue by jingtongtangflee** [dlrudie/Snip#173]
Hi! Today I updated Spotify and Snip after long time and Snip isn't working! It says "Spotify is not currently running". The latest working version is v6.0.5.

**Comment by TheWhiteArchon** [comment]
having the same issue have to open snip and choose spotify every 3 min for it to update song

**Comment by dlrudie** [comment]
Alright. Looks like I may have to implement port scanning.

**Comment by jingtongtangflee** [comment]
I found fix. I added 
"127.0.0.1		snip.spotilocal.com"
to my hosts file and now it's working!

**Comment by deadvirusllc** [comment]
I was having the same issue on another pc and your partial solution gave me a tip as to what is causing the problem.

See if this works,  

In Windows 10: 
Open Control panel, network and sharing center, then choose "Change adapter settings" on the left.
"Right" click on the adapter you use for your internet connection and select properties.
Click on "Internet Protocol Version 4(TCP/IPv4)" then Click the "Properties" button.
Click the radio button "Use the following DNS server address:"
Then enter the following:

Preferred DNS server  8.8.8.8
Alternate DNS server  8.8.4.4

Then hit OK and close all related windows.

See if SNIP is updating now.

**Comment by jingtongtangflee** [comment]
I don't use Google's DNS as preffered DNS because of bad location. It's giving me servers from Belgium which are far away from me. And I don't think that's the fix. It works the same as editing hosts file.

**Comment by TheWhiteArchon** [comment]
deadvirusllc tried that doesn't work still does the same :(

**Comment by dlrudie** [comment]
It's a port issue. I have a fix committed already. I just haven't built a new release yet.

**Comment by dlrudie** [comment]
Fixed with v6.9.1. (I'm hoping)

**Comment by jingtongtangflee** [comment]
Yeah, fixed :smile: . Thanks!

**Comment by Fonck97** [comment]
Snip is not recognizing at all Spotify, Snip text file always empty

**Comment by leonx132** [comment]
nope not fixed

**Comment by wzrdshep** [comment]
Are there any other suggestions? I've tried just about everything to get this back up and running and nothing is working :|
