### ISSUE TITLE
Can't set output format

### ISSUE THREAD

**Issue by nrataw** [dlrudie/Snip#175]
Hello,
I'm referring to this issue: https://github.com/dlrudie/Snip/issues/153
My problem is exactly the same despite you mentioning that the issue has been addressed. Using the latest version of Snip and VLC player. The txt file is updated upon changing songs, however altering the output format has no effect on it. 
Any help is greatly appreciated!

**Comment by dlrudie** [comment]
This is not an issue of Snip. VLC doesn't support any feature such as output formatting or anything. Snip only reads the titlebar from VLC and outputs it. It cannot determine the differences between track titles, artists, albums, etc. therefore it does not know how to format them.

**Comment by Neodark7** [comment]
@dlrudie is there at least a way to add a space at the end of the line ? to avoid that 
![image](https://user-images.githubusercontent.com/7981869/28678213-12916d5c-72f0-11e7-8c27-2d8f725eb640.png)
