### ISSUE TITLE
Old song's been removed

### ISSUE THREAD

**Issue by Pancho111** [dlrudie/Snip#179]
HI , 
I would like to have a history of all songs that have been  playing and the snip.txt is only showing the song playing at the moment.
is the script meant to be like this ?
I don't see the Snip_History.txt , do I have to create this file ?
I am using windows 10 and VLC

thank you in advance

**Comment by dlrudie** [comment]
You have to enable history saving by right-clicking on Snip. Then as you play music Snip_History.txt will populate.
