### ISSUE TITLE
My PC downloads Snip as a 7Z File but it's a picture. Nothing to extract.

### ISSUE THREAD

**Issue by Darlune** [dlrudie/Snip#184]
Every time i try to download the latest version of Snip I end up downloading a 7Z File which ends up being a picture and nothing else. Not even a file to extract from. I can download the Source codes on where i can extract from there but the Snip.exe isnt in those files. Is this something I'm doing wrong or completely missing?

**Comment by murko69** [comment]
Do you have 7z installed or what do you use instead?
If you downloaded the 7z-file you should just right-click on it and extract (or even: right-click=>7zip=>extract here/extract to....)

So steps to take:
1. Download the latest 7z (right now that [6.9.1](https://github.com/dlrudie/Snip/releases/download/v6.9.1/Snip-v6.9.1.7z))
2. Save file
3. Open directory where you save the 7z-file
4. right click on it=>7-zip=> extract to.... (or similar if you have another file archiver)
5. Now you should have a complete Snip-folder to put anywhere you like
The source code doesn't contain an .exe. You need to build that on your own so it really is the 7z-file you want.

**Comment by dlrudie** [comment]
Thanks @murko69.
