### ISSUE TITLE
Album artwork won't show up randomly

### ISSUE THREAD

**Issue by dididan2000** [dlrudie/Snip#186]
The album cover will show up most of the times, but there is a rare time where it will just show blank for a song, so I have to go to spotify and go to the last song before it and then go to the song that had the blank album artwork to have it show properly.

**Comment by lwilletts** [comment]
Can confirm this is happening to me rarely with the google play music player. Sometimes starts reading the file then it cuts off and the rest of the image is black. Skipping through the tracks will fix it though.

**Comment by dlrudie** [comment]
I'll have to duplicate this. For reference, what's the download speed of your internet?

**Comment by dididan2000** [comment]
75 Mbps up and down
		
		

		
	




On Tue, Aug 8, 2017 at 8:45 PM -0400, "David Rudie" <notifications@github.com> wrote:












I'll have to duplicate this. For reference, what's the download speed of your internet?

**Comment by richo67** [comment]
Is downloading of album artwork over http and therefore depends on proxy settings? I see no album artwork. Connected to Spotify inside corporate network behind the proxy.

**Comment by dlrudie** [comment]
Artwork is downloaded over http, yes.
