### ISSUE TITLE
Snip doesn't show the name/artist of music that is using local files

### ISSUE THREAD

**Issue by deathb4retreat** [dlrudie/Snip#188]
Pretty much self explanatory. I had somebody sing and record to have their music put on my stream, however I noticed that any time their songs are playing on Spotify, Snip believes that Spotify either isn't open, or that no music is being played. 

Considering I want to give them credit, this doesn't help

http://prntscr.com/g3rjnd (image with it showing saying "Spotify is not currently running"

**Comment by murko69** [comment]
Probably same as #174

**Comment by dlrudie** [comment]
Duplicate of #174.
