### ISSUE TITLE
Ability to display one artist?

### ISSUE THREAD

**Issue by aminbenjilali** [dlrudie/Snip#195]
Hello,
I just downloaded your software and really enjoy, but there is one thing bothering me. I would like to know if there is the ability in the output format to just show one artist (especially when there are a lot of artist in one song) it makes a really long text file.

Kind regards and keep up the good work

**Comment by YoureNotGodBro** [comment]
Yeah I noticed this issue as well. I sort songs by Album Artist in iTunes and keep that field simple. Is there a way to add a tag for the Album Artist field?
