### ISSUE TITLE
Snip output information separately Foobar

### ISSUE THREAD

**Issue by colmusic** [dlrudie/Snip#196]
Snip doesn't seem to be able to output information to separate text files when using foobar. Really need to get the artist and song into separate text files but am instead left with blanks.

**Comment by colmusic** [comment]
Works fine with just snip.txt put cannot seem to do more than just that.

**Comment by omfgblondie** [comment]
It works partly for me. "%artist%–%title%" in the Window Title gets me the artist and track names in the correct files (documentation is reversed though). It can't figure out a way to get the Album to write out to its separate file, nor does Album Art save.

**Comment by dlrudie** [comment]
README specifies how to set up foobar.
