### ISSUE TITLE
Crashes as soon as it opens

### ISSUE THREAD

**Issue by jonathanthebonk** [dlrudie/Snip#197]
Running the latest version of Snip, a few seconds pass then it just says [this.](http://i.imgur.com/CX1CtnK.png)

Tried running as admin and redownloading several times.

**Comment by ftgcreeps** [comment]
i have the same issue

**Comment by dlrudie** [comment]
Which version of Windows is that? I use a lot of modern API's that may not be supported on older versions of Windows.

**Comment by ftgcreeps** [comment]
64bit win10 pro PCs custom build only 2 years old

👉Jake champion 👈

On Apr 1, 2018, at 11:51 PM, David Rudie <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #197<https://github.com/dlrudie/Snip/issues/197>.

**Comment by jonathanthebonk** [comment]
That was 7, I've since upgraded to 10 and it works fine.

Sent from my OnePlus smartphone

________________________________

**Comment by ftgcreeps** [comment]
What was 7

👉Jake champion 👈

On Apr 4, 2018, at 9:55 AM, jonathan <notifications@github.com<mailto:notifications@github.com>> wrote:

That was 7, I've since upgraded to 10 and it works fine.

Sent from my OnePlus smartphone

________________________________
