### ISSUE TITLE
cant find snip.txt file in folder

### ISSUE THREAD

**Issue by s0meoneyoukn0w** [dlrudie/Snip#20]
has the software changed because i cant find the snip.txt file in the folder i downloaded

**Comment by dlrudie** [comment]
When you run Snip.exe and play a track, there's a Snip.txt file that gets created alongside it that will contain the track information.

**Comment by djsind** [comment]
I downloaded and extracted "Snip-v4.6.0.7z" ... but there's no "Snip.exe" file within. Is there an additional download that I'm missing? Thanks for the help!

**Comment by johnanselmo-s3i** [comment]
I also can't find the text file no matter what. I checked 'Save Track History' but no text file is showing up.
