### ISSUE TITLE
SpotifyWebHelper starts lagging when Snip is running

### ISSUE THREAD

**Issue by ruskiar** [dlrudie/Snip#200]
When Snip is running I get lag on all audio on the machine. The SpotifyWebHelper.exe process consistently uses 2-3% of CPU time and all machine audio stutters and lags. During the time that Snip is running the web helper process IO is steadily growing. Killing Snip immediately drops web helper CPU time to 0, Other IO goes to 0 as well, and audio lag immediately stops.

About 5-10 seconds after starting Snip the lag, CPU time, and IO go awry and the lag starts. This has been an issue for a week or so and has persisted through Snip and Spotify reinstalls.

Running on Windows 7 with most up to date Spotify and Snip installs.

**Comment by ruskiar** [comment]
Still trying to troubleshoot this issue. below is a screenshot from DPC Latency Checker that shows when Snip starts running latency skyrockets and results in audio lag.
![image](https://user-images.githubusercontent.com/2279415/31639013-751c266c-b28b-11e7-8219-b9dec763a24d.png)

**Comment by ruskiar** [comment]
After some troubleshooting I was able to alleviate the problem a little bit by updating the Nvidia graphics driver so lag and stutter does not make audio unbearable to listen to but the lag is still there. Hopefully this helps in troubleshooting.

![image](https://user-images.githubusercontent.com/2279415/31797735-be51da6a-b4e4-11e7-8224-0d7a42ae5ac1.png)

**Comment by dlrudie** [comment]
This doesn't seem to have ever affected me. Snip does lag on start because it's probing SpotifyWebHelper for communication. Once connected it shouldn't consume any more CPU.
