### ISSUE TITLE
foobar reading files backwards and error when I try to use itunes.

### ISSUE THREAD

**Issue by HoarderofData** [dlrudie/Snip#201]
I am trying to use snip with foobar. But when I play a track the info is displayed backward. All settings are correct as can be seen from the below screenshot.

https://imgur.com/PnAQWAA

So I tried itunes, But when I click iTunes in snip I get an error as can be seen in the below screenshot.

https://imgur.com/b8lSjhW

Any idea why these issues are happening and how to fix them?

Thanks.

**Comment by omfgblondie** [comment]
So, it seems that for some reason Snip reads the Window Title in the opposite order stated. If you entered "123 – 456", you would get 123 written to the Artist file and 456 to the Track file. It seems to me that it doesn't check for Album at all.

To quickly fix your issue, just change Window Title to "%artist%–%title%"

**Comment by dlrudie** [comment]
I originally did it in this order because that's how Spotify originally operated. It was easy to duplicate. Since then it has been stuck that way. I may change it back but then everyone who has already configured it will have it backwards again. I'll see.

See #202 for iTunes-related fixes.
