### ISSUE TITLE
Album Display

### ISSUE THREAD

**Issue by EvilWalks** [dlrudie/Snip#203]
Hi there. Anyone know a way to force snip not to write the Album field? I want it to just pull the Artist - Track and skip the Album field altogether. 

Any help would be much appreciated.

**Comment by dlrudie** [comment]
Which media player are you using? Album is entirely optional already.

**Comment by EvilWalks** [comment]
Foobar2000... How do I get it to just not display the album? Or perhaps have it display after track name? Because right now, I can't see to stop it writting Aritst - [Album - Track #] - Track Name. No matter what I put in the format box for album?

**Comment by Happiys** [comment]
SUPPORTED FEATURES FOR PLAYERS
Spotify: Artist, Track, Album, Artwork
iTunes: Artist, Track, Album, Artwork
Winamp: Artist, Track
foobar2000: Artist, Track <-----------------------------------------------------
VLC: Nothing (It uses whatever the titlebar says)
Google Play Music Desktop Player: Artist, Track, Album, Artwork
Quod Libet: Nothing (It uses whatever the titlebar says)
