### ISSUE TITLE
Having problems with the new iTunes in Windows

### ISSUE THREAD

**Issue by ksgant** [dlrudie/Snip#205]
Every time I select it, it tells me to please exit iTunes and reselect iTunes from within Snip. But when I do it gives the same error:

Error: HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by Kurtessis** [comment]
Same here. any word on next update release?

**Comment by Zamtron** [comment]
Yep same here

**Comment by Kokarcito** [comment]
Same problem :(

**Comment by MackKnife** [comment]
#5

**Comment by OmarJoseph** [comment]
Yup, been having this problem for over a week now.

**Comment by dlrudie** [comment]
Duplicate #202
