### ISSUE TITLE
Snip not generating Snip.txt file

### ISSUE THREAD

**Issue by Sicknasty92** [dlrudie/Snip#206]
So fairly new to this, but Snip is showing the song im playing in spotify in the little icon at the bottom right, but its not generating the Snip.txt file so i can load it into OBS. ive re installed multiple times, re downloaded WinRar but whenever i extract to a folder on my desktop and double click, nothing happens. I've read through other issues and checked to make sure the SpotifyWebHelper is on, not sure what else im doing wrong.

**Comment by dlrudie** [comment]
If Snip is running and correctly shows the song that's playing then Snip.txt should be created.

Snip.txt gets created in the same directory as Snip.exe.
