### ISSUE TITLE
Error upon launch of Snip

### ISSUE THREAD

**Issue by kash0lt** [dlrudie/Snip#208]
Nasty dialog appears when Snip is started:

Please exit iTunes and reelect iTunes from within Snip.
Error HRESULT E_FAIL has been returned from call to a COM component.

It doesn't make any difference if I follow this instruction or not. No text from currently playing iTunes music ever shows.

I change over to Spotify and all works.

Back to iTunes and this error appears again.

Snip v6.9.1
iTunes v12.7.0.166

![capture](https://user-images.githubusercontent.com/19612764/31527421-4c099fce-af8a-11e7-9351-fb9744d80cdd.JPG)

**Comment by dlrudie** [comment]
Duplicate #202
