### ISSUE TITLE
Cant find snip?

### ISSUE THREAD

**Issue by QebQake101** [dlrudie/Snip#209]
cant find the application, how do i open it

**Comment by QebQake101** [comment]
i cant open it its like a .sln file

**Comment by Kurtessis** [comment]
you have to unzip it

**Comment by QebQake101** [comment]
i extracted it, is that different?

**Comment by QebQake101** [comment]
i used both winraw and 7-zip and extracted the snip master to my desktop, i clicked on snip.sln but it says i have to find an app to open it with? how do I open it?

**Comment by dlrudie** [comment]
You downloaded the source code. Why did you download the source code?

https://github.com/dlrudie/Snip/releases/latest

Download Snip-v#.#.#.7z.
The other files are source code and not the actual program.

:)

**Comment by QebQake101** [comment]
thx, geez im stoopid
