### ISSUE TITLE
Needs to support album name for foobar2000. Also, foobar track and artist wrong way round.

### ISSUE THREAD

**Issue by Tantusar** [dlrudie/Snip#22]
That's about it, actually.

**Comment by dlrudie** [comment]
I don't really have any plans to add support for album artwork through foobar2000.  The readme file explains the format needed for foobar2000 to display title and artist correctly.

**Comment by lwilletts** [comment]
Is there even a solution for grabbing album art through foobar2000? I would be very interested in getting this working as foobar is currently the lightest supported player which is a key factor for a fair few streamers to save CPU. To get local file playback with the album art display I'd have to install spotify which is not inciting, or even worse iTunes.
