### ISSUE TITLE
Spotify local file data not being read.

### ISSUE THREAD

**Issue by ChayKun** [dlrudie/Snip#222]
I'm just wondering if there'll be any sort of fix for this coming in the near future? 

I'm not sure about the technical side of things, or how hard it would be to integrate it, but with there being no support for WMP the closest thing would have to be Spotify. However I still run into the issue of nothing coming up when using local files, which really bugs me because the main reason I want a music ticker at this point is because I run OST I've personally downloaded and people usually ask me what it is, this would solve that, obviously. 

Why is it snip/spotify interact weirdly when referring to local files?

**Comment by spatnack** [comment]
As I understand dlrudie was not able to find a workaround for local files. My main issue with the local files not being read is that the saved information still displays the previously played song - is it possible to add an option to clear the title and artwork on a track ending to help alleviate this, or just load some default "local file playing" and artwork instead?

**Comment by dlrudie** [comment]
Snip just reads data from whatever Spotify provides. I'll figure it out eventually but local files aren't a priority to me at the moment.
