### ISSUE TITLE
iTunes integration not working

### ISSUE THREAD

**Issue by baterax** [dlrudie/Snip#223]
Hello!
Wonderful little piece of software, except I can't get it to do what I want it to, because:
- When I first ran it, I had iTunes open. When I right clicked it in the tray and selected iTunes, I got an error asking me to close iTunes and then re-select it from the menu. Under this, there's also two sentences that say "No such interface supported".
- Ok so I did it, but no luck: "no such interface supported" error. Again.

What now? Help!
Thanks in advance.

**Comment by MrXXIV** [comment]
Happening to me as well. Tried 6.8 and up. This might be an issue on iTunes side, but more or less a change that or upgrade needed to Snip in order to access iTunes again.

![untitled](https://user-images.githubusercontent.com/1838536/32712559-410d6c94-c813-11e7-9c7d-aab94b688504.png)

**Comment by baterax** [comment]
Mine is a different error:
![snip](https://user-images.githubusercontent.com/8533902/32723203-8c0e34ca-c864-11e7-9dcc-0ab790bddb54.PNG)

**Comment by markspolakovs** [comment]
#202 is tracking the iTunes issues. TL;DR: something was changed on Apple's side, no obvious way to fix it

**Comment by ratedrko** [comment]
is this ever gonna be fixed?

**Comment by markspolakovs** [comment]
From #202:

> There's zero documentation on this so I'm stuck playing around with it until I find something that works.

> They either changed them or removed them internally.

Probably, however it seems like @dlrudie is dealing with real life, and this is a non-trivial fix.

**Comment by dlrudie** [comment]
Will review this hotfix soon. Thanks for the support!

**Comment by dlrudie** [comment]
Hotfix for #202. Still need to review this. It looks like a solid hotfix but I want to try to update iTunes (still on old version) and tinker with it some more before I push forward with this at the moment. I still think I can figure it out. :)
