### ISSUE TITLE
Is it possible to switch source without using the right-click menu?

### ISSUE THREAD

**Issue by luxidoptera** [dlrudie/Snip#226]
Hey so I'm planning on using Snip as a "now playing" widget for livestreaming purposes, but I can't actually use it right now because I don't have Spotify (and I don't really want it) and the right-click menu freezes when I open it. Is there some way to switch the source to another option without using the right-click menu and, thus, freezing the program?

**Comment by markspolakovs** [comment]
Right-clicking shouldn't be freezing it, unless it's looking for Spotify... Weird, I'll look into it. In the meantime, open regedit, browse to `HKEY_CURRENT_USER/Software/Snip/6` and change `Player` to something other than the default.

**Comment by dlrudie** [comment]
The whole Spotify freezing was fixed locally. It had to do with it searching for Spotify's local web service. It only happens upon first start.

There's a commit I need to review that allows it to just see all players without switching manually.
