### ISSUE TITLE
Set Output Format Not Saving

### ISSUE THREAD

**Issue by deathheart14** [dlrudie/Snip#227]
I am using VLC player.
When I try to apply a spaces at the end of the  track or artist.

I am trying to add a space so while it is scrolling it it will not look like it is running together.

**Comment by TWonderchild** [comment]
Same here, even tried older versions down to 5.x it just doestn work.
Latest Win 10, VLC player.

**Comment by dlrudie** [comment]
The output will not update if Snip does not accurately detect the track from VLC. It looks for a specific format (see README) and if it detects it correctly it can divide it up and figure it out.

**Comment by SavageDrago** [comment]
Sorry for the multi-posting, but can't find any fix to the output thing. What now? Thanks!
