### ISSUE TITLE
Difficulty installing

### ISSUE THREAD

**Issue by Shift-F7** [dlrudie/Snip#228]
Hello

just run into a snag installing this. I'm new to the programming scene, and it's been years since I've used CLI.

Install instructions: 
4: Run run.py to generate a config file
5: Configure the file with your token and path to snip.txt Neither should have quotation marks
6: Start run.py

Is there a difference between "Run run.py" and "Start run.py"? I've seen some screenshots of people typing "python run.py", but I'm not having luck.

I've found run.py in C:\Users\$USER$\AppData\Local\Programs\Python\Python36\Lib\idlelib - is this the correct file?

Thanks in advance
-SF7

**Comment by markspolakovs** [comment]
@Shift-F7 Are you sure this is the right project you're posting the issue to? There's no Python in Snip.

**Comment by Shift-F7** [comment]
jfc, no, it's the wrong project! apologies
