### ISSUE TITLE
Extended String Formatting Options

### ISSUE THREAD

**Issue by Jademalo** [dlrudie/Snip#232]
At present, it seems like while we can control individual parts of the formatting (Track/Separator/Artist/Album), there's no way to change the master string that's saved into Snip.txt.
From my brief testing, it seems to be Track+Separator+Artist.

I have a workaround to get the string I want by deleting everything in the other boxes and putting my string in the track box, but it's not particularly elegant and ruins the Save Information Separately files.

Would it be possible to have an extra option in formatting options to change the master string dumped to Snip.txt?

Thanks!

**Comment by markspolakovs** [comment]
It's an idea I've had for a little while but haven't had time. I'll see if I can put together a PR in the next few weeks - no promises though

**Comment by dlrudie** [comment]
Snip.txt will update with what you have set in each field. It does use the format of Track+Separator+Artist. However it's fully customizable. Swap artist and track if you want. Change separator to be blank or use whatever. Add spaces or quotation marks. It's up to you.

I do eventually plan to make a better customizable interface but I won't have time until some time after the holidays.

**Comment by Jademalo** [comment]
I've been using that as a workaround and it's been working fine. Biggest issue is it's not compatible with the Save Information Separately files at the same time, I've got to set it up for either/or.

Thanks!
