### ISSUE TITLE
Include option to make Output Format tags use capital letters only.

### ISSUE THREAD

**Issue by lwilletts** [dlrudie/Snip#233]
I've got a great font that I am using for streams, but unfortunately the lower case is completely unreadable. Adding this feature would be great.

**Comment by markspolakovs** [comment]
This is an undocumented feature, but you can use `$$ut` for the track name, `$$ul` for the album, and `$$ua` for the artist, which will make it be uppercase.

**Comment by dlrudie** [comment]
Thanks for helping out @markspolakovs. There are quite a few undocumented text options. I think I've never documented them as I never really felt as if they should be a supported feature. I don't want to have a thousand $$xx variables. I'd like to make a nice interface where you can just select what's supported from there.

Anyway, yeah, $$ut/a/l.
