### ISSUE TITLE
Snip not working correctly with ITunes 

### ISSUE THREAD

**Issue by WolfManKing** [dlrudie/Snip#236]
I'm a beginning streamer putting music from itunes onto my steam, but when i open Itunes through snip i get this error message
![capture](https://user-images.githubusercontent.com/34862214/34358401-1bc9c996-ea9b-11e7-8a7d-eda57bb2647a.JPG)
All of the music has been downloaded through apple music, but i get this message when itunes starts up through Snip.

**Comment by markspolakovs** [comment]
Duplicate of #202.

**Comment by dlrudie** [comment]
Duplicate #202
