### ISSUE TITLE
Spotify isn't running

### ISSUE THREAD

**Issue by Ryobe-XCIX** [dlrudie/Snip#242]
I have Spotify open and with a song playing, in snip.txt it's showing the song but in OBS it's always showing "spotify isn't running". Sometimes it works and sometimes this happens. Ideas?

**Comment by Ryobe-XCIX** [comment]
Hello?

**Comment by pedrofracassi** [comment]
Try setting OBS to update the text faster

**Comment by Ryobe-XCIX** [comment]
How is that possible? Also it's not a problem of taking too long, it's a problem of never happening.

**Comment by pedrofracassi** [comment]
You need to have Snip running for it to update the text. Have you checked this?

**Comment by Ryobe-XCIX** [comment]
Yes

**Comment by Ryobe-XCIX** [comment]
Help please xD

**Comment by GenesisFR** [comment]
Make sure you have the latest version of OBS, I tried both with a "Text (GDI+)" and a "Text (FreeType 2)" source and they're both working fine for me on OBS Studio 21.0.1 (Win10 x64). I'm also using the Empty File If No Track Playing option on Snip (it works fine without it).

**Comment by Ryobe-XCIX** [comment]
Doesn't work for me Idk

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dlrudie** [comment]
OBS issue, not Snip.
