### ISSUE TITLE
It's 2018 and the output editing error still persists.

### ISSUE THREAD

**Issue by Bearded-Expense** [dlrudie/Snip#245]
Title says it all. When I edit the output settings, they don't change and it looks like shit when the name of the artist and song are all clumped together.

**Comment by FelipeGodoyG** [comment]
same

**Comment by Karlyr** [comment]
same

**Comment by dlrudie** [comment]
It's 2018 and the output editing still works fine.
https://i.imgur.com/jlFJEhb.png

Provide some more details so I can try to figure out what's going on.

What media player are you using? How are you editing the output format?
Output formatting really only works with Spotify and iTunes(When I can get iTunes working again).
The other players can work possibly if you set up the titlebars of the players.

**Comment by Zamtron** [comment]
I would really appreciate a fix for iTunes, good luck on that. c:

**Comment by dlrudie** [comment]
iTunes fixed itself. Make sure you’re running the latest version of iTunes. As of writing this 12.7.4 is the latest.

**Comment by DemonLied** [comment]
I'm using Foobar2000 ver 1.3.8 and I am having the output issue as well. Is there a possible fix?

**Comment by dlrudie** [comment]
Just follow the README for setting up the window title and it should attempt to separate the artist and track. If it can't detect the separation between artist and track then it just outputs it as a whole without output changes because it has no idea what's what.

**Comment by DemonLied** [comment]
Ahh so the output formatting issue isn't necessarily a bug, it just reads the formatting straight from Foobars formatting

**Comment by tedewen** [comment]
VLC 3.0.2 64 Bit
No format changes take hold, and text is run together on screen (OBS Studio).

**Comment by ayancey** [comment]
Quick tip to @Bearded-Expense. NEVER start an issue with the title "It's {CURRENT_YEAR} and..."

**Comment by Bearded-Expense** [comment]
@ayancey yo; I'm coming back 2 this thread a little later cuz I wrote this a few months ago

at the time that I wrote this thread, I was a little pissed off because it wasn't working. I went to github like immediately so I was still kinda pissed and I wrote a rly stupid and passive aggressive title to the guy who's obviously worked hard on making snip in the first place. I try my best to not let anger cloud my decision making, but I guess I slipped a little bit, and I apologize for that. I do still have the error, but this time, snip as a whole just Isn't displaying anything. If anyone could help me fix this, I'd appreciate it a lot!

**Comment by MeikelLP** [comment]
@Bearded-Expense do you work with Spotify? If yes try the latest release as due spotifys update we were required to make changes to snip itself.

**Comment by dlrudie** [comment]
The output will only be formatted if it can detect the separation of artist and track.

For iTunes and Spotify this works. For VLC, Winamp, foobar, and any other player that reads from the title bar it needs a solid separation. The readme file included with Snip goes over it.
