### ISSUE TITLE
Scrolling song artist and title in output - Winamp

### ISSUE THREAD

**Issue by BunnyHelp** [dlrudie/Snip#246]
As said in the title, the output is "scrolling along" with asterisks to separate the beginning and ends.
[It looks like this ](https://puu.sh/zmDFX/a5c2b773e4.png).
How would I / can I have just the artist and song title without this?

**Comment by dlrudie** [comment]
I don't understand what you're trying to do. The README explains how to set the Winamp titlebar up. You can customize the output in Snip from there.

**Comment by BunnyHelp** [comment]
I've already done everything in the README, but it's not outputting "correctly".
I just want Snip to take the artist and title of the song from what's currently playing in Winamp, in the format of `%artist% - %title%`. It *is* doing that, but it's sort of wrapping on top of its self like shown in the link above. (Here is it in action)[https://puu.sh/zUqdh/385fa12718.gif]
How do I make the output only `Avi & Surasshu - Shapeshifter`?

**Comment by dlrudie** [comment]
That's winamp adding the ***'s then. I'd check to see if there's a way to make Winamp not autoscroll, and make sure Winamp isn't adding the *'s. Snip just grabs the window title of Winamp and that's all. You'll just need to adjust Winamp's settings.
