### ISSUE TITLE
Nothing is working.

### ISSUE THREAD

**Issue by LGMarine** [dlrudie/Snip#248]
The only thing I'm able to do is download the link. From there, only the README file opens. The Snip icon doesn't even show up in the tray like it's supposed to. If you can help me, I'm willing to try again. If not, I'm just going to assume it to be a broken download.

**Comment by dlrudie** [comment]
Make sure you download and extract the .7z file. Not the source .zip file. Then run Snip.exe and it should appear in the tray.
