### ISSUE TITLE
Crashing on start-up!

### ISSUE THREAD

**Issue by PP2468100** [dlrudie/Snip#25]
Hey,
       I have recently been trying to use Snip for OBS as I would like to start live streaming in the near future. On the first time start-up, it worked completely fine but every single time after it just crashes as soon as I click on .exe. I was wondering if you could help me come up with a solution for this as I have tried downloading it again but it did not prevail.

**Comment by denolfe** [comment]
It looks like Spotify did a big overhaul of its UI. The song name is no longer showing in the window title, which I assume is causing issues.

**Comment by dlrudie** [comment]
#26 is a Duplicate of this.
