### ISSUE TITLE
Key shortcut for displaying the current song notification

### ISSUE THREAD

**Issue by richo67** [dlrudie/Snip#250]
This is more request, not a issue/bug.
**Would it be possible to re-trigger notification to display currently playing song?**
Currently one can see this notification when new song starts playing. If I want to know what isplaying I need to grab a mouse and got to Snip icon.
What is I pressed **CTRL-ALT-?** to trigger displaying of notification again?
Possible?
Thank you.

**Comment by richo67** [comment]
It would be great if these shortcut could be user defined. I had issue with CTRL-ALT_M which is also used by MS Word for creating comment.

**Comment by dlrudie** [comment]
A redesigned options panel is already in the works that will let you customize hotkeys (and other settings).

I'll add some options for re-displaying the notification as well as setting a timer (I believe the API allows for specifying a time).
