### ISSUE TITLE
Snip.exe is no where to be found and i have everything downloaded and exracted

### ISSUE THREAD

**Issue by THeLordBacon123** [dlrudie/Snip#251]
![2018-02-27](https://user-images.githubusercontent.com/36903065/36759551-97beefe2-1bcc-11e8-8587-302f0ffef6bf.png)
![2018-02-27 6](https://user-images.githubusercontent.com/36903065/36759559-a6635e8e-1bcc-11e8-9755-93a97520606f.png)
![2018-02-27 5](https://user-images.githubusercontent.com/36903065/36759565-adb2c5b2-1bcc-11e8-92d0-ff7c37c489dd.png)
![2018-02-27 4](https://user-images.githubusercontent.com/36903065/36759567-af5a74f0-1bcc-11e8-821d-c4174d9dffc1.png)
![2018-02-27 3](https://user-images.githubusercontent.com/36903065/36759569-b1484148-1bcc-11e8-944b-1a4e378f3228.png)
![2018-02-27 1](https://user-images.githubusercontent.com/36903065/36759570-b2f50ef4-1bcc-11e8-9f2c-1ac8590634d2.png)
![2018-02-27 2](https://user-images.githubusercontent.com/36903065/36759652-f6974000-1bcc-11e8-9a2c-01f7863c081e.png)

i have it extracted and i cant find Snip.exe

also if im missing something let me know cause i have 
both the .7z and the .zip installed and when ever i download a previous version its the same as this

**Comment by THeLordBacon123** [comment]
i should also mention that no one no matter where i looked could give me answer nor did the github issues page for Snip help

**Comment by markspolakovs** [comment]
You've downloaded the source code. Download the compiled .zip at https://github.com/dlrudie/Snip/releases/download/v6.9.1/Snip-v6.9.1.7z

**Comment by THeLordBacon123** [comment]
i download both the zip and .7z though

**Comment by markspolakovs** [comment]
That's odd. Are you sure you're downloading the .7z I linked to above?

Here are the contents of it, as I download it:
!()[https://i.imgur.com/jR2yMOA.png}

**Comment by dlrudie** [comment]
The screenshots above are of the source code .zip file. You need to get the .7z file and extract it.
