### ISSUE TITLE
Snip_Artwork doesnt show any picture

### ISSUE THREAD

**Issue by ItzSheldor** [dlrudie/Snip#254]
see above

**Comment by GenesisFR** [comment]
Did you enable the "Save Album Artwork" option? Which player are you using? I looked at the code, this feature is not supported for foobar2000 and Winamp and doesn't seem to be implemented for VLC and QuodLibet.

Here are my settings, it's working for me on Spotify desktop:

![untitled](https://user-images.githubusercontent.com/3614449/37065211-efc27b5e-216d-11e8-9e81-77ae0974a5db.png)

**Comment by ItzSheldor** [comment]
yo, ive enabled this and im using spotify tho

**Comment by dlrudie** [comment]
Artwork still working fine here.

Save Album Artwork will save it to the same directory as Snip.
Keep Spotify Album Artwork will let you select which size, but the option is also a checkbox itself. Make sure you actually click on "Keep Spotify Album Artwork"
