### ISSUE TITLE
Add the ability to save as json

### ISSUE THREAD

**Issue by jateuu** [dlrudie/Snip#259]
Would be great if you could json option. I used javascript to animate song change with snaz, but it isn't sadly updated anymore.

**Comment by dlrudie** [comment]
If you enable the Cache Spotify Metadata option it will save the JSON to a file.

**Comment by jateuu** [comment]
Yes but it creates new file every time song changes. Having just one file that it modifies would be great.

**Comment by dlrudie** [comment]
Alright, I can add that.
