### ISSUE TITLE
** MEDIA PLAYER ADDITIONS TO SNIP **

### ISSUE THREAD

**Issue by dlrudie** [dlrudie/Snip#263]
This is a consolidated list for players that were requested. If you'd like a certain media player supported post in this issue. While I likely will not add support for these players myself, Snip is open source for anyone else to contribute.

- Desktop Players
[AIMP](http://www.aimp.ru/)
[Amazon Music Desktop Player](https://www.amazon.com/b?node=16962657011)
Groove Music (Windows Store)
[Kodi](https://kodi.tv/)
[Soundnode](http://www.soundnodeapp.com/)
Spotify (Windows Store)
Windows Media Player

- Web-based Players
[Pretzel](https://app.pretzel.rocks/player)
[TIDAL](https://listen.tidal.com/)
[YouTube](https://youtu.be) - #92

**Comment by crashturk** [comment]
sorry bad english

I need aimp support and lyric info file 
or
just lyric info file

**Comment by Blootrix** [comment]
Can you please add support for the application [Pretzel](https://app.pretzel.rocks/player). 
It has a downloadable version for Windows which is what I'm looking for support for, thanks!

**Comment by dlrudie** [comment]
@crashturk I have no plans whatsoever to implement lyric support.

**Comment by GenesisFR** [comment]
Groove Music has been discontinued by the way, so I guess there's no point adding support for it anymore: https://support.microsoft.com/en-us/help/4046109/groove-music-and-spotify-faq

**Comment by CptCatbutt** [comment]
Would it be possible to add support for Yandex.Music?

**Comment by Darthmullet** [comment]
I would love support for Media Monkey https://www.mediamonkey.com/

**Comment by Appleteezerz** [comment]
Hey, got anywhere with incorporating Amazon Music?  It's second best to Spotify (in my opinion) and a lot of people paying for amazon prime wouldn't need to go prime for Spotify (Plus Amazon have a better database of colleges/universities for discount membership for life) :)

**Comment by GenesisFR** [comment]
He dropped support for anything but Spotify/iTunes in v7.

**Comment by dlrudie** [comment]
See #404 on clarification as to why there’s less support.

If amazon has a really straight/forward public API that just works and doesn’t change constantly it’s something I can consider but I do lack a lot of free time.
