### ISSUE TITLE
Custom "No Track Playing" for Snip

### ISSUE THREAD

**Issue by yefeibin** [dlrudie/Snip#266]
I was wondering if you could implement a setting to let us enter in our own message instead of "No Track Playing". It seems like it would be something easy and useful. 

Not sure if this is where its saved, but it would be great to be able to change this - found under the resources Strings.txt

; This text is saved to the Snip.txt file when no track is playing in the
; selected media file or when the user stops/pauses a playing track.
NoTrackPlaying=No Track Playing

**Comment by dlrudie** [comment]
It's something I can add in the future. I have something in the works with a completely redesigned output formatting window and I'll be able to add this. No ETA though.

**Comment by parrotflakes** [comment]
Not sure if this will be seen or not, but custom text (or lack thereof) for when music is no longer playing would be dope.
