### ISSUE TITLE
Snip.exe is empty

### ISSUE THREAD

**Issue by ThatOneBrownKid** [dlrudie/Snip#272]
So I have been trying to setup Snip for a while now but to no avail. I first downloaded it last night (4/21/18) and it seemed to work fine. The next morning I was finishing up the aesthetics and it was working for 2-3 mins but just stopped. When I hover over Snip in the tray it says Spotify is currently running and the snip.txt file is empty when a song is playing. I have been looking through a lot of the forums and still haven't been able to fix it. Also, my Spotify WebHelper is open, but only sometimes. Sometimes it is open and sometimes is not, but whether it is open or snip.txt is empty. I would really like this program to work and would really appreciate any help.

**Comment by dlrudie** [comment]
Snip relies on SpotifyWebHelper to be running at all times. If it's not running then there may be a problem with your Spotify install. Also make sure the option to enable SpotifyWebHelper is selected in Spotify's settings.
