### ISSUE TITLE
snip  broken for itunes again ?

### ISSUE THREAD

**Issue by MackKnife** [dlrudie/Snip#273]
Since the new update on Itunes (12.7.4) Snip dosnt get any informations from Itunes .
snip.txt empty no cover and  history  is only the old ones before the update  

and yes im using  snip v6.9.5
Im using Itunes 12.7.4 on Windows 10

No errors  or anything else on snip  either itunes

**Comment by dlrudie** [comment]
Just tested iTunes v12.7.4.76 with Snip v6.9.5 and it's still working fine here. I'm also on Windows Pro v10.0.17134.

**Comment by phi-lam** [comment]
Hey man,

Thanks for the response, a reinstall fixed it. Sorry for the inconvenience!

Thanks,
Phi

**Comment by MackKnife** [comment]
im still waiting for a fix for the new itunes version  is there anyone out there which can build a fix
