### ISSUE TITLE
Ability to use filename in Foobar2000 mode?

### ISSUE THREAD

**Issue by Launchy21** [dlrudie/Snip#274]
I am using Foobar2000 as my music player, and Snip is picking up some odd tags in the MP3s, so it would be awesome if Snip could simple grab the filename and output that in the text file. Maybe even grab the album cover too?

**Comment by GenesisFR** [comment]
Filenames are inconsistent so that wouldn't be reliable.

**Comment by dlrudie** [comment]
Snip will default to use whatever is in the titlebar of foobar2000 if it can't detect the correct layout for formatting. So in a way it supports it. Just not separate file output.
