### ISSUE TITLE
Spotify is not currently running

### ISSUE THREAD

**Issue by Goldenphelix** [dlrudie/Snip#278]
As seen in the screenshot linked, spotify is definitely playing a song and running but when I hover over snip it says that spotify is not currently running?
I use snip for my streams on twitch and would love for this to be fixed.
Thank you.
https://gyazo.com/158eb55db97d1b008344d7f09d914816

**Comment by vinnyNC** [comment]
I get this and it works for a bit and quits working.

**Comment by Goldenphelix** [comment]
I decided to move over to https://smgmusicdisplay.com
Costs a small amount initially, but it does what I need.
