### ISSUE TITLE
Add Streamlabs Chatbot Support and Format Menue

### ISSUE THREAD

**Issue by LoaStaub** [dlrudie/Snip#279]
Hey guys, i just wanted to leave you an impression.
I am using Snip for long now and I am verry happy with it.
I would like to tell you my ideas, that you might want to use.

1.
I thought about a Format Setting, i don't like that the format ist title - artist.
Yes i changed Artist Format to $$t and Trakc Format to $$a but maybe a little setting oportunity would be awesome.

2.
I thought about a support for the Streamlabs Chatbot. Always when people are requesting Spotify Songs, everything ist cool, but when they request youtube content, it doesn't appear due to lack of support for it. Maybe you think about this idea, maybe it is impossible, maybe you don't even want to do it.
I'm fine with it, i just wanted to share some thoughts.

Hope you are doing good :)

Have a nice day!

LoaStaub

**Comment by GenesisFR** [comment]
1. I've been thinking about doing it the same way [Snaz](https://github.com/JimmyAppelt/Snaz/wiki/Spotify) was doing it. Until now, I was waiting for @dlrudie to merge my pull requests before working on it but I guess I'll just do it on a separate branch.

2. For that I think you need to make a browser extension that communicates with your app, pretty sure this is beyond the scope of Snip for now (you can find other apps that can do it though).

**Comment by dlrudie** [comment]
Definitely been busy with 70 hour work weeks. Have not had a lot of time to review pull requests. It's on my list.

1) I have a separate build of Snip here that I've been working on for awhile that has a completely reformatted output format layout. There's a lot more control, customizability, and... in the code-side of it... easier to add extended features for formatting.

2) There is a browser pull request but I have not had time to really dig into it. There were some performance concerns with the pull request currently and I just have not had time to really research improvements to it.

I will eventually go through everything but my time has been limited.
