### ISSUE TITLE
Program not opening

### ISSUE THREAD

**Issue by Zamtron** [dlrudie/Snip#281]
After downloading the latest versoin (Snip-v6.9.5 as I am writing this), extracting it and executing the program, it appears in my task bar. Although  if I try hovering over it to set it to search for iTunes, it instantly disappears.

**Comment by Flare576** [comment]
Same Experience, Running Windows 10 and Snip v6.9.5 and happy to pull any logs you'd like (so long as you tell me where to find 'em).

It appears in the system tray (and under Background Processes in Task Manager as *Suspended*) briefly before crashing/closing.

**Comment by dlrudie** [comment]
Perhaps check in the Windows Event Viewer for details on the crash.
