### ISSUE TITLE
Hotkey error message.

### ISSUE THREAD

**Issue by ThoughtShift** [dlrudie/Snip#285]
Every time I launch Snip with Spotify I keep getting an error window that says:

 "This hotkey is already registered by another application and will be skipped: Alt, Control, M"

Any idea on how to troubleshoot this? It says no track playing when I play a track in Spotify. Each time a new song plays I get this error message.﻿ Thanks

**Comment by dlrudie** [comment]
Do you use any of Snip's hotkeys? You can right-click on Snip and choose to disable hotkeys. It shouldn't complain anymore after that.

**Comment by anneo17** [comment]
There is no option when you right-click the application to disable hotkeys???

**Comment by GenesisFR** [comment]
@anneo17 https://github.com/dlrudie/Snip/issues/309#issuecomment-407180030
