### ISSUE TITLE
6.9.5 (64-bit only)

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#288]
I wasn't aware of the update. Still running 6.9.1 with success.
Am I to understand that updating to 6.9.5 won't be possible for me since I am running on 32-bit Win10 ?
Upgrading my old desktop to 64-bit isn't really an option but I do love this application so what do I do?

Stay on 6.9.1 until I get a new desktop? :/

**Comment by Chrionz** [comment]
Yep, that will be your only option, however it begs the question; why are you running 32 bit in 2018...

**Comment by murko69** [comment]
Well the computer is from 2009 with just a few minor upgrades over the
years. Should work fine with 64-bit really, but I just never got around for
such an upgrade. Guessing I never will. I have a laptop that runs it though

Den sön 17 juni 2018 19:04Chrionz <notifications@github.com> skrev:

**Comment by dlrudie** [comment]
It doesn't have to be. There wasn't any particular reason why I changed it to 64-bit. I just figured it's extra overhead and I didn't think anyone was actually still using a 32-bit system. It will still compile just fine as 32-bit. Maybe I'll switch it back to AnyCPU.

**Comment by murko69** [comment]
Thanks for the info @dlrudie . Actually I do think there are a lot of oldtimers, non-gamers or just plain poor people still using 32-bit. I think I belong in all three categories :D 
I'm closing this one since I got answers!
