### ISSUE TITLE
Snip Not Extractable?

### ISSUE THREAD

**Issue by kittykatnightcore** [dlrudie/Snip#289]
Basically when downloading snip, it does not appear as an extractable file.  There is only one thing downloaded (not a folder or multiple things) and it is not snip.exe so I cant open it

**Comment by FoamShrimpay** [comment]
https://github.com/dlrudie/Snip/releases/tag/v6.9.5
use this version instead. I had the same problem.

**Comment by kittykatnightcore** [comment]
That seemed to work, thank you!
