### ISSUE TITLE
Continue while locked Windows

### ISSUE THREAD

**Issue by Radiofreak1041** [dlrudie/Snip#291]
Is Snip being able to operate while Windows is locked? I am using Snip on a server with Remote Desktop access. Whenever I close the connection, Snip doesn't register data anymore until I log back in.
I'm using Snip with Spotify.

**Comment by dlrudie** [comment]
I've had other people report this issue before. I'm guessing it has to do with something within Spotify making it non-detectable while Windows is locked. I'll have to do some research.

**Comment by dlrudie** [comment]
See #299
