### ISSUE TITLE
Editing *Track Not Playing* Msg

### ISSUE THREAD

**Issue by sblsubin** [dlrudie/Snip#292]
Hello, is there anyway to edit the *track not playing* msg?
While scrolling, it shows as *no track playingno track playing no...*, with no space after *playing*
https://gyazo.com/694fb6069f8b73c3f1ce790d79a191d9
Tried to look around to see if I could edit this, but couldn't seem to find out how.

**Comment by dlrudie** [comment]
You can edit the output format by right-clicking on Snip in the system tray and choosing Set Output Format. You can then add spaces if needed.

**Comment by GenesisFR** [comment]
You have to download the source code, change the NoTrackPlaying string in one of the Resources/Strings.txt files and recompile the project.

Or you can just enable "Empty File If No Track Playing" in Snip settings so that nothing is displayed in OBS.

**Comment by neverbackdown81** [comment]
i need it to display in obs so my viewers can see what iim plying listeninig to i messaged u davvid on twitch check your wispers

**Comment by sblsubin** [comment]
dlrudie, I didn't see any option for default no songs playing msg in set output format.
genesisFR, How do I recomile exactly?  Never done it before O_o;

**Comment by GenesisFR** [comment]
You can't customize localization strings in Snip externally at the moment. I don't understand why it's bothering you though, do you really want to show "No track playing " in OBS?

To recompile Snip, you need Visual Studio 2017 to open the project, then create an application on the Spotify developer website and use your client ID and secret in a file called `ApplicationKeys.cs`, it's been explained somewhere in one of the issues so you'll have to search.
