### ISSUE TITLE
Itunes album wont show

### ISSUE THREAD

**Issue by rawrstreams** [dlrudie/Snip#293]
It will only show the Title and the Artist, it wont show the album

![untitled-1](https://user-images.githubusercontent.com/40874722/42353865-e0b40b44-8088-11e8-810d-8841d81cd186.jpg)
![untitled-2](https://user-images.githubusercontent.com/40874722/42353866-e0c3767e-8088-11e8-832f-3a76f134f4f3.jpg)
![untitled-4](https://user-images.githubusercontent.com/40874722/42354090-08d7298e-808a-11e8-8219-cc996ff37847.jpg)
![untitled-3](https://user-images.githubusercontent.com/40874722/42353867-e0d0538a-8088-11e8-985a-115f831f7361.jpg)

**Comment by MackKnife** [comment]
this is an know error  when u are using Apple Music Subscribtion .  

i got the same problem  Music  which i own  in my libary will show the cover  but music which  is from Apple Music  wont show the covers

**Comment by rawrstreams** [comment]
It's music from my computer

**Comment by MackKnife** [comment]
I guess u did u save the cover file in snip  ?! 

Which version of itunes are u using ?

**Comment by rawrstreams** [comment]
Yes i saved the cover file to snip

I have the current version of Itunes

**Comment by dlrudie** [comment]
I'll have to mess with this. I have music locally as well as a subscription.
