### ISSUE TITLE
Snip on ubuntu?

### ISSUE THREAD

**Issue by ghost** [dlrudie/Snip#295]
How to? no configure, no make O_O

**Comment by GenesisFR** [comment]
It's made in C# dude, it only compiles on Windows. Maybe you could get it work with Visual Studio Code, otherwise just use Wine to run it.

**Comment by markspolakovs** [comment]
Yup, Snip uses WinForms, so even porting it to .NET Core would be pretty much impossible.

**Comment by dlrudie** [comment]
Most of the code is portable. Mono exists. And the WinForms integration is minimal as it's mostly a system tray menu. Obviously locating processes and finding window handles will be different. I'm not going to bother porting it but it wouldn't be too bad. But then again it wouldn't be too difficult to create a Linux-specific program from scratch.
