### ISSUE TITLE
Snip not working w/ spotify after editing host list

### ISSUE THREAD

**Issue by thehossidiot** [dlrudie/Snip#297]
So I did this work around with spotify and adding to my host list so I could disable ads and now snip doesn't work with spotify for OBS.  Any idea on how I can get it to work again?

**Comment by GenesisFR** [comment]
What entries did you add to your host?

**Comment by dlrudie** [comment]
See #299

**Comment by brianj64** [comment]
I just wonder how Discord is still able to detect track information without an update?

**Comment by dlrudie** [comment]
Discord is pretty much a web browser. They use the web API and other stuff.
