### ISSUE TITLE
Snip doesnt save track history

### ISSUE THREAD

**Issue by drwankingstein** [dlrudie/Snip#298]
ive tried both VLC and WINAMP, and it doesnt save track history at all, doesnt even make a file

**Comment by MeikelLP** [comment]
Just a stupid question but:
Did you checked the option that snip shall save the history?

**Comment by MeikelLP** [comment]
Did you read [this](https://github.com/dlrudie/Snip#supported-features-for-players) ? VLC and WINAMP both do not support track history at this point.

Is your issue a bug or a feature request ❓

**Comment by drwankingstein** [comment]
is it because it doesnt support output formating? i thought that was just for how it writes down the song details into the file? or am I missing something?

**Comment by MeikelLP** [comment]
It's just not implemented yet.
