### ISSUE TITLE
Snip "No Track Playing"

### ISSUE THREAD

**Issue by L3wis-97** [dlrudie/Snip#301]
So I opened snip and streamed yesterday and it was working fine but then today i go to do the same thing and now it says im not playing a track when I am.
I have tried:
Reinstalling snip
Reinstalling Spotify
Restarting PC
All threads i've found

Nothing seems to be working and its odd that it stopped working out of nowhere

**Comment by pswaab** [comment]
Please look here https://github.com/dlrudie/Snip/issues/300
You ar not the only one.
