### ISSUE TITLE
Not detecting spotify track

### ISSUE THREAD

**Issue by fracture93** [dlrudie/Snip#305]
Hello,

Recently reinstalled latest version of snip on W10, and tried both the windows store version and the non windows store version of spotify but no matter what it does not detect my playing track.  I have uninstalled and reinstalled both snip and spotify multiple times and made sure the webhelper is running every time.  I cannot seem to get it to detect my playing track, it worked completely fine before reinstall of W10 and I am not sure what else I can try as I googled all possible wordings i could think of to figure this issue out.

**Comment by dumbrellas** [comment]
Seems that a recent Spotify update has changed something with how Snip accesses the information.

**Comment by fracture93** [comment]
sorry, i will close this, issue #299  seems to be what i needed
