### ISSUE TITLE
No more autostart

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#317]
As title says. Autostart don't work anymore. 
I still have my shortcut in `{DRIVE}:\Users\{MYUSER}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` but nothing happens.

According to @MeikelLP in #315 this _"may be because of the admin rights requirement since 6.10."_  and that sounds legit, so I'm adding this issue :)

**Comment by Jademalo** [comment]
Also having this issue. Definitely started when admin rights were required.
I'm using the same location on Windows 10.

**Comment by MeikelLP** [comment]
Did you try `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` ?

**Comment by Jademalo** [comment]
That folder doesn't exist exactly, but there is Start-up. I'll try that later and get back to you.

**Comment by MeikelLP** [comment]
Else try running the program `shell:common startup` via **run.exe** (`WIN` + `R`)

**Comment by murko69** [comment]
What's the difference between shell:common startup and shell:startup?
The last one is where I had my Snip autostart from earlier.
I for one can't create a C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp (and that's where I end up with shell:common startup) - I'm getting an error asking me if I like to put in on the desktop instead.

I can put a copy of the .exe-file there but that don't seem right :)

**Comment by murko69** [comment]
All of this don't really matter atm anyway though since Snip isn't working at all using Spotify since a few months

**Comment by MeikelLP** [comment]
`shell:common shell` is the system-wide startup which applies to all users (called by the system).

You should put a link (`.lnk`) file there. Just google something like _add programms to startup_

**Comment by Jademalo** [comment]
Huh, it's been working fine with spotify for me

**Comment by murko69** [comment]
Some ppl (quite a few as it seems counting all the issues-threads) have big issues with Snip only showing "spotify isn't running" or similar message since a few versions back. 
Same issue with Spotify standalone-file and with the Windows Store-version (some ppl reported one or the other actually working though)
I'm one of the unlucky ones that's been missing out completely on Snip for a fem months time so I've been crossing my fingers for a long time for a fully working Snip

**Comment by Jademalo** [comment]
Ok, just to totally confirm - No matter which Start-up folder or method is used, it doesn't load on startup at all.
