### ISSUE TITLE
Snip not recognizing that spotify is running

### ISSUE THREAD

**Issue by r04dw4rri0r** [dlrudie/Snip#320]
Snip says spotify is not running when I have it open and playing a song. It was working fine a few days ago. I think there may have been a spotify update. I've tried running both programs as administrator and non-administrator and I'm still having issues.

**Comment by MeikelLP** [comment]
@r04dw4rri0r Dupliacte of #315?

**Comment by r04dw4rri0r** [comment]
I guess. It's been working fine for Spotify until two days ago. Other than that, it's been fine for two weeks.

**Comment by r04dw4rri0r** [comment]
It started working fine again. Not sure why.

**Comment by MeikelLP** [comment]
Next time it's not working again, try to include some meta data about you case (Spotify version, OS Version, Spotify from Store or Standalone?, ...)
