### ISSUE TITLE
Album not showing up - apologies if I'm being thick

### ISSUE THREAD

**Issue by mochiinvasion** [dlrudie/Snip#324]
Hiya

Not sure if I'm just being dumb, but my album isn't showing up in snip.txt. I use Google Music desktop player. 

Output format:
![image](https://user-images.githubusercontent.com/42628764/44500504-b22b3180-a680-11e8-9818-27ce0b33549a.png)

However, it only exports as [song] - [artist]. Messing with the artist format doesn't work, unless I'm doing it wrong. 
![image](https://user-images.githubusercontent.com/42628764/44500517-ccfda600-a680-11e8-8bd0-acc2f64aa231.png)

My apologies if it's just that there's an option I need to select or something very simple like that,

Thanks
Mochi

(pls ignore my emo pissbaby music choicess :P )

**Comment by MeikelLP** [comment]
Isn't there an extra file for the album?
