### ISSUE TITLE
when i use snip, it readds music to my playlist that im listening to

### ISSUE THREAD

**Issue by barna911** [dlrudie/Snip#325]
when i use snip, and i play music from my spotify playlist, it readds that song to my playlist, and its really annoying, cause its not in order anymore :( please help/fix

**Comment by MeikelLP** [comment]
I don't understand what your problem is. When does snip save a song to a spotify playlist??

**Comment by GenesisFR** [comment]
This isn't what Snip does, must be caused by something else or another program.
