### ISSUE TITLE
Spotify cant be read, but no error either.

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [dlrudie/Snip#327]
I just cant get Spotify to read.
the SNIP.txt is just empty and nothing happens, WinAMP does work.

WIN 10 Pro 64
No Plugins for Spotify, just fresh installed it again.
Stand Alone Version.
I were in the Spotify Options, i dont block cookies ETC, everythig set to public etc.

Any suggestions?

Thank You

**Comment by MeikelLP** [comment]
see #315

**Comment by JayTheLordOfTheFishes** [comment]
> see #315

does not work for me, this thread doe snot really help.

**Comment by MeikelLP** [comment]
I shall not help. It only shows you that this error is already being tracked there. No reason to open another issue.

**Comment by NAFKog** [comment]
Same Problem as Jay.
