### ISSUE TITLE
Snip won't save program and output settings

### ISSUE THREAD

**Issue by MohnJadden** [dlrudie/Snip#330]
I had set Snip to read from Winamp and output track/artist/etc. separately.  Upon machine shutdown, those settings don't save.  Is there a way to save the settings or configure an ini to have it do so?

**Comment by GenesisFR** [comment]
Snip saves its settings to the registry under the "HKEY_CURRENT_USER\Software\Snip\6" key. I don't know if settings are saved when shutting down the computer while Snip is running, but they should be saved when closing Snip manually.

If they still aren't saved when closing Snip, then you have a permission issue. Check that you have an admin account and your antivirus is not interfering with Snip.
