### ISSUE TITLE
VLC Player Song Name and Artist Connected

### ISSUE THREAD

**Issue by ItsMeTheMcb** [dlrudie/Snip#331]
I use VLC and I know that you can't use the output format option for it but is it possible to make the title and artist not run up on each other? currently I have a situation like this in my scrolling text, **MonodyTheFatRat -** but instead I would like something along the lines of **Monody   TheFatRat -** where there are 2-3 spaces between.

Edit: 

> You can use an outline with a size of 8 and an opacity of 0. It will add some spacing at the end of the text. -GenesisFR

>

**Comment by p455w0rd** [comment]
you can fix this within OBS using the "use custom texts extents" option
![](https://puu.sh/BrK3z/09134b9811.png)

**Comment by ItsMeTheMcb** [comment]
the issue with using custom text extents is that it doesn't fix songs with really long titles such as **"Dancin' to the Sound of a Broken Heart"** by **Galantis** unless I want to have it take up like half the screen and that leaves short song names like **"Delta"** by **C2C** with a huge space between the name and artist and looks really bad.

**Comment by ItsMeTheMcb** [comment]
I do have artist and track tags on all but maybe 1 or 2 songs, I even had to remove every . Individually Because it would destroy the title and artist in obs. But what it is doing is ripping the titl and artist so it says [artist] - [title] but when it scrolls there is no space after the title or before the artist so they run together,  le][artist] - [tit

**Comment by GenesisFR** [comment]
I don't have this problem here. Mind sharing the tags of the problematic song and showing your OBS text source and filter settings?

**Comment by ItsMeTheMcb** [comment]
https://imgur.com/a/9dtRGpy

The issue occurs with any song where the artist and title ends up being longer than the box being used so a song like **"Delta"** by **C2C** would fit with extra space but a long song title and/or artist ends up running right up on each other with no space. also, thank you for trying to help even if no solution is found.

**Comment by GenesisFR** [comment]
That is indeed something annoying, The problem is not really noticeable with my settings because I'm using an outline on my text sources, which mitigates the problem.

However, I found a workaround. You can use an outline with a size of 8 and an opacity of 0. It will add some spacing at the end of the text.

I know @dlrudie had started working on an overhaul of the output format window a while ago to make it more customizable and hopefully extending it to other media players. No clue when that will be done though (I'd be glad to take care of it as I'd like to make the formatting use optional tokens like Snaz).

**Comment by ItsMeTheMcb** [comment]
The big thing for me is that I want the text to be readable and not take up the whole screen for some of my really long songs so I have it scroll and that doesn’t seem like it would fix anything but I will try it out

**Comment by GenesisFR** [comment]
Try it and you'll see it doesn't make the text necessarily bigger.

**Comment by GenesisFR** [comment]
Any update?

**Comment by ItsMeTheMcb** [comment]
ah sorry about forgetting to reply but it did help when I tried again just now but instead I decided to change all of my .flac songs to .m4a and imported all 700 something songs into iTunes because then I could add the songs I really like to my phone but it did work surprisingly to me since i thought it would just change the border. thank you
