### ISSUE TITLE
Snip will not launch at Startup

### ISSUE THREAD

**Issue by Jademalo** [dlrudie/Snip#332]
I have a shortcut to Snip.exe in my Start menu Startup folder, however the program doesn't load on startup.
Older versions seemed to work fine, I'm not sure why this one doesn't.

**Comment by MeikelLP** [comment]
What version to use? Windows verson?

**Comment by MeikelLP** [comment]
related / duplicate of #317

**Comment by Jademalo** [comment]
Didn't see the dupe, I'll post in there. Ty!
