### ISSUE TITLE
Snip not reading spotify song 6.10

### ISSUE THREAD

**Issue by haloceman357** [dlrudie/Snip#335]
Im having an issue with snip not reading the song data from spotify again. Would it be possible for it to just get window data from spotify or something since when spotify plays a song the window in explorer shows the song and artist?

**Comment by nFin1ty** [comment]
Try restarting Spotify after starting Snip.

**Comment by madspooky** [comment]
I've also seen where if i have streamlabs OBS open first before Snip and Spotify it won't recognize it. It always works if I do the following:

* Open Snip
* Open Spotify
* Start OBS

**Comment by patrickgh3** [comment]
> 
> 
> I've also seen where if i have streamlabs OBS open first before Snip and Spotify it won't recognize it. It always works if I do the following:
> 
>     * Open Snip
> 
>     * Open Spotify
> 
>     * Start OBS

This worked for me. Thanks madspooky! (Snip v6.10.2, most recent version of Spotify as of right now)
