### ISSUE TITLE
it's possible to add a WebNowPlaying to Snip?

### ISSUE THREAD

**Issue by LinuxGamer** [dlrudie/Snip#336]
I want to get the now playing from my YouTube Music electron app :/
![image](https://user-images.githubusercontent.com/17398632/46922118-d3eaca00-cfda-11e8-93c5-064467ff6d96.png)

**Comment by LinuxGamer** [comment]
add a snip to discord rich presence is a good thing to add to :)

**Comment by GenesisFR** [comment]
See #263
