### ISSUE TITLE
Includes "[Foobar2000]" in display

### ISSUE THREAD

**Issue by thekubliest** [dlrudie/Snip#337]
Hello,

I used to use Winamp with Snip since it was simple, but I ended up having too many hotkeys conflict with it that were unable to be disabled. I tried Spotify, but it just has so many issues in general. I now am trying to use Foobar2000.

I set the window title as suggested in the ReadMe (`%title% – %artist%`) but when it's displayed in OBS it shows "EXAMPLE ARTIST [foobar2000]" EXAMPLE SONG [EXAMPLE ALBUM]

No matter what I change I can't remove the "[foobar2000]" from after the artist. Has anyone else run into this? How do I remove it? (I'm using v6.10.2.)

Thanks for your help!

**Comment by skid9000** [comment]
Same problem here...

**Comment by LillieSatou** [comment]
You don't need a PR for this, as this is not a Snip issue, but a Foobar one.

in foobar2000, add `$repeat($char(32),999)` to the END of your Window title (in settings>display>Default UI.)

**Comment by thazdomato** [comment]
> You don't need a PR for this, as this is not a Snip issue, but a Foobar one.
> 
> in foobar2000, add `$repeat($char(32),999)` to the END of your Window title from within Foobar2000 (in settings>display>Default UI.)
> 
> this will work with the latest version of foobar2000 (currently 1.4.5 at time of update)

still working in 2025, thanks a lot!!
