### ISSUE TITLE
Errors trying to run

### ISSUE THREAD

**Issue by Raeanana** [dlrudie/Snip#339]
When I try opening the program to register it to Spotify (per a tutorial I read) it gives me errors saying "This hotkey is already registered by another application and will be skipped: [hotkey]".

This pops up several times and that's all that happens when trying to run the program. There is nothing in the .txt file for me to use in SLOBS.

Is there an official tutorial for using this? [This](https://obsproject.com/forum/threads/now-playing-music-for-spotify-itunes-winamp-on-stream.925/) is what I tried. But can't get to step 3. I cannot "run" it.

**Comment by GenesisFR** [comment]
Duplicate of #309.
