### ISSUE TITLE
No album titles

### ISSUE THREAD

**Issue by DevilDriver572** [dlrudie/Snip#34]
I'm using the latest iTunes (12.1.2.27) and Snip (4.60)

While I can get the track and artist to show up when playing, I can't get the album to show. Thanks for any help

**Comment by liamreed** [comment]
same issue

**Comment by dlrudie** [comment]
I'll look into this once I have Spotify working again.

**Comment by dlrudie** [comment]
Tested with iTunes 12.1.2.27 and the album title is correctly saved to Snip_Album.txt.  It also displays in Snip.txt and the system tray if you add $l to one of the fields.

**Comment by DevilDriver572** [comment]
Yes it shows and does save correctly to the Snip_Album.txt HOWEVER it doesn't save to the Snip.txt file

**Comment by DevilDriver572** [comment]
And the problem still persists

**Comment by dlrudie** [comment]
It will not save to Snip.txt by design by default.  You can, however, right click on the system tray icon, choose "Set Output Format" and add $l to any of the other lines or modify it how you want and it will save it to Snip.txt from there.

**Comment by DevilDriver572** [comment]
It's already there as it should be. It's not saving to Snip.txt

**Comment by DevilDriver572** [comment]
Wait, just worked after adding to the Song name line. Thanks

**Comment by dlrudie** [comment]
What I mean is that you could change it around.

Make the separator line say "from" and change the artist line to, for example, "$l by $a".

This will make the output in Snip.txt look like:
"Terrible Lie" from Pretty Hate Machine by Nine Inch Nails

**Comment by dlrudie** [comment]
I may eventually add album output to Snip.txt with an option you can toggle, however it was only meant to contain a simple string and not be cluttered.
