### ISSUE TITLE
Error With itunes and snip

### ISSUE THREAD

**Issue by MackKnife** [dlrudie/Snip#341]
Hey,  for me itunes and snip isnt working  since if updated to both newest version 
![error](https://user-images.githubusercontent.com/32893086/47706364-4e495a00-dc29-11e8-977e-09efc6412482.png)

This is a screenshot  where i have itunes open  playing a titel  and  snip wont catch any track data nor cover and brings up this error  but even after i close itunes and click itunes on snip it opens up and   empty file  and after a while  same error message again ?

**Comment by MackKnife** [comment]
i thin k this happens when u have 2 apps which using the connection to itunes  like i have  lastfm  and snip   only one can get  the data from itunes.   therefore snip brings up this error

**Comment by MiraiSubject** [comment]
Yup am able to reproduce this as well. 

Having Rainmeter (which has a skin active that hooks into iTunes' scripting interface) open causes Snip to fail to connect and also makes Rainmeter unstable in the process. Closing Rainmeter and running Snip properly gives me the now playing data
