### ISSUE TITLE
Snip makes the characters "]" and "}" unavailable

### ISSUE THREAD

**Issue by Fakstate** [dlrudie/Snip#342]
I'm on Windows 10, running the last build. I'm on an Azerty keyboard.
![image](https://user-images.githubusercontent.com/18249614/48114209-73a81a80-e25e-11e8-9892-6311e74c1218.png)

**Comment by Amp0** [comment]
Same issue here for me, I'm also on an azerty keyboard.

**Comment by dlrudie** [comment]
Eventually in the future I'll add the ability to set your own hotkeys.
