### ISSUE TITLE
How do I change the language of Snip?

### ISSUE THREAD

**Issue by ayygurl** [dlrudie/Snip#343]
Thanks!

**Comment by ayygurl** [comment]
Nevermind, I just deleted the french ressources file and it's now in english just like I wanted it to be!

Thank you for reading.

**Comment by GenesisFR** [comment]
Besides renaming resource files, I don't see any way of changing the language of Snip only. I guess you'd have to change the language of your whole operating system.

**Comment by dlrudie** [comment]
Snip just uses the native language of the operating system. If a resource file exists for the current language set on the computer it will use it by default. If you'd like to lock it to English then you can do what you mentioned and delete the other language file.
