### ISSUE TITLE
Snip "This hoktey is already Registered by another Application and Will be Skipped" Hotkey issue

### ISSUE THREAD

**Issue by TheZergBerg** [dlrudie/Snip#344]
When Skip starts it gives me this message
![forumhelp](https://user-images.githubusercontent.com/39413917/48365611-3da0d700-e660-11e8-9572-3af3343edbc4.png), and after looking through content I found that you have to right click the Icon to disable hotkeys, but when I right click the icon, I get this: 
![forumhelp2](https://user-images.githubusercontent.com/39413917/48365696-7ccf2800-e660-11e8-9369-607df819ee4c.png). Is there some kind of icon I'm missing to get this: ![forumhelp3](https://user-images.githubusercontent.com/3614449/43099371-fd482abe-8e8f-11e8-93d5-f505b9879d06.png)?

**Comment by GenesisFR** [comment]
The Snip icon in your taskbar.

**Comment by TheZergBerg** [comment]
I'm sorry, but when I right click it, this happens 
![forumhelp3](https://user-images.githubusercontent.com/39413917/48388536-8c755d80-e6ae-11e8-8a34-ead41222ae5c.png), is there something I misread or am Missing?

**Comment by GenesisFR** [comment]
This area.

https://www.howtogeek.com/wp-content/uploads/2015/08/x00_lead_image_email_notification.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.qGvMu2Vv3i.png
