### ISSUE TITLE
capitalized text with Spotify

### ISSUE THREAD

**Issue by dynamizer** [dlrudie/Snip#345]
Hello,

How can i have my snip.txt content in capitalized text ?

Have a good day

**Comment by MeikelLP** [comment]
Can't you just capitalize it with your recording tool like OBS?

**Comment by GenesisFR** [comment]
You can't do that in OBS Studio or SLOBS, don't know about XSplit.

Looks like you'd need to uppercase the parameters to this function here: https://github.com/dlrudie/Snip/blob/master/Snip/Players/Spotify.cs#L215

**Comment by dlrudie** [comment]
https://github.com/dlrudie/Snip/releases/tag/v6.5.0

There’s actually some hidden variables built in to snip already for this.

**Comment by GenesisFR** [comment]
I just tried them, works great! You have to put them in the "Set Output Format" window.
