### ISSUE TITLE
Snip not generating the app, neither the text file?

### ISSUE THREAD

**Issue by VanishBlox** [dlrudie/Snip#347]
Today I wanted to stream something, I opened snip because I do that always and then opened Spotify, but it didn't load the name of the song into OBS so I thought it was OBS. I removed it from OBS and then I tried adding it but the text file still was empty even though I was playing a song. I tried deleting the Snip-master folder and then downloading it again but now it doesn't show the APP either the text file? all I can see are files that I can't read with my pc. Help...

**Comment by jaynelayne** [comment]
I am having the same issue. I downloaded today to try out and there is no .exe file and nothing in my system tray.

**Comment by GenesisFR** [comment]
Always download Snip-vX.XX.X.zip from [releases](https://github.com/dlrudie/Snip/releases) otherwise you get the source code. If there's still no EXE after extracting it, blame your antivirus.

**Comment by VanishBlox** [comment]
FINALY! it worked, I just need to download the orignal release, I was always cloning the code but now it works! thank you @GenesisFR
