### ISSUE TITLE
Resize max length of artist text

### ISSUE THREAD

**Issue by Badatsum** [dlrudie/Snip#348]
Hello is this possible to limit the number of characters for the artist box? Because some music takes more than half of my screen and if I cut directly on OBS the following no longer see or almost. Thanks for help !

**Comment by GenesisFR** [comment]
Most likely won't happen for a while. You can use a scroll filter on your text source in OBS and limit the width there.

**Comment by dlrudie** [comment]
I like this feature request but I don't see myself adding it. You can use the scrolling ability in OBS like mentioned.
