### ISSUE TITLE
It means another program previously registered a global hotkey (aka keyboard shortcut) that Snip also wants to use. There's no reason why it'd prevent Snip from working.

### ISSUE THREAD

**Issue by norman250** [dlrudie/Snip#349]

**Comment by Ajax112189** [comment]
the app wont even install for me due to this keyboard shortcut error. saying my hotkeys are being used in another application although i have no other apps running

**Comment by lf0990** [comment]
same here and im running windows 8 on my pc so unfortunately no with run command. Any insight into this from anyone?

**Comment by dlrudie** [comment]
A huge portion of the code will be changing soon. I should have a new release out in the next week or two.
