### ISSUE TITLE
Setting output format on VLC not working

### ISSUE THREAD

**Issue by Ensmi** [dlrudie/Snip#353]
I'm using snip with OBS as a side scrolling 'now playing' element however none of the Output Format settings are working
e.g. song name is "Aerocity - Love Lost"
No matter what put in the fields it only scrolls as 
"Aerocity - Love LostAerocity - Love LostAerocity - Love Lost"
Obviously this isn't neat so I wanted to put spaces or a symbol in between the Artist name and Song name but no dice

**Comment by GenesisFR** [comment]
![image](https://user-images.githubusercontent.com/3614449/54047120-3324c300-41a4-11e9-9b75-bac299c96213.png)

**Comment by Ensmi** [comment]
I did read that but I didn't think it was talking about the output format, my bad cheers

**Comment by GenesisFR** [comment]
It is, there's no reliable way to know the artist and track for local files since they won't necessarily have tags.

**Comment by Ensmi** [comment]
Right, I've just opted to rename all my local files to accommodate for the output formatting not working with VLC
My issue was that I wanted to have music play on stream but I didn't want to hear it because I find it difficult to play a game with music however there would be too much silence on stream to be comfortable.
Spotify and Itunes don't allow to have a different output device as far as I could find so VLC and Winamp were the way to go
(Using a virtual cable btw)

**Comment by GenesisFR** [comment]
Don't know if this can help:

https://superuser.com/a/1374503
https://youtu.be/kekG3HBDNsM

**Comment by Ensmi** [comment]
All good, I've already put in all the work to get VLC working the way I wanted, but thanks for going out of your way to help, really appreciate it :)

**Comment by dlrudie** [comment]
VLC support is being dropped.
