### ISSUE TITLE
16.0.2 | No text file, but song name is there when hovering over the icon?

### ISSUE THREAD

**Issue by maxcalder0n** [dlrudie/Snip#356]
I extracted the Snip file to my desktop, ran the program, started up my Spotify, and it seemed to have worked! When I hovered over the icon on my taskbar, the song name showed up, but when I went to check the Snip.txt file, it wasn't in the extracted file. I attempted making one myself to see if it would work, but no dice. Any advice?

**Comment by GenesisFR** [comment]
The TXT file is automatically created by Snip. I'd say it's a permission issue so move Snip to another location like `D:/`.

**Comment by murko69** [comment]
I still don't get how Snip seems to work with Spotify for some ppl, when it's completely dead for so many others.
Mine has been totally dead for 9 months now.

**Comment by tocram1** [comment]
Same for me @murko69, completely dead, the Spotify setting doesn't even show the song's name when hovering the taskbar icon... With Foobar2000, the full name + name file + [Foorbar2000] is saved in Snip.txt, but the metadata aren't saved separately in the different files (yes, I checked the option for that)... Very odd.

**Comment by dlrudie** [comment]
A huge portion of the code will be changing soon. I should have a new release out in the next week or two.
