### ISSUE TITLE
Snip not detecting VLC

### ISSUE THREAD

**Issue by Sel1516** [dlrudie/Snip#357]
As the title says. I've tried starting Snip and then VLC, and the other way around as well. I've also tried what the note for VLC says, the thing with pressing stop and Snip would detect VLC. But it did nothing. I have a track playing and Snip just doesn't detect it at all. Well maybe it detects VLC, but not any tracks that I'm playing. I've used both Snip and VLC together a few days ago or less and they worked perfectly together with no issues at all. I even started both of them up in the same order that I always do. This is the first time I'm having an issue like this with them.

**Comment by dlrudie** [comment]
VLC support is being dropped.
