### ISSUE TITLE
"Empty File If No Track Playing" function not working

### ISSUE THREAD

**Issue by jphilli22** [dlrudie/Snip#358]
Until recently, the text file and album artwork would empty when I paused Spotify as normal. However, even with the above option checked, pausing playback no longer empties them. So track titles and album artwork remain on screen even when nothing is playing. 

No update to Spotify lately, but this did start occurring after I installed some major Windows 10 updates. May have possibly broken something?

**Comment by M1st3rJ4ck** [comment]
I can't say for certainty that what you suggest is the issue or not. I've had Premium for almost a year and the issue just started occurring. And I haven't noticed Spotify performing any updates anytime recently. It may very well have been a silent update, in which case, fixing it could be as simple as updating the condition you mentioned.

**Comment by GenesisFR** [comment]
Seems like the window title changed according to this commit: https://github.com/Inzaniity/Songify/commit/acbfa769ee00ca744eeae384eec856647b3edd2b#diff-7989b3780fca0a32003795c4a31bcbebL225

**Comment by MalicT** [comment]
Came in to post this same thing that it is currently not clearing the title when the music is stopped or paused for Spotify

**Comment by GenesisFR** [comment]
> How do we get a working version of this with this fix? Releases show last one in 2018
Just wait until #360 gets merged.

**Comment by jphilli22** [comment]
> > How do we get a working version of this with this fix? Releases show last one in 2018
> 
> Just wait until #360 gets merged.

Pardon me, GenesisFR, could you elaborate on that? I'm unfamiliar with how I need to update to the fixed version. I tried creating a build of the source code myself with VS, but that encountered its own issues. Do I need to wait until dlrudie puts up an official update, or is there some other way I can download an updated full build?

**Comment by GenesisFR** [comment]
Simple answer: wait for an official update.

Complicated answer: clone the source code for Snip, create a Spotify dev account to get an API key, put it in `Snip\ApplicationKeys.cs` and recompile the project.

Here's a template for ApplicationKeys.cs:

```
using System;
using System.Text;

namespace Winter
{
    public static class ApplicationKeys
    {
        public static string clientid = "";
        public static string clientsecret = "";
        public static string Spotify = Convert.ToBase64String(Encoding.UTF8.GetBytes(string.Format("{0}:{1}", clientid, clientsecret)));
    }
}
```

**Comment by jphilli22** [comment]
Well, when the last public release was almost a year ago, it makes me question when I will actually be able to use that short answer. So it seems like the complicated answer is what I'm looking for.

**Comment by GenesisFR** [comment]
You'll have to comment some of the iTunes code if you don't have iTunes installed or it won't compile.

**Comment by MalicT** [comment]
Since Snaz dropped support for reading Spotify music tracks, a lot of streamers have turned to Snip for reading music tracks being played and display to viewers/allow our bots to read the txt file to put into chat.  It is the only program that is on the OBS studio plugins that still is supported.

Not everyone here knows what is need to compile and put together a new release version.  Right now the last song is still displayed on OBS when the music stops because Snip does not clear the txt file.  The last release was 10 months ago  How often are we expecting to get an updated release?

**Comment by jphilli22** [comment]
That's been my concern as well. I've spent a lot of time trying to find third-party software that performed this function, but this seems to be the only one that works anymore. Prior to the last update, the developer seemed to provide frequent updates, several within a few weeks of each other. I'm concerned that dlrudie has abandoned the project.

**Comment by GenesisFR** [comment]
Some decent alternatives:

https://obsproject.com/forum/threads/musicbuddy-supports-spotify-youtube-and-more.82228/
https://obsproject.com/forum/threads/obscurrentsong-spotify.83388/

Haven't tested on latest Spotify as I'm using a downgraded version that never updates.
