### ISSUE TITLE
Artwork not work

### ISSUE THREAD

**Issue by eDDx** [dlrudie/Snip#362]
Thanks a lot for this app but I do not why the artwork is always blank

![art](https://user-images.githubusercontent.com/115531/59484899-b3149600-8e41-11e9-99f1-f859d31180ed.jpg)

**Comment by GenesisFR** [comment]
![image](https://user-images.githubusercontent.com/3614449/59532116-ce20ed80-8eb5-11e9-94fc-d988f34dbf8b.png)

**Comment by eDDx** [comment]
Happens on Spotify  too :(

**Comment by GenesisFR** [comment]
Make sure this is selected.

![image](https://user-images.githubusercontent.com/3614449/59533320-1db4e880-8eb9-11e9-8420-5f078f108fad.png)

**Comment by dlrudie** [comment]
A huge portion of the code will be changing soon. I should have a new release out in the next week or two.
(VLC support will be dropping)
