### ISSUE TITLE
Doesn't Seem To Work With Older Versions

### ISSUE THREAD

**Issue by sirj0k3r** [dlrudie/Snip#364]
I'm using 1.0.73.345.g6c9971ef version and Snip doesn't seem to pull any info from the song.
Same Snip version works with later Soptify versions.
Also tried download the Snip release before and after the Spotify version I'm using and no luck.

**Comment by sirj0k3r** [comment]
Changed to 1.1.8.439.g8502297d and the issue seems to be gone.
Might be major versions specific.

**Comment by GenesisFR** [comment]
Latest Snip works fine on 1.0.85.259.g4ab01679 for me.
