### ISSUE TITLE
Not pulling info from spotify

### ISSUE THREAD

**Issue by jdev21** [dlrudie/Snip#370]
I'm running 7.0.1 but snip will either not update with the current song at all (switched to spotify is what it says) or it will take over a minute into the song before it finally reads it.

**Comment by dlrudie** [comment]
Yes. This will happen for a bit. Not a bug. This is due to Snip being rate limited on API calls. The initial release saw too many calls. 7.0.1 slows it down and adds retry. Once all users upgrade to 7.0.1 there should be a good increase in success of API calls.

**Comment by jdev21** [comment]
Hate to say I ended up downgrading to get it working properly. It may be hard to get enough people to upgrade and make it usable if it's not working otherwise.

**Comment by dlrudie** [comment]
I may just have to disable the usage of 7.0.0 then. Using 7.0.0 is only going to compound the problem. You’re still going to hit the rate limit. The only problem is that it’s going to ignore the retry timer and potentially get Snip blocked by Spotify.

I have another solution in the works but I’m out of town and won’t be flying back until Sunday. So it may not be until next weekend that I have an update out.

**Comment by dlrudie** [comment]
v7.0.2 incoming
