### ISSUE TITLE
Request: Spotify Podcast Info

### ISSUE THREAD

**Issue by GigglingGeekette** [dlrudie/Snip#372]
Is it theoretically possible for Snip to pull the info from podcasts in Spotify?

Such as episode name in "track" and podcast name in "album" or "artist"? Having that plus the podcast logo as the album art would be incredibly helpful 😄 

Cheers!

**Comment by MeikelLP** [comment]
If I read the docs correctly there shouldn't be any difference between podcasts and normal songs: https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-the-users-currently-playing-track

@dlrudie Did you use this API call or another one?

**Comment by dlrudie** [comment]
That is the API I use. However the JSON reply may be different for podcasts.

Can you link me to which podcast you use and I’ll check it out?

Thanks.

**Comment by dlrudie** [comment]
Alright there's absolutely nothing I can do with podcasts.

The JSON Spotify returns contains absolutely no info on the podcast.

The only thing I can implement is that if you play a podcast that Snip won't crash anymore.
