### ISSUE TITLE
ERR_CONNECTION_REFUSED on authorizing with facebook account

### ISSUE THREAD

**Issue by chrion02** [dlrudie/Snip#373]
Trying snip for the first time, after opening and pressing the "login with facebook"-button doing the authorization, i immediately get redirected to the chrome browser error screen with "ERR_CONNECTION_REFUSED"

**Comment by dlrudie** [comment]
Upgrade to 7.0.2

**Comment by MeikelLP** [comment]
Maybe a firewall issue?
