### ISSUE TITLE
Unable to access settings

### ISSUE THREAD

**Issue by SwippedTritch** [dlrudie/Snip#376]
Snip is running in the taskbar but I am unable to access any settings to update parameters or change source.

**Comment by murko69** [comment]
Unlike many other apps in the taskbar this __only__ uses right click to open menu. Doesn't that work either?

**Comment by dlrudie** [comment]
This is going to be due to the local web server hanging and blocking everything. I’ll look into that this coming weekend time permitting.

**Comment by dlrudie** [comment]
Fixed in 6f287eb318c4a3bdc193e49097161578998b26e9
