### ISSUE TITLE
Text File Missing After Last Update

### ISSUE THREAD

**Issue by MisakiCherry** [dlrudie/Snip#377]
When I open Snip it says that it is authorized by Spotify but the text file is not created and it disappears from the Task Bar when i hover over it.

**Comment by DarkDrinker** [comment]
Have the same issue after the new update.

**Comment by DarkDrinker** [comment]
I found a solution to this. apparently important that you extracted the zip and run Snip from the extracted folder. Now it works like a dream again. Hope it helps.

**Comment by MisakiCherry** [comment]
Still doesn't work the text file doesn't appear.
