### ISSUE TITLE
Minimized to tray doesn't seem to work

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#378]
In 7.0.2:

> Changed timer from 5 seconds back to 1 second. However **Snip now uses the titlebar of Spotify to determine when tracks change and will only fetch new data when the titlebar changes**. This ultimately cuts down on API calls significantly

The bold part I guess is the reason why it doesn't seem to work when I minimize Spotify to tray using the x-button?
Just using the Minimize-button "_" on Spotify works fine.
If there's no workaround for this I wil just need to remember to not use the "x"-button on Spotify

**Comment by dlrudie** [comment]
That’s correct. I discovered this too after releasing 7.0.2. Spotify used to still provide a title bar even when minimized to tray. It may still. I just have to look into it.
