### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by wflieller** [dlrudie/Snip#379]
Any idea if you will be adding mac version of snip? Currently nothing exists for us :(

**Comment by dlrudie** [comment]
No plans but it could be easily done with AppleScript.

**Comment by dlrudie** [comment]
I'm no AppleScript expert but here's a quick script I threw together. It will output to Snip.txt on your desktop of the currently playing track.

```
use AppleScript version "2.7"
use scripting additions

tell application "Spotify"
	set trackID to ""
	set snipFile to (((path to desktop folder) as string) & "Snip.txt")
	repeat
		set currentTrack to the current track
		if player state is playing then
			if id of currentTrack is trackID then
			else
				set snipText to "\"" & name of currentTrack & "\" — " & artist of currentTrack
				my writeTextToFile(snipText, snipFile)
				set trackID to id of currentTrack
			end if
		else
			set trackID to ""
			my writeTextToFile("", snipFile)
		end if
	end repeat
end tell

on writeTextToFile(theText, theFile)
	try
		set theFile to theFile as string
		set theOpenedFile to open for access file theFile with write permission
		set eof of theOpenedFile to 0
		write theText to theOpenedFile starting at eof
		close access theOpenedFile
		return true
	on error
		try
			close access file theFile
		end try
		return false
	end try
end writeTextToFile
```

**Comment by b7anka** [comment]
Hi @dlrudie thanks it works but the text file is not recognized by OBS and the reason is because OBS only allow files encoded in utf-8 or utf-16 so here is the updated code that will work with obs:

<pre>
use AppleScript version "2.7"
use scripting additions

tell application "Spotify"
	set trackID to ""
	set snipFile to (((path to desktop folder) as string) & "Snip.txt")
	repeat
		set currentTrack to the current track
		if player state is playing then
			if id of currentTrack is trackID then
			else
				set snipText to name of currentTrack & " - " & artist of currentTrack
				my writeTextToFile(snipText, snipFile)
				set trackID to id of currentTrack
			end if
		else
			set trackID to ""
			my writeTextToFile("", snipFile)
		end if
	end repeat
end tell

on writeTextToFile(theText, theFile)
	try
		set theFile to theFile as string
		set theOpenedFile to open for access file theFile with write permission
		set eof of theOpenedFile to 0
		write theText to theOpenedFile as «class utf8» starting at eof
		close access theOpenedFile
		return true
	on error
		try
			close access file theFile
		end try
		return false
	end try
end writeTextToFile
</pre>
