### ISSUE TITLE
right click

### ISSUE THREAD

**Issue by vertex101** [dlrudie/Snip#381]
I am using Win10 and with the latest version when i try to right click the icon in my tray it doesn't bring up no menu to change from spotify to itunes

**Comment by tombets2424** [comment]
Yep, I had that. It forces you to log in to Spotify otherwise you can't right click to bring up snip's functions.

**Comment by murko69** [comment]
I think #369 is the same and it's on the bug list

**Comment by vertex101** [comment]
Ah okay I will give that a try and see if it will work for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlrudie** [comment]
Duplicate of #369 basically. It's still on my list.
