### ISSUE TITLE
Playing on a Remote Device

### ISSUE THREAD

**Issue by autonetmobile** [dlrudie/Snip#382]
With 7.0.2, when I play on a remote device, Snip now says "No Track Playing" and Snip.txt file is empty.   If I play on the local device it works.

**Comment by dlrudie** [comment]
This is related to Spotify being minimized to the system tray likely.

**Comment by autonetmobile** [comment]
No.  That's not it.   It's something to do with Playing the audio on a Remote Device.    When I play on the local device it works fine.

**Comment by autonetmobile** [comment]
Here's a clue.  When I play on the local device, the Window name of Spotify shows the artist/song,   but when I play on a remote device the Window name is just "Spotify Premium".   Even though the artist/name does show up in the Spotify App itself.

**Comment by autonetmobile** [comment]
FYI.  When I use the Spotify player in the browser version I don't have this problem.  I wrote an ugly script to grab the title of the browser and remove the Google Chrome nonsense and it seems to work.  Not very elegant,  but it's working.
