### ISSUE TITLE
How to update account authentication

### ISSUE THREAD

**Issue by RazorsharpNo1** [dlrudie/Snip#387]
Hi guys,

when i first started snip V7, i used my second spotify account for the authentication.
However, i want to use my main account, and i don't know how to change the account information. 

I tried to delete/reinstall everything but it's automatically authorizing my old acc. 

Can you help me?

**Comment by murko69** [comment]
Hi there. Should be simple
Go to https://www.spotify.com/se/account/apps/ (on your second account) and delete Snip - then try again with your main account

**Comment by dlrudie** [comment]
Thanks, @murko69 .
