### ISSUE TITLE
Album info does not appear in snip.txt file

### ISSUE THREAD

**Issue by calvin-powers** [dlrudie/Snip#388]
First of all, mega thanks for thie very helpful tool. Just installed it for the first time. 

I'm using version 7.0.2 on Windows 10.  I have it connected to my locally installed iTunes. 

I'm using the default formatting. 

The snip.txt file does not update with the album info. Just song title and artist. 

If I check the save information separately box, the separate files are created and the Snip_album file has the album information and is even formatted correctly.  

Total newbie here, so forgive me if I am missing something obvious. But I cannot get the album info to display in the single snip text file.

**Comment by murko69** [comment]
You are correct! :)

**Comment by calvin-powers** [comment]
OK well, I can pull the separate files into OBS. The way I like to present stuff is 

"song title" from album-name by artist. 

But I think I can construct that by pulling in the individual files. 

Maybe the readme could be updated to document that album is not included in the single file version?

**Comment by dlrudie** [comment]
There are hidden variables you can use to force the album title into the standard layout. I never added them to the readme file as I wasn't ever sure if I was going to keep them or rename them. However, they've been around long enough that I may as well add them to the readme.
