### ISSUE TITLE
Snip won't work well with OBS Studio + obs.live

### ISSUE THREAD

**Issue by nokuga** [dlrudie/Snip#389]
I was using Snip in SLOBS, worked fine until 7.0. Then, some bugs on track naming, but still working.

Migrated to OBSlive (streamelements addon to OBS Studio) and couldn't make Snip work. 

At first, it wouldn't work at all. Install text source, it goes vertical. If I turn it vertical in options, it goes horizontal.

Today, I that error stopped. The song text finally appears, but it doesn't scroll as it did before. It just stay still, changes when song changes, but even managing it is weird.

**Comment by dlrudie** [comment]
This is not a problem with Snip but with the other software you're using. Snip just saves text to a file. That's all it does.
