### ISSUE TITLE
No VLC support? 

### ISSUE THREAD

**Issue by NANOHORIZON** [dlrudie/Snip#393]
I see no option for VLC?

**Comment by MalicT** [comment]
One of the last updates removed support for everything except iTunes and Spotify

**Comment by Kartchampion** [comment]
If you want to use VLC you can still go to https://github.com/dlrudie/Snip/releases and download the last version which features VLC support (6.10.2). While this isn't ideal it still seems to work no problem.

**Comment by dlrudie** [comment]
See #404
