### ISSUE TITLE
"Spotify is not currently running"

### ISSUE THREAD

**Issue by B-Donk** [dlrudie/Snip#394]
Not sure what I am doing wrong here but snip is not recognizing spotify and the txt file is not displaying anything when a song is playing. I read something about spotify needed to be authorized to use it or vice versa but I am not sure I ever got that or needed that to use it in the past.

**Comment by SamTheCoder777** [comment]
You need to authorize snip on Spotify. On your Windows taskbar, click the arrow button and right-click snip logo. On the menu click Spotify and a tab will open. Sign in and you are done.

**Comment by B-Donk** [comment]
Spotify was already selected and I clicked it and nothing happened. I have used it in the past so I assume I am already authorized

**Comment by B-Donk** [comment]
Downloaded the most recent version and it works now. Thank you for the reply!

**Comment by Citrogen** [comment]
Can't click on the icon in the Windows tray (does nothing when I do)...  Having same issue as above.

**Comment by SamTheCoder777** [comment]
> Can't click on the icon in the Windows tray (does nothing when I do)... Having same issue as above.

Did you try to update it?

**Comment by dlrudie** [comment]
Fixed in 6944341afd2400513eec2131192931f4fce53966
