### ISSUE TITLE
cannot right click, .txt file not being generated

### ISSUE THREAD

**Issue by moodyjo** [dlrudie/Snip#395]
I can't right click on the program, nothing shows up. I have to close it in task manager. No .txt file shows up either.

**Comment by brakerb** [comment]
Hey, I just had the same problem. If you start the program twice you can right-click the second one, weird... ^^

**Comment by Aspoon520** [comment]
I was having a similar issue opening multiple snip apps, but I found that only one will work and others are duds. You should be able to right-click Snip in your file location. Either way, as long as you can get to your Snip properties you can try my solution to the .txt file updating issue.

1.Navigate to Snip in your files
2.Right-click Snip
3.Click Properties
4.Click to the Compatability tab and click Run compatibility troubleshooter
Good luck and happy streaming :)

**Comment by dlrudie** [comment]
Closing this as there's been no further comments.
