### ISSUE TITLE
ISSUE v7.05 - txt file not updating

### ISSUE THREAD

**Issue by kingofmystery** [dlrudie/Snip#396]
hi there

using spotify, snip identifies the song and when I hover over the snip icon I can see the track info, however this does not update in the txt file.
I've had it work at random times, however I have no idea how I got it to work - in my opinion it was trial and error by restarting all my stream apps, snip included.

any ideas?

Thanks

**Comment by Santikun** [comment]
I have this issue as well, can we please get an update?

**Comment by PinkWisp** [comment]
Artwork updates, text does not.

**Comment by Aspoon520** [comment]
I was having a similar issue, I hope my solution works for you too!

1.Navigate to Snip in your files
2.Right click Snip
3.Click Properties
4.In the Compatability tab and click Run compatibility troubleshooter
Goodluck and happy streaming :)

**Comment by Iplay4u** [comment]
Please help, I have the same issue and have tried all solutions posted here and it still doesn't work

**Comment by murko69** [comment]
Could this be a "reading/writing permission" issue? Maybe depends on where you actually put the Snip- folder? Sometimes this happens (at least with other applications) if it's put directly under C:\. In that case 'run as admin' might work, but better yet would be to put Snip directory somewhere else I guess.

**Comment by dlrudie** [comment]
Closing as there's been no further comments.
