### ISSUE TITLE
Blocked by Spotify?

### ISSUE THREAD

**Issue by spoiltcheese** [dlrudie/Snip#397]
I have tried to authorise Spotify to access my playlist but it fails: "Oops, something went wrong...:"
Tried multiple time and multiple browsers and even https://spotify.aidenwallis.co.uk/ . Same problem.

Talking to a service rep at Spotify seems to suggest that they have blocked external parties (or Twitch) from accessing this information. Can you please confirm?

**Comment by dlrudie** [comment]
Next time this happens can you right-click on the page, view source, and copy/paste that here.

**Comment by dlrudie** [comment]
Closing as there's been no further comments.
