### ISSUE TITLE
"Unable to connect" to localhost:10597 after switching to Spotify

### ISSUE THREAD

**Issue by SoNothingMC** [dlrudie/Snip#399]
![image](https://user-images.githubusercontent.com/32032824/66830031-26ace800-ef87-11e9-81d9-35a3596089a0.png)
Taskbar appear as No Track Playing

**Comment by htxrager** [comment]
I get this problem too and when I try to add the Text file to OBS, nothing appears.

**Comment by Helalan** [comment]
Not working for me either

**Comment by Graxo** [comment]
Same, what do i do wrong?

**Comment by dlrudie** [comment]
Fixed in 6f287eb318c4a3bdc193e49097161578998b26e9
