### ISSUE TITLE
Crash for Spotify (Non Premium)

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#40]
Love Snip, love Spotify!

Yesterday my premium went away (temp), since I forgot to pay for premium service. Just noticed today that as soon as ads (audio ads) are starting on Spotify I get an error and if ignored (and closed AFTER the audio ad is done) nothing happens, otherwise Snip killed.

I can attach a screen for you if needed
Otherwise I don't know what info you might need from my end

I probably wont get the error anymore when fixing the premium again, but if it's fixable for others if might be a good thing 

Dunno if attachment or text info helps that much since it's in Swedish but here it is :)

![rjl1d](https://cloud.githubusercontent.com/assets/12071221/8594944/49d89ee6-2646-11e5-8bd0-3bd241124122.jpg)

The infotext in the attachement was this:

Information om att aktivera JIT-felsökning i stället för den 
här dialogrutan finns i slutet av det här meddelandet.

************** Undantagstext **************
System.ArgumentOutOfRangeException: Index låg utanför intervallet. Det får inte vara negativt och måste vara mindre än mängdens storlek.
Parameternamn: index
   vid System.ThrowHelper.ThrowArgumentOutOfRangeException()
   vid CallSite.Target(Closure , CallSite , Object , Int32 )
   vid Winter.Spotify.Update()
   vid Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   vid System.Windows.Forms.Timer.OnTick(EventArgs e)
   vid System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Sammansättningsversion: 5.0.0.0
    Win32-version: 5.0.0.0
    CodeBase: file:///D:/Program/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.CSharp
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34249 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Sammansättningsversion: 0.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_sv_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.resources.dll
----------------------------------------

************** JIT-felsökning **************
För att aktivera JIT-felsökning (just-in-time ) måste .config-filen för det här
tillämpningsprogrammet eller datorn (machine.config) ha 
jitDebugging-värdet angivet i avsnittet system.windows.forms.
Tillämpningsprogrammet måste också vara kompilerat med felsökning
aktiverat.

Till exempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

När JIT-felsökning är aktiverad kommer alla undantag som inte hanteras
att skickas till JIT-felsökaren som är registrerad på datorn
snarare än att hanteras av den här dialogrutan.

**Comment by jaharkema** [comment]
I got the same, but in English :-)  
Also tried to change the Markdown a bit.

Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException()
>    at CallSite.Target(Closure , CallSite , Object , Int32 )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at Winter.Spotify.Update()
>    at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
>    at System.Windows.Forms.Timer.OnTick(EventArgs e)
>    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> \----------------------------------------
> Snip
>     Assembly Version: 5.0.0.0
>     Win32 Version: 5.0.0.0
>     CodeBase: file:///D:/Program%20Files/Snip/Snip.exe
> \----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34250 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> \----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> \----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> \----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> \----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> \----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> \----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.33440
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> \----------------------------------------
> System.Web
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34248 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> \----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> \----------------------------------------
> System.Dynamic
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.33440
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> \----------------------------------------

> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.

> For example:

> \<configuration>
>     \<system.windows.forms jitDebugging="true" />
> \</configuration>

> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
