### ISSUE TITLE
Won't open at all

### ISSUE THREAD

**Issue by Ninja-13** [dlrudie/Snip#401]
Hi I've been using snip for like over a year now and not had very many issues, but recently I can't get snip to open at all. I checked and it's not running in the background either. I was using 7.0.2 then got the new version and still wouldn't open. Also tried previous versions before those as well. I would download the zip, unzip with and without 7zip, and even run as administrator and still nothing. I'm on windows 8.1. And it was working fine just the other day, but then I factory reset my PC just last night and now it won't work. I'm not sure why though, tried everything. If you could get back to me soon I would really appreciate it.

**Comment by user19955** [comment]
Hey did you find the solution for this?

**Comment by Ninja-13** [comment]
Yea, idk what exactly fixed it. But I upgraded my pc and just happened to factory reset my pc, and got fresh install and that seemed to work.
    On Tuesday, April 7, 2020, 12:31:24 PM EDT, user19955 <notifications@github.com> wrote:  
 
 


Hey did you find the solution for this?
