### ISSUE TITLE
Changed to spotify (not updating?)

### ISSUE THREAD

**Issue by Ebbakatten** [dlrudie/Snip#402]
When I start Snip, if I hover over the icon it gives me the message "Changed to Spotify" (In swedish so might not be correctly translated) Then it won't update from there. Txt file empty.

If I have snip running and restart Spotify without restarting Snip, then it changes to "No track playing", but it doesn't update the current playing track when I start a song. Still an empty txt file.

Do I have to start it in a very specific way for it work or? this has to be a bug right? It seems like the program is running, but it's not updating. Might be something on my end as well since I've tried 7.0.5 - 0.2 - 0.1 and still have the same issue on every single one.

**Comment by murko69** [comment]
Did you authorize the app?

**Comment by Ebbakatten** [comment]
Yes, it says spotify authorized message on a new chrome tab every time I try it.

**Comment by Ebbakatten** [comment]
Also tried 6.10.2 now. Accoring to that version, spotify isn't even running when it clearly does. Otherwise, same issue.

**Comment by Ebbakatten** [comment]
Got it to work! For now at least, hopefully for good.
I uninstalled spotify (Windows version) and installed the standalone version instead.
I won't close this yet because I want to make sure that was the issue.

**Comment by Ebbakatten** [comment]
Still works fine. I'm pretty sure what said above was the issue, closing thread

**Comment by GenesisFR** [comment]
The Windows store version never worked with Snip.
