### ISSUE TITLE
Google Play Desktop no longer supported?

### ISSUE THREAD

**Issue by fortris** [dlrudie/Snip#404]
I downloaded 7.0.5 after noticing the "New Version Avaliable!" message but opening 7.0.5 only shows Spotify and iTunes whereas my current version has Spotify, iTunes, Winamp, foobar2000, VLC, GPDMP and Quod Libet.

Were all of these depreciated or did I do something wrong?

**Comment by murko69** [comment]
As of 7.0.0 only iTunes and Spotify is supported.
A direct quote from the 7.0.0-release; _"Removed all media player support except Spotify and iTunes. (I don't have the time to maintain all of the code for all of the media players. I'm sorry about that. Perhaps with a rewrite I can make Snip modular and other people can maintain their own plugins.)"_

**Comment by dlrudie** [comment]
It’s as @murko69 pointed out. I barely have free time to maintain Snip or my other projects, and with each media player that was added every time I’d make a change to Snip I’d have to test that change out in all of the supported players and it just became too much to maintain. I’m not opposed to supporting additional media players; they will just have to be added and maintained by someone other than me. Thanks for understanding.
