### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by teclucas98** [dlrudie/Snip#405]
I tried via Wine but it didn't create the TXT file for use in OBS

**Comment by dlrudie** [comment]
I have no intention of trying to get this to work through wine.

It’s in C# currently. More than likely it would take less effort to implement a native program using mono. Obviously UI stuff would need changed around. But then comes the decision of which GUI to use, GTK, QT, etc.

I have no plans for the foreseeable future. Sorry.
