### ISSUE TITLE
Almost Instantanous Crashes

### ISSUE THREAD

**Issue by JOBNED1** [dlrudie/Snip#407]
Shortly after opening the Snip application after updating to 7.0.5 i got it to run successfully one time... After which every time I try to open the application as soon as I mouse over the icon in the toolbar to see if it is picking up spotify that I have playing it disappears instead... I can't even right click it to change settings as I did in the past.

![What is seen](https://user-images.githubusercontent.com/59860126/72316705-f7c90f80-3664-11ea-8d73-69c04cf883fa.png)

**Comment by carson-wright** [comment]
Try running it as an administrator, that worked for me.

**Comment by dlrudie** [comment]
Closing as there's been no further comments.
