### ISSUE TITLE
Cannot quit snip.

### ISSUE THREAD

**Issue by FluorescentApe** [dlrudie/Snip#409]
In the old version of Snip i could right-click the program and exit. Now nothing happens when i right-click.

**Comment by dlrudie** [comment]
I need more information.

Do you use iTunes or Spotify? If you use Spotify did you authorize Spotify to be used?

I feel like if Snip gets hung up on trying to authorize it becomes unresponsive. You should be able to right click to exit.

**Comment by FluorescentApe** [comment]
Hello David! I quickly realized i needed to authorize spotify in order to
get it working. It works very well right now!

Thanks tho for responding!
