### ISSUE TITLE
Spotify artwork is not redownloaded when resolution changed

### ISSUE THREAD

**Issue by markspolakovs** [dlrudie/Snip#41]
In the latest version at time of writing (v5.0.1, last commit 06c9f7aa), when the Spotify artwork resolution is changed in the taskbar, the track must be changed before it is redownloaded. In the pre-release versions, it automatically got redownloaded.

**Comment by dlrudie** [comment]
I'm not sure if this is something it really needs to do or not.  Perhaps in the future there could be an option for "all sizes."

**Comment by dlrudie** [comment]
I have no plans to change this behavior anymore.
