### ISSUE TITLE
New install - No Track Playing

### ISSUE THREAD

**Issue by moosemedia** [dlrudie/Snip#412]
Reinstalled my PC
Reinstalled Snip 
I get Authenticated message 
Strart playing music, I get No Track Playing, even through the web player.
Help

**Comment by Haaruun-I** [comment]
I am having the same problem, it looks like the localhost server that does all the oath isn't working

**Comment by ItsMadaleine** [comment]
> Reinstalled my PC
> Reinstalled Snip
> I get Authenticated message
> Strart playing music, I get No Track Playing, even through the web player.
> Help

Has this been resolved? I can't find anything for "no track playing" in the solved threads, everything is about Snip not recognizing that Spotify is running.

**Comment by dlrudie** [comment]
Likely fixed in 6944341afd2400513eec2131192931f4fce53966
