### ISSUE TITLE
Save Information Separately not working

### ISSUE THREAD

**Issue by user19955** [dlrudie/Snip#413]
I've searched all over to find what i'm doing wrong (aware this is most likely me not doing something right)
but can't seem to get the artist name or song title to show up when using the "snip_artist" or "snip_track" txt files. But works fine when using the main "snip" txt file where both are together. Any suggestions?

**Comment by murko69** [comment]
Ok, just covering the basics here :
You actually checked the option "save info separate" (4th from above)? :)

**Comment by user19955** [comment]
Yep :)

**Comment by user19955** [comment]
I've figured it out, and as suspected it was an error on my side. But incase anyone else makes the same mistake I'll explain it.
I had previously changed the output format so that $$a and $$t were the opposite way round as I wanted artist name to show up first on stream. It seems that by having changed these round it messed up the code somewhere when trying to fetch the individual data. 

Thanks for making a great program by the way :)

**Comment by murko69** [comment]
I'm sure you are probably not the only one who wants to have artist before track, but the 'workaround' for that is to fetch the info separately - then you can chose order yourself.
I actually should have figured your issue out on the spot. When thinking of it, I actually did the exact same thing when I first started using Snip long ago and that's what made me use the separate info in the first place :)
Somehow I just forgot about it.
