### ISSUE TITLE
Snip not opening Spotify authorization

### ISSUE THREAD

**Issue by user19955** [dlrudie/Snip#414]
Recently changed from an old setup which used foobar.
I've deleted all files to do with foobar and snip,
but when I download the new snip file and double click to open it doesn't bring up the spotify authorization page, any ideas?

**Comment by user19955** [comment]
Also no text files (track/artist etc). The program is not running according to task manager. When I double click (or right click and 'open') I just get the small loading wheel for a second and then nothing happens

**Comment by dlrudie** [comment]
Likely fixed with 6f287eb318c4a3bdc193e49097161578998b26e9
