### ISSUE TITLE
Sending me to the Spotify website

### ISSUE THREAD

**Issue by cartoonist22** [dlrudie/Snip#415]
I just downloaded it. The software itself isn't opening, It's just sending me straight to the Spotify website. I'm wanting to use a different app so how do I open the software itself?

**Comment by dlrudie** [comment]
There may be a misunderstanding. Snip runs in the system tray. On launch you will not see anything really as it just sits in the tray. However, it does require authorization to Spotify so it opens a browser for you to login and grant authorization.
