### ISSUE TITLE
No album artwork

### ISSUE THREAD

**Issue by eric421** [dlrudie/Snip#417]
Getting the track name and artist but nowhere to change the format of it or ‘save’ album artwork so it can show up. Can anybody help?

**Comment by Hellgrint** [comment]
same problem for me

**Comment by gonka26** [comment]
same ;(

**Comment by murko69** [comment]
How do you mean?
Right click on the Snip icon in the system field and chose the third option from the top (right under Spotify and iTunes)
Is called Output format or similar in English


    $$t = Track Title
    $$ut = TRACK TITLE
    $$lt = track title
    $$a = Track Artist
    $$ua = TRACK ARTIST
    $$la = track artist
    $$l = Track Album
    $$ul = TRACK ALBUM
    $$ll = track album
    $$i = Spotify track ID
    $$n = New line

check 4th option if you want track, artist and album name in 3 separate text files
----
5th (and 6th) option from the top is for saving album cover (and the size for it)




Or am I just misunderstanding things?

**Comment by TomAvecLeVdsl** [comment]
Same problem , tryed all 3
`$$l = Track Album
$$ul = TRACK ALBUM
$$ll = track album`
and still not working

**Comment by murko69** [comment]
And you enabled the rest? "saving cover" ?

**Comment by TomAvecLeVdsl** [comment]
Done it right now ... working fine 
Thanks you :)
Have a great day
