### ISSUE TITLE
Trying to fork?

### ISSUE THREAD

**Issue by chezzzer** [dlrudie/Snip#419]
So I'm trying to fork Snip and develop it to my own needs, but I get this on build? Do I not have a certain file orr?
![image](https://user-images.githubusercontent.com/46093784/79426183-dfc3ac00-8016-11ea-9a75-a08cf0687adc.png)

**Comment by GenesisFR** [comment]
https://github.com/dlrudie/Snip/issues/299#issuecomment-406359335
https://github.com/dlrudie/Snip/issues/358#issuecomment-495345346

**Comment by Chezzer-ub** [comment]
thankyou :)

**Comment by Chezzer-ub** [comment]
you should consider trying to get this on the main page.
