### ISSUE TITLE
Unsaved settings

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#42]
First of all thanks for the quick fix (#40).
Second.... I'm kinda new to Github, and dunno if this would fit as an issue or request. Don't know of any support forums for Snip either so...... here we go.

Is there a way to actually save the settings made in Snip or do I have to do it al over each time I need to reboot the computer?

I have Snip set up in autostart but every time I reboot the previous settings are gone. See image! The one on the left is my setting and the one on the right is the default setting that keeps popping up on reboot.

![hhh](https://cloud.githubusercontent.com/assets/12071221/8675907/85d01fe2-2a46-11e5-8a06-4c2a9983310d.png)

I use Spotify + Snip to present kind of a "Now Playing" -signature, using the separate text files for artist, song and album +cover art, auto-syncing them to my host via FTP and then present it (with a bit of coding)...

When the settings is changed upon reboot I lose that signature aswell, since Snip then wont write the info in the separate files anymore... til I change it back.

Any help is appreciated

**Comment by dlrudie** [comment]
It saves settings automatically. It writes values to the registry and reads from them on startup.

**Comment by murko69** [comment]
Saves or should save? =)
I will try and re-install Snip later today and see if that does it.
Thanks for you great work.

**Comment by murko69** [comment]
Adding info!
You are correct when you say that the settings are saved automatically.
IF (and that's an important if :))...... you actually press EXIT after you are happy with your settings.

Next time I reopen the program, the saved settings works fine even if I reboot the computer and let Snip start via autostart.
If I was to change anything in my settings again, and then reboot, those new settings will be gone aswell and my earlier settings would now be the "default" ones.

The key here seems to be EXIT, as in "EXIT=Write values to registry"
I'd prefer a simple save-button or even better, to have the values written to the registry on every change made instead (if possible).

**Comment by dlrudie** [comment]
You are correct.  Only if you exit with the menu will it save.  I will change this behavior to save automatically when any exit event is received.
