### ISSUE TITLE
Could not find any resources appropriate for the specified culture (or the neutral culture) on disk.

### ISSUE THREAD

**Issue by chezzzer** [dlrudie/Snip#420]
Getting this on snip.cs?

![image](https://user-images.githubusercontent.com/46093784/79552292-f63d3680-80ee-11ea-8a82-eaf3a4623a30.png)

**Comment by Overflxw** [comment]
I have this issue too.

**Comment by mrboost** [comment]
Ever find a solution on this? Having the same issue myself

**Comment by dlrudie** [comment]
Is this still an issue? I've checked Snip out on multiple different systems and have been able to build it successfully on all of them.

**Comment by dlrudie** [comment]
This seems related to ApplicationKeys.cs.

df3ad97461badd84791972c4f68cc75c435ad51b
