### ISSUE TITLE
Start new Spotify OAuth flow

### ISSUE THREAD

**Issue by so-dennisp** [dlrudie/Snip#421]
Hi there,

i cant connect another user to Snip with the Spotify OAuth flow.
I already deleted folder, registry etc.

But i always get the following message directly: Snip successfully authorized with Spotify. You may close this window now.

How can i authorize another Spotify account after i already authorized another account?

Dennis

**Comment by murko69** [comment]
You probably need to disconnect via your Spotify account.
Login to your https://www.spotify.com, then click on 'apps' in the left hand menu and then find Snip among your apps and click "revoke" (or whatever it's acalled in your language) 

I don't think you can have more than one user authorized at the time though.....
