### ISSUE TITLE
Cannot find how to use foobar2000

### ISSUE THREAD

**Issue by notNSANE** [dlrudie/Snip#423]
I can't find the option

**Comment by GenesisFR** [comment]
Foobar support went fubar with Snip version 7.

**Comment by JDoawp** [comment]
How come?

**Comment by JDoawp** [comment]
> Foobar support went fubar with Snip version 7.

Assuming the same with Winamp.. How come?

**Comment by GenesisFR** [comment]
Read https://github.com/dlrudie/Snip/releases/tag/v7.0.0

**Comment by dlrudie** [comment]
They were removed as I don't use those players nor have time to maintain any support for them. I'm sorry for not being able to keep them as part of Snip. You're welcome to fork Snip and add them back.
