### ISSUE TITLE
Snip crashes att launch

### ISSUE THREAD

**Issue by SkyyMC** [dlrudie/Snip#425]
When im launching snip on my windows server 2012 r2 it crashes on launch

![image](https://user-images.githubusercontent.com/43611579/81498952-acbeb200-927c-11ea-8b48-e9a89e4f556b.png)

**Comment by murko69** [comment]
Does it crash also if you start as administrator?
Or maybe you need to run the program in compatible mode (dunno if that's the exact English term though)

**Comment by SkyyMC** [comment]
Fixed it updated windows to latest version
