### ISSUE TITLE
Doesnt write to file in VLC

### ISSUE THREAD

**Issue by MrJoki007** [dlrudie/Snip#43]
When i use Snip with VLC and hover over the snip icon it shows the song in the taskbar, but it doesnt want to write it into the file
![j2ywg](https://cloud.githubusercontent.com/assets/8217564/8757652/53582a4e-2cdc-11e5-8ef5-ecc6d462e45e.png)
![j2z4s](https://cloud.githubusercontent.com/assets/8217564/8757662/6f4e8770-2cdc-11e5-9208-621535f8eeb2.png)

**Comment by dlrudie** [comment]
I'll look into this soon.

**Comment by dlrudie** [comment]
I see the issue. I do a check to see if a empty file setting is enabled and if it is it just empties the file. I don't know why I did this. How did this beer get in my hand?
