### ISSUE TITLE
Artwork wont update

### ISSUE THREAD

**Issue by PocketPJ** [dlrudie/Snip#430]
im using Streamlabs OBS and the song title and everything works fine and i have no trouble updating that after closing out of streamlabs or pausing spotify, but it seems if i have spotify closed or paused  the artwork doesnt update. right now to fix this ive just been deleting the source and re adding it to my stream and it updates. Im not sure if theres something im missing in the settings or what..

**Comment by dlrudie** [comment]
This is not related to Snip.
