### ISSUE TITLE
Winamp

### ISSUE THREAD

**Issue by facetcat** [dlrudie/Snip#432]
This used to work with winamp. Why does it no longer?

**Comment by murko69** [comment]
When 7.0.0 was released in July 2019 support on everything but Spotify and iTunes was canceled.
Here's a direct quote from the release notes: "_Removed all media player support except Spotify and iTunes. (I don't have the time to maintain all of the code for all of the media players. I'm sorry about that. Perhaps with a rewrite I can make Snip modular and other people can maintain their own plugins.)_"

**Comment by Yurlyn** [comment]
Could this bit of code not be reinstated? Winamp doesn't get updated anymore anyway so that code doesn't have to change, right?

**Comment by dlrudie** [comment]
I just don't have the time to maintain it all. Supporting something like that goes beyond the code. I still have to respond to emails and issues in Github from people trying to configure/use WInamp correctly.
