### ISSUE TITLE
Forced to link Spotify before App will work at all

### ISSUE THREAD

**Issue by jennec** [dlrudie/Snip#436]
I was not able to use the app at all without first authenticating a Spotify account.  Could not Right Click and configure the app.  Could not choose to use iTunes.  

I do not use Spotify, but to be able to use this app I had to create an account and authenticate the app to it.  

Please remove the unnecessary need to authenticate to Spotify (unless you choose to use Spotify)

**Comment by dlrudie** [comment]
Duplicate #369
