### ISSUE TITLE
Suggestion: Add visual fade-in/fade-out transitions to text between song changes

### ISSUE THREAD

**Issue by npokpongkiat** [dlrudie/Snip#438]
Not sure if there's already a way to do this, but it'd be amazing if there was an option to add fade-in/fade-out transitions to the text between songs!

**Comment by MalicT** [comment]
All snip does is write the song name to a text file, any effects would have to be something that your streaming software would do

**Comment by dlrudie** [comment]
This would be a feature request to OBS or whatever streaming software you use. As MalicT said all Snip does is output to a text file.
