### ISSUE TITLE
How do I uninstall

### ISSUE THREAD

**Issue by Shamallam** [dlrudie/Snip#439]
Can someone please help me? I would like to uninstall snip. Its messing up some of my streaming stuff and I cant play spotify without it open. i would like to remove it from chrome. Please can someone help me on how to do this?

**Comment by GenesisFR** [comment]
Just delete the folder?

**Comment by Shamallam** [comment]
thats the first thing i did. i even cleared the recycle bin. theres nothing on my desktop but its still in chrome.

**Comment by GenesisFR** [comment]
No clue what this is but the official version of Snip doesn't support Chrome. Check your browser extensions, that's how to uninstall it.

**Comment by Shamallam** [comment]
The icon in the middle is snip on chrome. I downloaded it from the github website under dlrudie/snip...its not under the extensions tab, so chrome is def not recognizing it. i only have 4 ext.
![image](https://user-images.githubusercontent.com/70462827/91668735-7d0a1300-ead4-11ea-8fdf-e2a102fc489c.png)

**Comment by Shamallam** [comment]
clearly a bug if its not meant to work on chrome but now its stuck on chrome and it wont go away :(

**Comment by dlrudie** [comment]
This app has nothing to do with Chrome whatsoever. It does not look for, or tie into, anything to do with any rowdier.

**Comment by Shamallam** [comment]
I did delete the folder...theres nothing on my desktop. thats the first thing I did....

**Comment by Shamallam** [comment]
I see how this will go though...closing an issue thats not resolved...thanks for that...

**Comment by dlrudie** [comment]
There’s nothing to resolve. Your problem doesn’t have to do with Snip. You’re looking in the wrong place.

**Comment by Shamallam** [comment]
what do I need to look for then? I downloaded snip and now it wont go away...so where else do I go for snip help?

**Comment by dlrudie** [comment]
I’ll resolve your issue for you… using a search engine. I did one simple Google search for “chrome music icon” and got the answer. The icon you see is a built-in feature of Chrome itself. Whenever you have a tab open playing audio that icon will appear and you can click it to control it.

**Comment by Shamallam** [comment]
well ty for actually resolving my issue. I had never seen that icon pop up until i downloaded snip so not sure if it activated something somewhere. Not everyone is as tech savy as you guys are, sorry to be such a burden when looking for music solutions...
