### ISSUE TITLE
wont save spotify artwork

### ISSUE THREAD

**Issue by Nerxxy** [dlrudie/Snip#441]
title says it all

**Comment by dlrudie** [comment]
If you enable "Save Album Artwork" then Snip will save the artwork to the same directory as Snip.exe but that file is used to always display the most current artwork of the song playing. If you change songs it will overwrite that file with the new artwork. If you stop a song it will overwrite it with a blank song.

If you'd like to permanently save the artwork make sure there is a checkmark in the "Keep Album Artwork" menu item.

![image](https://user-images.githubusercontent.com/1780069/114107876-74ae5d80-9897-11eb-818b-dd92b4e73318.png)
