### ISSUE TITLE
Cover of the song is too big/small and its size changes by playing an other song

### ISSUE THREAD

**Issue by Lxnnqrt** [dlrudie/Snip#446]
Please help me. The size of the Cover changes by playing an other song

**Comment by dlrudie** [comment]
Need more details. Spotify or iTunes? iTunes will simply copy whatever size artwork is stored in the file itself. Spotify maintains a fixed set of sizes for artwork. But even then I can't guarantee the sizes that Spotify provides. I have no control over the size.

**Comment by dlrudie** [comment]
No response.
