### ISSUE TITLE
SUGGESTION: Twitch Soundtrack in .txt

### ISSUE THREAD

**Issue by TheKasarR** [dlrudie/Snip#447]
A suggestion

As latest twitch DMCA maybe you'll add Soundtrack by Twitch application to supported players on Snip?

**Comment by MalicT** [comment]
Be cautious using that, people have been getting DMCAed for music played on that too, it is not fully vetted and still has issues

**Comment by T0biii** [comment]
FYI:
If are Playing a song from Twitch Soundtrack and you hover over the Stream you can see  what is Playing
![TwitchSoundTrack](https://i.tobias.bayern/fszkjiWh.png)

**Comment by dlrudie** [comment]
While I said I won't add or support any more players besides Spotify and iTunes this is one I may look into. The primary reason I even created Snip was for me to display what I was listening to while streaming on Twitch. With the rise of DMCA takedowns this would be beneficial to myself as well as other streamers.

**Comment by dlrudie** [comment]
Quick glance at this and it looks like support for this is integrated straight into your stream so it would be kind of pointless to add to Snip.
