### ISSUE TITLE
Snip not working with OBS 30/11/20

### ISSUE THREAD

**Issue by jass45** [dlrudie/Snip#449]
I used a tutorial on YouTube (https://www.youtube.com/watch?v=a0xVDFATqas&t=83s) which would allow me to connect my spotify to OBS using Snip so i could share the music i was currently listening to on the stream, however yesterday i noticed that OBS stopped showing the Snip music text/music artwork. I deleted an re-installed snip and when i try to install the application, it takes me to a webpage which says 

"This site can’t be reached"
localhost refused to connect.

Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Does anyone know why this is happening??? 

Thanks.

**Comment by scolastico** [comment]
I dont think this is an issue with OBS seems like the internal webserver from Snip is broken.

**Comment by scolastico** [comment]
Tested all versions scince v6.10.1 but none of them are working.

**Comment by Fl00der1000** [comment]
Is there a way to use snip nowadays?

**Comment by dlrudie** [comment]
OBS and Snip really have nothing to do with each other.

It’s been a few weeks since I last tested Snip but as of a few weeks ago it still worked fine for me.

I’ll try to dedicate a little bit of time to Snip this weekend.

**Comment by GenesisFR** [comment]
I tried Snip again last night (stopped using it since the copyrighted music fiasco on Twitch) and it's still working fine with OBS.

**Comment by UniversalBojack** [comment]
Snip is also not working for me. I watched two different video tutorials on how to set it up: https://www.youtube.com/watch?v=tf0JF8mdiYE&feature=youtu.be&ab_channel=ZyphenVisuals      https://www.youtube.com/watch?v=a0xVDFATqas&t=241s&ab_channel=GamingCareers.  The setup isn't the issue, OBS just won't show anything. No widget or text.  The box shows up that there is a source there, but nothing shows up.  Any help would be appreciated.  Thanks

**Comment by MalicT** [comment]
Is Snip generating a text file?

OBS only reads the text file.  Make sure that Snip has permissions to change the file in wherever it is running, read only is off, admin mode, etc

It works fine for me, but I made sure it is generating the files with the above criteria

**Comment by UniversalBojack** [comment]
@MalicT I see a .txt file in the Snip folder.  I put some text in there, saved and dragged in into OBS, and it showed up.  I ran Snip as Admin but still nothing.  How do I go about giving it permissions to change what it needs when running? Also, how or where do I go to check for the " read only" option?

**Comment by MalicT** [comment]
I remember a long time ago where people found to **_not_** install it to either program or program(x86) folder files, it does not have permissions to write there, you need to make a folder somewhere else so it can write things.  I have another program called Snaz that I use for countdown timers and other text that OBS grabs, and I just jammed it in there because I knew it had perms to write to .txt files, and OBS could grab them without issues.

Mine is installed located at C:\Snaz\Snip-v7.0.5\Snip

**Comment by dlrudie** [comment]
You can put Snip anywhere. It doesn’t care if it’s in either Program Files directories, desktop, etc. It only looks in, and writes into, its own directory.

If you’re getting an error about it not being able to reach the web server then you need to check Spotify and make sure it’s running it’s own webserver. Snip relies on Spotify’s web server.

Snip will also only generate the text file once it is working correctly and able to read song info. If you’re getting the web server error then it’s never going to create the file.

I’m at work but I remember there being a setting within Spotify for enabling/disabling the web server. It’s supposed to be enabled by default.

**Comment by dlrudie** [comment]
Also, if it’s connected correctly, you authorized your Spotify account successfully, and it’s still showing that no track is playing then bring Spotify forward and then minimize it. It won’t work if Spotify is running in the system tray if I’m remembering correctly. Spotify has changed their client so much over the years.

**Comment by UniversalBojack** [comment]
@dlrudie @MalicT I got it to work.  I was using Spotify thru a browser tab and not the desktop app.  Using the desktop app it was able to create the txt file correctly.  Thanks for the help.
