### ISSUE TITLE
Save Information Separately Does Not Work When Playing Local Files With No Album Art In Spotify

### ISSUE THREAD

**Issue by The-Evil-Dice** [dlrudie/Snip#45]
Issue is as the title says.

The album art is set to a 1x1 image, Snip.txt updates with the artist and title perfectly fine, however Snip_Album.txt, Snip_Artist.txt and Snip_Track.txt all retain whatever values they had prior to the song being played, whether that be empty or the details of the previous track.

**Comment by dlrudie** [comment]
I'll have to look into this. I've never used the local file feature of Spotify before.

**Comment by craftbyte** [comment]
For me this also happens with songs that have album art

**Comment by DemonDhampir** [comment]
I also have this issue. even when the saved files have got all the Track information, it doesn't grab any of the track information, with the exception of the Mixed "snip.txt" file.
I have version 5.3.0.
If you would like me to grab any information to assist you, just let me know at: vg.dhampir@live.co.uk
Just give me a brief explanation of what to grab and how to grab it, and I would gladly do anything I can to assist.

**Comment by dlrudie** [comment]
No updates.
