### ISSUE TITLE
System.Resources.MissingManifestResourceException when trying to run source code.

### ISSUE THREAD

**Issue by Overflxw** [dlrudie/Snip#452]
Any help would be very appreciated.
![image](https://user-images.githubusercontent.com/77849687/105517012-6ad08180-5cce-11eb-92f5-51d7319cf07c.png)

**Comment by dlrudie** [comment]
This looks like Snip isn't finding the resource files. Make sure you extract all files in the archive.

**Comment by Overflxw** [comment]
> This looks like Snip isn't finding the resource files. Make sure you extract all files in the archive.

I installed the zip for the source code, I just reinstalled another just to make sure I hadn't accidentally deleted a file. However I still get the same error, are you able to check on your side if there are any missing files? Thank you.

**Comment by dlrudie** [comment]
Why are you using the source code? Unless you plan to compile it yourself or contribute there's no reason for it. Download the binary release.

**Comment by Overflxw** [comment]
> Why are you using the source code? Unless you plan to compile it yourself or contribute there's no reason for it. Download the binary release.

I am new to programming and was interested as to how you implement the Spotify API into a C# program so I wanted to experiment with the source code to see what I can do (like adding features and other stuff) purely just for personal use.

**Comment by dlrudie** [comment]
That's fine and all but I really can't help you with the setup of the VS solution. There will always be minor things you'll have to configure before it will work. You're going to want your own API key to input. Create an ApplicationKeys.cs file and put your API key in it. Then attempt to build. The resources it's talking about in your screenshot has to do with the assembled resource files from the .txt files. If it can't find that then it's not building successfully, which it won't without ApplicationKeys.cs.

```
namespace Winter
{
    public static class ApplicationKeys
    {
        public const string Spotify = "YOURKEY";
    }
}
```

**Comment by Overflxw** [comment]
> That's fine and all but I really can't help you with the setup of the VS solution. There will always be minor things you'll have to configure before it will work. You're going to want your own API key to input. Create an ApplicationKeys.cs file and put your API key in it. Then attempt to build. The resources it's talking about in your screenshot has to do with the assembled resource files from the .txt files. If it can't find that then it's not building successfully, which it won't without ApplicationKeys.cs.
> 
> ```
> namespace Winter
> {
>     public static class ApplicationKeys
>     {
>         public const string Spotify = "YOURKEY";
>     }
> }
> ```

Thank you for the help, I had already seen on a comment by someone else somewhere on this project detailing what to write for the ApplicationKeys.cs however it was written wrong. This reply has resolved my issue thank you.

**Comment by dlrudie** [comment]
I'll add a dummy ApplicationKeys.cs file to the repo with instructions at some point.

**Comment by Overflxw** [comment]
> I'll add a dummy ApplicationKeys.cs file to the repo with instructions at some point.

Yeah, sounds like a good idea lol

**Comment by dlrudie** [comment]
I only haven't because I don't know git well enough and I don't want to include my own ApplicationKeys.cs. I'm sure there's a way to have that file and not overwrite it with my own, or I could just do a ApplicationKeys.cs.EDITME or something.

**Comment by GenesisFR** [comment]
> I only haven't because I don't know git well enough and I don't want to include my own ApplicationKeys.cs. I'm sure there's a way to have that file and not overwrite it with my own, or I could just do a ApplicationKeys.cs.EDITME or something.

In the .gitignore file I'm sure you can do that, have local changes ignored for some files.

**Comment by dlrudie** [comment]
Added instrcutions in df3ad97461badd84791972c4f68cc75c435ad51b
