### ISSUE TITLE
Framework Error

### ISSUE THREAD

**Issue by exxulary** [dlrudie/Snip#454]
![Capture](https://user-images.githubusercontent.com/80090631/110078472-a6825080-7d3c-11eb-946e-cf58c3962dd9.PNG)
i got this error while trying to switch to VLC. Im using the older version v6.10 because i dont pay for itunes or spotify and would rather use vlc.

**Comment by GenesisFR** [comment]
And what's in Details?

**Comment by dlrudie** [comment]
This error really doesn't give me much to go off of. As @GenesisFR said, what's in the details?

Also, informative note in case you weren't aware, you don't have to pay for iTunes or Spotify. Both are free and would operate just like VLC in the sense that you can import your own music into the clients.

**Comment by dlrudie** [comment]
No further details provided.
