### ISSUE TITLE
Snip opens localhost website that doesn't show

### ISSUE THREAD

**Issue by omgmajk** [dlrudie/Snip#455]
Whenever I open Snip it opens a localhost website (http://localhost:10597/code) that doesn't display anything/fails to load. Is there a way to remove this from happening?

**Comment by dlrudie** [comment]
With Spotify's API when you authenticate there are tokens exchanged between Snip and Spotify. These token exchanges are done through the web.  A local server is spun up to receive that token and use it to authenticate. A page should always open but it shouldn't be blank. If you've already logged in with Spotify then it should open to a page that says you were authenticated successfully and that you can close the window now.

**Comment by Maxprotrad3r** [comment]
Hi I got same problem too. The website used to show as you said "Spotify connected" and it works as intent. After re-install Windows I have to reconnect but the Local host site always fail to reached. I tried different browsers and still got "fail to load/reach" notifications. How can I solve this problem then?

**Comment by Maxprotrad3r** [comment]
Hi I got same problem too. The website used to show as you said "Spotify connected" and it works as intent. After re-install Windows I have to reconnect but the Local host site always fail to reached. I tried different browsers and still got "fail to load/reach" notifications. How can I solve this problem then?

**Comment by dlrudie** [comment]
Resolved in 6f287eb318c4a3bdc193e49097161578998b26e9
