### ISSUE TITLE
unable to connect to local host 

### ISSUE THREAD

**Issue by AjaxAjaxAjax** [dlrudie/Snip#458]
I have used Snip totally fine in the past (great little program btw). I tried to boot it up today and log into my spotify, however once I authorize Snip it brings up the following page:
![problem](https://user-images.githubusercontent.com/39123567/114188510-90476000-998c-11eb-8ba8-2e1f92b4d307.png)

 I have tried reinstalling Snip, as well restarting my system to no avail. Any help would be greatly appreciated :)

**Comment by dlrudie** [comment]
Make sure you run Snip as administrator.

I still plan to get back to this to do away with the login window.

**Comment by Brilliafy** [comment]
This happened to me too. Running as administrator made no difference. I am so confused as to why this would be the case, since it worked fine yesterday :(

**Comment by dlrudie** [comment]
Resolved in 6f287eb318c4a3bdc193e49097161578998b26e9
