### ISSUE TITLE
Not detecting Soundtrack (Spotify)

### ISSUE THREAD

**Issue by VisualKitten** [dlrudie/Snip#460]
it simply doesnt detect sound and i have 2 hours left for it so ?

**Comment by VisualKitten** [comment]
I fixed it, turns out Snip was trying to play from another account not the correct.

**Comment by dlrudie** [comment]
This is correct. For future reference if anyone stumbles upon this ticket… if you’re ever logged into one account and you need to switch to another, first exit snip, then log into Spotify’s website under the account you want to disconnect. Go to the apps section and disconnect Snip from that account. When you launch Snip it will ask you to sign in again.
