### ISSUE TITLE
Does Not Update Snip.txt and Snip_Artwork.jpg

### ISSUE THREAD

**Issue by BadWolf1023** [dlrudie/Snip#461]
Rare bug, happens every 30 songs or so for me. Seemingly random, the .txt and .jpg won't update for one song. It will update on the next song though, so it's not "stuck" per say. It's like it simply missed the song change event for a song.

![image](https://user-images.githubusercontent.com/23650362/116810930-1aa65e00-ab0c-11eb-81a5-8b97634b3c3f.png)

![image](https://user-images.githubusercontent.com/23650362/116810947-314cb500-ab0c-11eb-8d64-a80d7869104f.png)

**Comment by BadWolf1023** [comment]
Also, the name of the spotify.exe does change when this happens. So can rule that out. (Read that Snip detects song change based on spotify window name changing.)

**Comment by dlrudie** [comment]
I'm with you here. I experience this myself. It's random when it happens. Something just isn't lining up right.

**Comment by EchoLWS** [comment]
Am having this issue, makes it unusable. please fix this

**Comment by murko69** [comment]
> Am having this issue, makes it unusable. please fix this

Unusable is a pretty strong use of word IMO. I'm also having this 'glitch' from time to time.
Sometimes I also have an issue like Snip is one song behind and when a track starts it wil update according to the track that just ended. This usually fixes itself with the bug reported in this thread - but unusable - far from it!
