### ISSUE TITLE
Changes to spotify 

### ISSUE THREAD

**Issue by harryhargreaves2** [dlrudie/Snip#462]
Just received version 1.1.59.714.g7e040462-a and Snip is not working any more. Anyone else having the same issue?

Tried Rebooting - reinstalling all apps etc - no improvement.

When I start SNIP it confirms "Snip successfully authorized with Spotify. You may close this window now."  - but no metadata received.

**Comment by xmaspoo** [comment]
I'm having the same issue with the new version of Spotify.

**Comment by dlrudie** [comment]
It's still working here. I'm on 1.1.60.668.gff09d345-a which is even newer.

Are you running Snip as Administrator? (It's required)

I've tested opening Spotify and playing songs, as well as minimizing to the tray and switching songs, and Snip updates correctly.

![image](https://user-images.githubusercontent.com/1780069/119710390-e892ce00-be23-11eb-8f67-7d3a4c535471.png)

**Comment by harryhargreaves2** [comment]
Will run as administreator Many thanks for your reply Harry ent from Mail for Windows 10 From: David RudieSent: 26 May 2021 19:12To: dlrudie/SnipCc: harryhargreaves2; AuthorSubject: Re: [dlrudie/Snip] Changes to spotify (#462) It's still working here. I'm on 1.1.60.668.gff09d345-a which is even newer.Are you running Snip as Administrator? (It's required)I've tested opening Spotify and playing songs, as well as minimizing to the tray and switching songs, and Snip updates correctly.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
