### ISSUE TITLE
No Track Playing

### ISSUE THREAD

**Issue by romanzdr** [dlrudie/Snip#463]
![Снимок экрана (2)](https://user-images.githubusercontent.com/85021239/120070028-a078e300-c091-11eb-9e59-b136bfd20b56.png)
I ran it as an administrator, there is no track
how can I fix it?

**Comment by mramirezpages** [comment]
Same

**Comment by dlrudie** [comment]
Fixed with 6944341afd2400513eec2131192931f4fce53966
