### ISSUE TITLE
Spotify: cleanup files when there’s no artwork or no album/artist

### ISSUE THREAD

**Issue by Elarcis** [dlrudie/Snip#464]
Spotify has the ability to play local files in its player. Sometimes, they don’t have an album name nor an album artwork.

Snip correctly shows the updated song name, but when the player goes from a song with an album/artwork to a song without, the files Snip writes into aren’t emptied, and the new song keeps the previous album cover and name. This stays like this until I pause the player, time at which Snips cleans up the files and the proper infos are shown.

Example: track title and artist are good, but the artwork and album are from the previous track.
![image](https://user-images.githubusercontent.com/990841/121936480-f7491280-cd49-11eb-9f13-51882d8fa282.png)

After pausing/resuming: 
![image](https://user-images.githubusercontent.com/990841/121936679-2cedfb80-cd4a-11eb-87fe-98d831daee2a.png)

**Comment by dlrudie** [comment]
Local file playing through Spotify is still highly unexperimented with on my end. This may be a bug. I'll add it to my list.

**Comment by dlrudie** [comment]
Not really a duplicate but going to isolate to #443.
