### ISSUE TITLE
Output changes don't work

### ISSUE THREAD

**Issue by mipez** [dlrudie/Snip#47]
Snip v5.0.5 / WinAmp v5.65

The output settings don't work properly. The input is saved in the registry and loaded on start, but there are no changes whatsoever. It uses the standard format instead.

Also the option so save the song information seperately doesn't work, it simply writes a single space char.

Otherwise the current track and artist is displayed as given by WinAmp.

**Comment by dlrudie** [comment]
This information is located in the readme file.
