### ISSUE TITLE
Multiple .txt files please

### ISSUE THREAD

**Issue by Androidphonetoucher** [dlrudie/Snip#471]

**Comment by Androidphonetoucher** [comment]
Would like the ability for Snip to generate multiple TXT files, so that one can give track title, and the other artist name.

This would give much greater flexibility for formatting when inserting in to OBS etc (rather than one big line of text). Thank you! :-)

**Comment by dlrudie** [comment]
This option already exists. Right-click on Snip in the system tray and there’s an option to enable multiple file outputs.

**Comment by Androidphonetoucher** [comment]
I LOVE YOU!! Thanks I didn't know this :-)
