### ISSUE TITLE
How to disable Hotkeys

### ISSUE THREAD

**Issue by IAmLizzy** [dlrudie/Snip#473]
The Hotkeys need an option to be changed or disabled, as the current ones don't work very well with german keyboards (qwertz) as several characters, such as for example the tilde and backwards slash can't be typed anymore.

**Comment by dlrudie** [comment]
While there is no current option to change the hotkeys you can disable them. Once Snip starts up right-click on the Snip icon in the system tray and there will be an option "Enable Hotkeys" with a checkmark. Just click that to disable it.

**Comment by GenesisFR** [comment]
You can use AutoHotkey to circumvent that limitation through remapping hotkeys or hotkey combinations to tilde and backslash.

**Comment by IAmLizzy** [comment]
> While there is no current option to change the hotkeys you can disable them. Once Snip starts up right-click on the Snip icon in the system tray and there will be an option "Enable Hotkeys" with a checkmark. Just click that to disable it.

Oh well where are my eyes. thanks for reminding me, and sorry for bringing up this unneccesary issue. we can close it, or leave it open for the aspect of changing the hotkeys.
