### ISSUE TITLE
Itunes radio album artwork

### ISSUE THREAD

**Issue by Gonz0444** [dlrudie/Snip#474]
When I play music from my library in Itunes snip will grab all of the info including the album artwork just fine, however if I am playing a radio station snip will grab everything except for the album artwork. I have tried toggling various options as well as restarting both snip and Itunes and have not had any success.

**Comment by Sysadminfromhell** [comment]
Same Problem here, some news?

**Comment by dlrudie** [comment]
No news. Haven't touched it. Not sure when I'll get to it. It's on the list to look into though.

**Comment by Sysadminfromhell** [comment]
Some news around here?

**Comment by Sysadminfromhell** [comment]
Hey there, new year new try.
Whats about the Art Cover? Soimething new yet?
I saw a PL could see through it?

**Comment by Aractor** [comment]
Still seems to be an issue. Works great with local iTunes library files, but will not display album artwork from iTunes radio.

**Comment by dlrudie** [comment]
I'll revisit this soon and see if the iTunes COM library provides a way to get this information. I seem to remember the last time I looked it doesn't. I feel like it's this way because the iTunes COM library was created before they even had a radio and they haven't touched updating the COM library since. But I'll see.

**Comment by dlrudie** [comment]
I looked through the iTunes COM library and tested many various things but so far it seems impossible to get any details from anything other than local files.

There is an [IITURLTrack](https://documentation.help/iTunesCOM/interfaceIITURLTrack.html) interface but it doesn't provide anything really. All of the functions return nothing other than the name of the radio station itself.

Unfortunately this will not be possible to implement.
