### ISSUE TITLE
Not detecting Spotify

### ISSUE THREAD

**Issue by funkdoobeast** [dlrudie/Snip#476]
Snip is not recognizing Spotify Desktop on Win10 for me and it doesn't work with the web player either. Tried starting it normally and as admin in every combination possible (start order, admin privileges).

**Comment by dlrudie** [comment]
I'm assuming by stating Spotify Desktop that you are using the standalone Spotify and not the Windows Store version?

To clarify, have you tried:
1) Without Snip running, start Spotify first.
2) Play a track and pause it.
3) Start Snip.
4) Unpause the track and see if Snip detects it.

**Comment by dlrudie** [comment]
Fixed with 6944341afd2400513eec2131192931f4fce53966
