### ISSUE TITLE
The txts are not updating

### ISSUE THREAD

**Issue by HugoJupiter** [dlrudie/Snip#479]
Hello, every time since i installed Snip, the txts won't update. I start both spotify and snip but my txt file won't show any track info ... Can somebody help me please ?

**Comment by Corbinator333** [comment]
Same, I have spotify open on my PC and I hover over the little snaz icon and it shows this:
![image](https://user-images.githubusercontent.com/63374705/147714463-bd47a781-40c3-46ea-af40-09bcdf0b402f.png)
I have my playlist I play on my Twitch streams going, and the .txt files just won't update, and Snip refuses to discover the song.

**Comment by dlrudie** [comment]
Sometimes this is the case where restarting Snip will allow it to detect Spotify correctly. This will eventually not be the case.

**Comment by dlrudie** [comment]
Resolved with 6944341afd2400513eec2131192931f4fce53966
