### ISSUE TITLE
Information doesn't update, always same song and album artwork with spotify

### ISSUE THREAD

**Issue by Kaneco** [dlrudie/Snip#48]
I've tried everything, running as admin, restarting my pc, restarting spotify, redownloading snip, resetting snip settings and the same song is always on the album artwork and snip.txt

“Left Hand Free - Live from Lido, Berlin” ― alt-J

Always this song, I even activated song history and when I change song this damn song repeats itself in the song history file when I change song.

**Comment by dlrudie** [comment]
As long as the track information is changing in the Spotify titlebar it should work fine.
