### ISSUE TITLE
Unable to drag to OBS Scene

### ISSUE THREAD

**Issue by okindoy** [dlrudie/Snip#482]
Everytime I try to drag the generated .txt file, it is unable to do so, or isnt allowed to. Is it because of the newer version of OBS?

**Comment by MacStevins** [comment]
Well, because it's just data and not an actual thing that obs can use

**Comment by dlrudie** [comment]
This would be an issue unrelated to Snip. Snip just simply outputs data to a text file. How you use that text file is up to you. To use it with OBS you would need to create a text source and then point it to the text file.
