### ISSUE TITLE
Switching Accounts

### ISSUE THREAD

**Issue by VeXNimrod** [dlrudie/Snip#483]
How could I switch Spotify accounts and or uninstall Snip to reinstall and link a different account?

**Comment by TahSquid** [comment]
Is there a followup on this, I'm wondering the same. I have multiple Spotify accounts and manage to loginto the wrong one.

**Comment by murko69** [comment]
If you log in to your Spotify account (the one connected with Snip) you could always un-link Snip that way via Apps - remove access, and then restart with a new Spotify account
![b581b3b6bcef0ca70b733f8959e17e55](https://user-images.githubusercontent.com/12071221/152870056-64ee2ec8-c10b-4391-bcdb-73f57d09b1de.png)
 
 If I'm not totally misunderstanding the issue :)

**Comment by TahSquid** [comment]
@murko69 
> If I'm not totally misunderstanding the issue :)

Nono, this is what I asked for! I never knew such thing on Spotify existed, haha. Thanks!

**Comment by dlrudie** [comment]
Thanks, @murko69, for keeping up with these issues. I appreciate it!
