### ISSUE TITLE
Feature: Option split title and artist

### ISSUE THREAD

**Issue by yansaan** [dlrudie/Snip#485]
Hello, please make option (or checklist) artist and title song in to 2 file (without splitter)

#### artist.txt
```
Name Artist
```

#### title.txt
```
Name Tittle song
```

**Comment by murko69** [comment]
This is already an option.
All you need to do is check the "save information separately" (or similar acordning to your language settings) and you will get the two files: Snip_Artist.txt and Snip_Track.txt.
