### ISSUE TITLE
VPN interferes with Snip's work

### ISSUE THREAD

**Issue by gmsam** [dlrudie/Snip#487]
I turn on VPN in Windows and Snip stops working - covers and text in OBS are not displayed. I turn off the VPN - everything works as it should. This problem appeared a couple of weeks ago, although before that VPN did not interfere with the correct operation of Snip. I turn on another VPN, which does not work through Windows, and Snip works as it should. What can be wrong?

**Comment by gmsam** [comment]
I turned on the problematic VPN, clicked on all the links that you sent me - all the links opened without problems

**Comment by dlrudie** [comment]
I couldn't say why it wouldn't work then.

Do you have Snip running before connecting to the VPN? It may be that when you connect to the VPN, and if Snip is already running, it may try to still access the internet through your normal network interface and not the VPN interface. Have you tried launching Spotify and Snip after the connection to that VPN is already established?

**Comment by gmsam** [comment]
I closed Spotify and Snip. Enabled VPN. Recorded a video of the whole process https://skr.sh/vCTnofHfDMf?a

**Comment by gmsam** [comment]
An example of a video when the VPN is completely turned off and everything works as it should https://skr.sh/vCTUR36K8km?a

**Comment by gmsam** [comment]
I turn on the VPN, which works by itself, and not through Windows - Snip works as it should https://skr.sh/vCTTD57klkA?a

**Comment by gmsam** [comment]
![switched](https://user-images.githubusercontent.com/60562199/153764288-3338dd06-2dea-4124-8767-41f3221087a8.jpg)
when the problematic VPN is turned on, the inscription "switched to spotify" appears

**Comment by dlrudie** [comment]
Fixed in 6944341afd2400513eec2131192931f4fce53966
