### ISSUE TITLE
Nothing Updates

### ISSUE THREAD

**Issue by Meowdyy** [dlrudie/Snip#490]
I have restarted snip several times as well as obs and spotify and nothing wants to update. On top of that, the artwork shows in really low quality any fixes?

**Comment by Meowdyy** [comment]
Edit: it seems to update very randomly, sometimes it updates and sometimes it doesn't and I was able to fix the low resolution artwork

**Comment by dlrudie** [comment]
Likely fixed in 6944341afd2400513eec2131192931f4fce53966
