### ISSUE TITLE
"No track playing" when spotify is paused

### ISSUE THREAD

**Issue by MrInvisible97** [dlrudie/Snip#491]
Hi, is there a way to make output file not empty while spotify is paused ? Or just let last song in file ? 
Thnaks

**Comment by Nerxxy** [comment]
![image](https://user-images.githubusercontent.com/37718547/158442116-c0909187-112e-4190-a89e-88b93791c2b7.png)

Have tried unticking this option?

If you don't know how to get that menu then just right click on the snip icon in the bottom right of your taskbar

**Comment by MrInvisible97** [comment]
Hi, thnaks for your reply. Unfortunately i have it unchecked so there is
"No track playing "
When i check that option, there is nothing. I tried to find something in
source code but i fail.

út 15. 3. 2022 v 19:02 odesílatel Nerxxy ***@***.***> napsal:

**Comment by dlrudie** [comment]
I'm sorry; I have no plans to change the current way it operates.
