### ISSUE TITLE
not working lately

### ISSUE THREAD

**Issue by MattStreams** [dlrudie/Snip#493]
not updating, or always a track behind. need to constantly update manually. anyone else?

**Comment by murko69** [comment]
It's a strange thing indeed.
If I just play music on my computer directly, then Snip falls a track behind on several occasions then randomly 'skips' a track to be on spot again for a few tracks, only to fall one behind again.

But.... If I start Spotify on my computer or phone and THEN cast it to another unit in the house, it works flawlessly 100%

**Comment by dlrudie** [comment]
Closing this because I'm going to bank on 6944341afd2400513eec2131192931f4fce53966 fixing this.
