### ISSUE TITLE
No txt file data

### ISSUE THREAD

**Issue by bluespark23** [dlrudie/Snip#494]
no songnames in the text file.. 

Windows 11 updated regularly.

re-installed spotify and snip from scratch
checked that spotify account allows access to snip
started snip as admin
nothing works :(

I get "switched to spotify" but no other data in the text file.

It was working fine until a few weeks ago  :(    please, if anyone can help?

**Comment by aJanism123** [comment]
U ever figure this out? I have the same issue

**Comment by dlrudie** [comment]
This should be fixed in 6944341afd2400513eec2131192931f4fce53966
