### ISSUE TITLE
text files not updating

### ISSUE THREAD

**Issue by sainsdy** [dlrudie/Snip#497]
Occasional bug, happens every 10 songs or so for me. Seemingly random, none of the .txt and .jpg files will update when the song changes. It may update on the next song though, sometimes it misses 2 songs in a row. It's like it simply missed the song change event for a song.
Snip version 7.05
Spotify Version: 1.1.85.895.g2a71e1b8 (15/5/2022)
I close spotify and reopen and it seems okay, but starts up again after both apps have been open for a few hours.

**Comment by murko69** [comment]
This happens for me aswell and have done so for a long time.
It seems totally random and somtimes the image even updates one track to late making it unsynced for a few tracks before everything works fine again (got nothing to do witch cache on my end though - I got that covered :D).

However...
Sometimes when I run Spotify I chose to cast it with Chromecast to the TV instead (great sound through that speaker system) and then there is never this 'glitch'

**Comment by karimawii** [comment]
Same here, metadata sometimes doesn't update

**Comment by karimawii** [comment]
I think David should replace the token authorization with app authorization, and just let everyone add their client secret and ID, this would be way less buggy since the token expires over time. I'm not a dev though, so don't take my word, but I think that'd solve the problem.

**Comment by dlrudie** [comment]
I'll try to return to working on Snip soon. The tokens do expire but there's provisions in the API and in Snip's code to update the token automatically. I can still open/use Snip just fine and never have any problems with tracks not updating, but I shut my computer down most nights so Snip never really stays running for extended periods of time.

Spotify just updates their client and API so frequently that I don't really keep up with all of the changes too well, especially with my busy life.

I have no plans to make users enter their own keys. That would require additional steps. The goal is to make it just work. You open it up, sign into your Spotify account, and then you're done. I've started work on the next iteration of Snip but it's been slow as my time is limited. I may copy over some of those changes to this version of Snip to try to cut out some bugs or issues. I just need time.

**Comment by JosephGriffith1** [comment]
I'm having this issue too, exactly as murko69 describes. I've needed to open the Spotify app for Snip and play music from Spotify Web to prevent this from happening. Only annoyance is the Web version of spotify doesn't have the crossfade feature.

I found that you could easily get it do to lag/fail to update by quickly skipping to the next song a couple times then occasionally going back a track.

**Comment by JosephGriffith1** [comment]
I'm having this issue too, exactly as murko69 describes. I've needed to open the Spotify app for Snip and play music from Spotify Web to prevent this from happening. Only annoyance is the Web version of spotify doesn't have the crossfade feature.

I found that you could easily get it to lag/fail to update by quickly skipping to the next song a couple times then occasionally going back a track until eventually the track name and image fails to update.

**Comment by karimawii** [comment]
I'm using [Songify](https://github.com/songify-rocks/Songify) as an alternative for the time being, this is not to take away from Snip, just so people can continue having the features Snip has if it's not working properly for them

**Comment by dlrudie** [comment]
Likely fixed in 6944341afd2400513eec2131192931f4fce53966
