### ISSUE TITLE
Changing Spotify accounts

### ISSUE THREAD

**Issue by ItsMadaleine** [dlrudie/Snip#498]
I'm  having an issue where Snip stops working. The only way to get it to work again is to log into Spotify again at the permission prompt. I would like to log out of my Spotify account in Snip (aka reauthorize Snip to use my Spotify acct),  however, I don't know how to do that. Occasionally, if I uninstall Snip and reinstall, I'll get the login prompt, however, more often than not, I do not have this option. Is there a way to manually log out and reauthorize? I hope this makes sense, I'm not sure how to explain it better.

**Comment by ItsMadaleine** [comment]
Can anyone help me with this??

**Comment by GenesisFR** [comment]
You have to go on the Spotify website, log in, check in the authorized apps and remove Snip from the list.

**Comment by ItsMadaleine** [comment]
> You have to go to the Spotify website, log in, check in the authorized apps and remove Snip from the list.

That worked!! Thank you so much!!! I was able to log back in and it fixed the "no track playing" issue.
