### ISSUE TITLE
Snip stopped working for me

### ISSUE THREAD

**Issue by aJanism123** [dlrudie/Snip#500]
I use snip for streaming using OBS. Whenever I play songs, i noticed that nothing was showing up on my stream. After looking into it, i realized that the Snip.txt and Artwork werent showing anything. I tried to disconnect snip from my spotify and reconnecting, logging in and out of spotify, and also tried reinstalling Snip. However nothing has worked so far. It was working fine a few days ago but suddenly it stopped working for me. Any ideas?

**Comment by NeonLightning** [comment]
same here

**Comment by dlrudie** [comment]
This may be resolved with 6944341afd2400513eec2131192931f4fce53966
