### ISSUE TITLE
Annoying text glitch when playing music; can't find any other reports of this problem.

### ISSUE THREAD

**Issue by CyberTruckerAlpha** [dlrudie/Snip#501]
I use snip to display whatever I happen to be playing on WinAmp if gameplay gets a little too quiet, while streaming on OBS Studio. Problem is there's a weird issue that I'm not really seeing anywhere else.
1.gif is how it should be working: scrolling looped text that changes with each song. Problem is when I turn off music for awhile, and then turn it back on later:
We get something like 2.jpg, or worse. The text glitches out completely and no longer scrolls. The only way to fix it is to turn off the text source and turn it back on, which effectively refreshes it. I wouldn't call that a solution, however, as I need to manually do this while streaming live.
3.png is my text source settings and 4.png is my scroll filter settings, in case it's my settings that are somehow causing the problem.
![1](https://user-images.githubusercontent.com/95217754/189501267-7a2f05fb-6949-4efb-995b-9b1e7de440e2.gif)
![2](https://user-images.githubusercontent.com/95217754/189501268-e776776c-55b2-41bf-adea-edc9bd507640.jpg)
![3](https://user-images.githubusercontent.com/95217754/189501269-3dddd927-457c-46c5-94c3-ae78a16a8830.png)
![4](https://user-images.githubusercontent.com/95217754/189501271-24daeb49-760e-45d8-b79e-6258b399a75e.png)

**Comment by dlrudie** [comment]
OBS has absolutely nothing to do with Snip. You may want to reach out to their forums for assistance in setting that up.
https://obsproject.com/forum/

**Comment by CyberTruckerAlpha** [comment]
Yeah thanks a lot.
