### ISSUE TITLE
Update broke snip

### ISSUE THREAD

**Issue by danteblades** [dlrudie/Snip#502]
It seems on the newest version of spotify it breaks snip for me

**Comment by raespark** [comment]
Having the same issue :(

**Comment by JesseCaddell** [comment]
can confirm having the same issue as well

**Comment by MikoLee2333** [comment]
I got same issue too. After the update of spotify, snip could not catch the song info out now.

**Comment by hemidragon** [comment]
Can confirm, as of today, snip does not pick up spotify album art nor titles anymore.
Usual spotify restart, snip restart or selecting relevant software to hook into workarounds don't work anymore.

**Comment by tahakuzgun** [comment]
same

**Comment by edwrios** [comment]
Same here. Not working anymore with the last update (Spotify 1.1.94.870.gf994cb0b)

**Comment by dlrudie** [comment]
I'm looking into it.

**Comment by dlrudie** [comment]
This is a weird one for me. If I run Spotify on one computer I can't get it to work at all. But if I run it on another system it works perfectly fine.

I stripped out all of the code that detects if Spotify is even running locally so it just relies on the web API from Spotify. On the development system I stil cannot get it to recognize that Spotify is even playing a song. However, if I open Spotify on another computer and hit play, then Snip on that system properly detects the song playing. I can also play a song in Spotify on my phone and it will also detect that successfully.

The Spotify app running on my dev PC can also play a song separately of all other devices. My gaming PC and phone share the account and if I play it on one it pauses it on the other so I can't play it on two devices at once.

Something is definitely weird.

**Comment by JesseCaddell** [comment]
Seems the issue you encountered between devices is being looked into by Spotify. May have to wait for a fix.

https://community.spotify.com/t5/Ongoing-Issues/Connect-feature-not-working-properly-on-the-Desktop-app/idi-p/5431952

**Comment by dlrudie** [comment]
@JesseCaddell Thank you for that link! I have a feeling Snip will just start working normally again once they fix that.

**Comment by hemidragon** [comment]
What an odd issue.. Let's wait and see then! Might take up to a few weeks for them.
Just for added record, I've been using Snip on a single PC locally with no extras.

Thanks for looking into it, @dlrudie!

**Comment by dlrudie** [comment]
On a side note. I can drop scanning for the actual Spotify app running and straight-up use the API to determine all that information. This can make it so you can run Snip on any system whether you have Spotify running on it or not and it can still get the details. (i.e. you can have Spotify playing a song on your phone and the Snip app will still report what's playing)

**Comment by hemidragon** [comment]
Oh hey, you were right, @dlrudie! Updated Spotify just a minute ago and snip came back to life. That was nice of Spotify devs to fix that one issue real fast (reported Monday, fixed by Thursday).

![SpotVersion](https://user-images.githubusercontent.com/40802261/191797799-61cd5c2c-fc6c-4db2-a0b6-6888599a5e34.jpg)

**Comment by JesseCaddell** [comment]
Thanks for the update @hemidragon and for the ss of the Spotify version. I checked and needed to update myself. Snip is back!

**Comment by dlrudie** [comment]
Tested on 1.1.94.872.g7a9200fe on my development computer (the one that exhibited the issue as well) and it is working again normally. Thank you, @hemidragon, for letting me know they updated it. I'm still working on an overhauled version of Snip (albeit slowly) which should work far more reliably.

Closing this ticket. Thanks, everyone.

**Comment by MikoLee2333** [comment]
Can't wait to see the new version
