### ISSUE TITLE
"No Track Playing" - Not detecting any music

### ISSUE THREAD

**Issue by Noahhjnz** [dlrudie/Snip#503]
I'm trying to use snip for OBS, but the main problem I've ran into is snip not detecting any music playing, when I hover over the program in my taskbar it says "No track playing" even when I have music on.

I've tried reinstalling the program, signing in and out of Spotify and tried using the web version of Spotify and the app and also restarting my computer entirely, no luck. 

any advice? much appreciated.

**Comment by hemidragon** [comment]
#502 
It's a very recent issue, being looked into.

**Comment by dlrudie** [comment]
Duplicate #502.
