### ISSUE TITLE
No Text in Snip.txt

### ISSUE THREAD

**Issue by brianfonr** [dlrudie/Snip#504]
@dlrudie -
First I want to say thank you and hope you are well. I have recently updated my OBS and I have noticed Snip.txt is empty when playing Spotify songs. 

- Cheers

**Comment by Gh0sT2242** [comment]
Hi Brian! Hoping I can help!

Have you tried the following?
- Closing Snip via Task Manager and re-launching. 
- Shutting down Spotify and re-launching. 

One of those two options should resolve the issue! Especially if Spotify updated. 

Let me know how it works!

**Comment by dlrudie** [comment]
This may be resolved with 6944341afd2400513eec2131192931f4fce53966
