### ISSUE TITLE
Last song being shown instead of current song being played

### ISSUE THREAD

**Issue by DynaUK** [dlrudie/Snip#506]
Snip keeps displaying the last song played and not the current one when using Spotify,

**Comment by dlrudie** [comment]
How frequent does it happen? Is it after an extended period of time? Does opening Snip.txt show the changes (as in maybe if you are displaying it through another program maybe the program hasn't re-read it)?

**Comment by JammyDodgerr** [comment]
Hi there, 

Hope you are well, 

I am experiencing the same issue, I have very little idea what I am talking about, but it seems that when Snip is pulling the track info from Spotify it isn't re-checking it/updating enough. 

Mine will show a song, normally the previous song, then when I skip to the next one it will still be one behind, but it updates as soon as I skip to the next song, but the info displayed is still the previous. It used to be near instant when I played a song or changed, but now t seems lagged. 

I have tried an older version of the Spotify window app but that doesn't help so maybe Spotify have changed something on their server side.

As you have mentioned above, I have checked the Snip text file and it updates but is still the previous song. 

Sometimes it will catch and get the right song, but then it doesn't update correctly and falls into the previous song loop again. 

It is strange as it was working fine about a week ago, so something has updated somewhere causing this issue. 

If I right click on the Snip icon in the tray and click Spotify (so it re checked with Spotify if I am logged in) the song will update correctly, but then will fall back into the pervious loop.

I LOVE your app, and I totally understand this is a side hobby, so if I can be any help I will try my best.

**Comment by DynaUK** [comment]
Thank you for the quick reply, and apologies for not replying sooner (my internet died shortly after). This usually happens after the first song that been manually inputted. (I click on a song it shows it correctly, then I skip, or let it play out, it'll still show that last song while the next one is playing. (I might try and make a small video showing this). 

When opening the snip text just shows the same thing. (The previous song). I'm not entirely sure how it would look if another program would affect it but I make sure no other music player is on while using it and it still does the same thing.

Personally I thought it could be on the Spotify side since the newer versions have been causing connectivity issues but JammyDodgerr has said that might not be the cause

> How frequent does it happen? Is it after an extended period of time? Does opening Snip.txt show the changes (as in maybe if you are displaying it through another program maybe the program hasn't re-read it)?

**Comment by JammyDodgerr** [comment]
It is strange that as soon as I skip to the next song, the text info changes near instantly to the previous song, so like one step behind. 

If I play song A, the text may not update for a little time, it may never show, but as soon as I click next to song B it will nearly instantly show song A info, then when I click to song C it will show song B. Sometimes it catches up and shows the correct song info, but normally it is behind, but updates as soon as I click next song. 

Sometimes it will get stuck on an old song and not update for a few songs, then it will catch up correctly and then it will loop back and only show previous songs after a while. Restarting Snip seems to bring it back to the correct info for the current song, but it will then soon go back into the previous song loop. 

I will keep trying old Spotify versions throughout the day. 

Where does Snip get the track info? id it local Spotify data or from the web server/services?

**Comment by JammyDodgerr** [comment]
Also when I click on Spotify within the Snip icon tray menu it takes me to the page - "Snip successfully authorized with Spotify. You may close this window now." and it will update correctly, but only for that song, its like it isn't getting the updates without being prompted by either the next song change or manual update

**Comment by JammyDodgerr** [comment]
Even when I change song forward or back, it will change instantly, but it will be the wrong one. If I go from song B to song A, it will show song B while I am playing A. If I go from song B to song C it will show song B while I am playing C..

The change is near instant though, so its getting the updates, just not the right song at the right time.

**Comment by JammyDodgerr** [comment]
I have tried the oldest version of Spotify that I can find online - spotify-1-1-69-612 (October 21) and still the same issues. Might it be a Spotify server issue?

**Comment by dlrudie** [comment]
Thanks for all of the information. I couldn't say at the moment. I'll have some free time this weekend to take a look at this further. While I am working on a whole new version I think I may work on the current one this weekend and get it working more reliably.

**Comment by lolrekurai** [comment]
thank you so much for looking into this, i've been using snip for my obs for a long time now and last few weeks it's been having this problem, i'll be on the watch for any updates ♥

**Comment by dlrudie** [comment]
One particular reason for lack of updates is that I just didn't have my development environment setup anymore and had no inspiration/motivation to work on Snip without it. I've set up a new dev VM yesterday and have VS and everything up and running well. I've already made a couple of commits and have begun working on fixing issues and improving Snip.

I'm not entirely sure what all I'll be working on or focusing on this weekend but I will for sure be closing the majority of three pages of issues here on Github.

**Comment by dlrudie** [comment]
This is likely resolved with 6944341afd2400513eec2131192931f4fce53966

**Comment by dlrudie** [comment]
Better yet. I'm just going to throw up a simple build. This is not any kind of official release and is meant to be tested. Please only use this if you intend to provide feedback on how it works or doesn't work. Thank you.
[Snip.zip](https://github.com/dlrudie/Snip/files/9738043/Snip.zip)

**Comment by murko69** [comment]
Hi David!
I have just run 25 songs in a row without any issues what-so-ever.
 Artist/track/cover shown is the one currently playing and not at any time the one just finished! 

Will keep a close eye on it during the day,

**Comment by dlrudie** [comment]
Excellent. Thanks for testing so far.

I did find one issue myself. When exiting Spotify with a track playing Snip did not correctly update it to say no track playing. It's probably related to using this.LastTitle to check if it changed. I'll look at that later today.

**Comment by JammyDodgerr** [comment]
Hi guys, 

I am currently testing the .zip dlrudie posted and it is working a treat! What ever you done its fixed it! I will continue to test. 

Thank you so much for doing this!

**Comment by dlrudie** [comment]
Pushed a new release. Closing this issue for now. Please feel free to create new issues with any new (hopefully none) bugs you encounter. Thanks for the support!
