### ISSUE TITLE
Index was outside the bounds of the array at Winter.Spotify.Update()

### ISSUE THREAD

**Issue by QwisoDev** [dlrudie/Snip#51]
Windows 10 Home (64bit)

Crash occurs as soon as music begins playing. Can load Spotify desktop app and Snip with no error

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 4.6.0.0
    Win32 Version: 4.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

**Comment by dlrudie** [comment]
Can you provide any more information as to what you were doing when this error occurred and the steps to reproduce it?

**Comment by QwisoDev** [comment]
Crash occurs as soon as music begins playing. Can load Spotify desktop app and Snip with no error

**Comment by QwisoDev** [comment]
I've just begun setting up for OBS streaming. I downloaded snip and ran it, then downloaded installed the already downloaded spotify installer

As soon as I hit play one the first track I looked up, crash

**Comment by QwisoDev** [comment]
I'll be glad to run a dev version to help you test environments. My name at gmail will also reach me

**Comment by dlrudie** [comment]
Which version of Snip and are you using Spotify Premium?

**Comment by QwisoDev** [comment]
Snip-v4.6.0.7z | No

**Comment by QwisoDev** [comment]
I see now that's from an old link

**Comment by QwisoDev** [comment]
Contact this youtuber which seems to the most popular 'official' guide for getting Spotify music into an OBS ticker. His video hard links to the wrong version :[

https://www.youtube.com/watch?v=7wXQFnjyQFo

**Comment by dlrudie** [comment]
5.1.0 is the latest.

As long as people link to https://github.com/dlrudie/Snip/releases/latest then people will always download the latest version.

**Comment by QwisoDev** [comment]
I left comment on his video with proper link. Thanks for jumping on the response I would have completely over looked that for at least an hour .. haha
