### ISSUE TITLE
Snip is not compatible in Windows 10

### ISSUE THREAD

**Issue by Piederman** [dlrudie/Snip#52]
I'm using Windows 10 Pro x64 and I keep getting "Invalid JSON string" errors from Microsoft.NET Framework. How do you make it stop? I'll post the error message below, but it's in Swedish since I'm using the swedish lanuage.

"Information om att aktivera JIT-felsökning i stället för den 
här dialogrutan finns i slutet av det här meddelandet.

************** Undantagstext **************
System.Runtime.Serialization.SerializationException: Invalid JSON string
   vid SimpleJson.SimpleJson.DeserializeObject(String json)
   vid Winter.Spotify.Update()
   vid Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   vid System.Windows.Forms.Timer.OnTick(EventArgs e)
   vid System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Sammansättningsversion: 5.1.0.0
    Win32-version: 5.1.0.0
    CodeBase: file:///C:/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT-felsökning **************
För att aktivera JIT-felsökning (just-in-time ) måste .config-filen för det här
tillämpningsprogrammet eller datorn (machine.config) ha 
jitDebugging-värdet angivet i avsnittet system.windows.forms.
Tillämpningsprogrammet måste också vara kompilerat med felsökning
aktiverat.

Till exempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

När JIT-felsökning är aktiverad kommer alla undantag som inte hanteras
att skickas till JIT-felsökaren som är registrerad på datorn
snarare än att hanteras av den här dialogrutan.

"

**Comment by dlrudie** [comment]
This happens only when you try to play a song? Does it happen with any/all songs you try to play or only specific songs? Can you perhaps provide a spotify link for a song that this is happening to?

**Comment by Piederman** [comment]
It happens with almost every song. This song it crashed on right now as soon as I started playing the song:
https://open.spotify.com/track/2SFIYtyBSG8afcBgeFySZY

Some others I can listen through the whole song, but after 2-3 songs it comes back.

**Comment by dlrudie** [comment]
Can you tell me what the Spotify title says exactly when the song is playing? Just hover your mouse over Spotify in the taskbar.

Also, try to access this url:
http://ws.spotify.com/search/1/track.json?q=Halsey%20-%20Hold%20Me%20Down

If you can copy and paste that information into pastebin.com or something like that and post that link here.

**Comment by Piederman** [comment]
Is this what you wanted?

http://i.imgur.com/NAJrqlz.png

http://pastebin.com/UQx4QwzN

**Comment by craftbyte** [comment]
I have Windows 10 64 bit Pro and I see no issues with Snip in Spotify. I am using seperate files and Artwork

**Comment by Piederman** [comment]
Not sure what could be the issue if not Snip. I'm currently using another program like Snip that shows now playing in a text document and it has never failed me, but it doesn't have a artwork option which saddens me.

Extract resources folder? No I have just unzipped the Snip folder and started the .exe file.

**Comment by dlrudie** [comment]
Are you using the latest version of Spotify? There's a message to update it at the top of yours.

**Comment by Piederman** [comment]
I've tried both the newest and backing up to 1,5 years version of Spotify. Read that backing up to a older version would help, but didn't help with my issue.

**Comment by Piederman** [comment]
Okay I have found out that it is the function that saves the information separately that is crashing, what could the issue be?

**Comment by dlrudie** [comment]
I've been testing this and it's been working just fine. Using the latest release of Snip, the latest version of Spotify, and all options and settings work as intended.

**Comment by Piederman** [comment]
I've reinstalled my Windows 10 and it still gives me the same error. I don't know what to believe seeing that I don't get this error from anything but Snip, given I'm not a programmer but on a daily basis.

**Comment by dlrudie** [comment]
Send me an email and I'll get together a version for you that should help debug this issue.

**Comment by JohnnyGrey86** [comment]
Just wanted to chime in. I'm on Windows 10 Home 64bit, and I've gotten a Java error once. Unfortunately I didn't screenshot it. Not as frequently as the OP's, but just wanted to mention his isn't the only W10 system it has happened to.

**Comment by Piederman** [comment]
Thanks Johnny for letting me know I am not alone.

@dlrudie you can send it to tommeey@hotmail.com

**Comment by Piederman** [comment]
Haven't gotten any mail from you so far, you sure you sent it?

**Comment by christophlsa** [comment]
I have the same issue but with windows 8.1.

```
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Invalid JSON string.


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///C:/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34250 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34262 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34248 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
``` 

The last error occurred with this song: https://open.spotify.com/track/2sNvitW3TxiTeC9xT9f2ZZ

If I click "Continue" then this error is thrown with every following song. Just for your info: I'm a German user but set English as the system language. I also tested this with Spotify in English and German (only the client). The account itself is set to German (didn't tested to change this).

You can find my email address in my profile if you want to send me any debug files etc.

**Comment by geriatricginger** [comment]
pastebin.com/embed_js/JEUBa3y4
I get JSON error on W10 + Snip v5.1.0 when attempting to launch it.  Link is JSON error file.

**Comment by dlrudie** [comment]
Are there any particular songs this happens with?

**Comment by geriatricginger** [comment]
It happens when trying to launch Snip.  I dont even get that far lol

**Comment by geriatricginger** [comment]
oh, for gosh sakes, I'm stupid..  nevermind, I figured out what I was NOT doing right..  :-1:

**Comment by dlrudie** [comment]
What were you doing wrong?

**Comment by geriatricginger** [comment]
well, I was wrong again..  it will not work on any spotify song.  i get the JSON errors.  With foobar, it works fine.   
if I launch Snip, and select spotify, Snip instantly JSON errors.

**Comment by trekfox** [comment]
Getting same if I have spotify open I can get Snip to launch but as soon as anything plays it does the JSON error  (Win 8.1 , the other night I was forced to install .net 4.6 ( i think it was) because a program I need required it (so it is ether the .net or the latest spotify update, it updated today for me)

**Comment by Dislecix** [comment]
I was getting an index out of range error whenever I started playing a song from spotify. I realized I got linked to snip from an old reddit post and it was linked to an older release(v4.6.0.7). I downloaded the newest release (v5.2.1.7) and the error went away.

**Comment by dlrudie** [comment]
I'm going to close this. Make sure you're all using the latest version and that you have .NET framework 4.5 installed. If this persists then feel free to open it up again.
