### ISSUE TITLE
Change how the whole string appears in the main text files

### ISSUE THREAD

**Issue by craftbyte** [dlrudie/Snip#53]
I want to be able to make the display in the main text file **`Artist: Song (Album)`**
Maybe make another text filed in the config that allows you to do this?

**Comment by dlrudie** [comment]
You can do this already.

Click on the "Set Output Format" menu item and change it to how you want it to be.

Set the track format to: $t ($l)
Set the separator format to: : (colon with a space after it)

Done.

**Comment by craftbyte** [comment]
Then why are they seperated in the config window. You could just make 1 text box that accepts all three and get rid of the confusion. so I can just enter `$a: $t ($l)` since the order is reversed and you are currently doing `song+divider+artist`

**Comment by craftbyte** [comment]
Maybe just add a new text box for the complete file and leave the other ones for the seperate files.
