### ISSUE TITLE
No Track Playing

### ISSUE THREAD

**Issue by J-Gamers** [dlrudie/Snip#536]
I've been using snip now for almost 2 years and haven't had an issue. Recently as in today I open everything up as normal, Spotify, OBS, and snip, and snip is no longer displaying txt. I've tried redownloading, closing and opening Spotify, restarting computer. Every time I connect snip it says successfully connected to Spotify, and then Nothing. Nothing has been recently added or changed to any of the programs I've used for the past half a year. Any Ideas to what it might be?

**Comment by ne0lines** [comment]
Same issue, tried the same steps. Not working. Also tried v8.0.0, but same issue.

**Comment by ne0lines** [comment]
Working now again, must have been a Spotify issue

**Comment by J-Gamers** [comment]
Must've been a spotify issue because it's working fine now
