### ISSUE TITLE
Occasional "Spotify isn't running."

### ISSUE THREAD

**Issue by JohnnyGrey86** [dlrudie/Snip#56]
This is a fantastic little program, so thank you for taking the time to write it!

The program occasionally doesn't update the currently playing song or artwork, and the tooltip for Snip says "Spotify isn't running." (Or something similar, I'm pulling this from my memory) It seems random, and closing Spotify and reopening it works. If there's anything else I can provide, let me know.

Snip v5.1.0
Spotify 1.0.13.108.gcd94e7db

How does Snip detect Spotify is running?

Usually Snip is pretty good about wiping out the contents of the image and text files, but when this "event" occurs, it seems Snip isn't wiping the contents.

**Comment by JohnnyGrey86** [comment]
![Image of Problem](https://lh5.googleusercontent.com/An8WHfNq4ASmGLO4HfF6i0Sck75Aw4tWxIZtf4qT_mvk3SM0_mv0n_oOJvHLuayCuSVedqJm4xybMQE=w1799-h867)

**Comment by dlrudie** [comment]
I haven't seen this happen yet. It's always working fine for me.

Snip just looks for the window "SpotifyMainWindow" and gets the title from it.  If it's ever saying that it can't find it then there's something weird going on.

**Comment by dlrudie** [comment]
I have been unable to duplicate this concern.
