### ISSUE TITLE
Snip won't save the Spotify Artwork

### ISSUE THREAD

**Issue by dumbdumb** [dlrudie/Snip#57]
So I just downgraded to Spotify 0.9.15.27.xxxxx and so far everything runs stable.
But nevertheless, Snip won't save the Spotify Artwork correctly. Snip is set up correctly ("Save Album Artwork") and the file Snip_Artwork is created. The file is completely empty and thus can't be displayed in OBS.
Does someone has any idea how to fix that?

Another problem: Snip recognizes the title as "Spotify - *Title* - *Artist*". Anyway to get "Spotify" out of there? :)

**Comment by dumbdumb** [comment]
ok, i "fixed " both issues using snip 4.6.0

**Comment by dlrudie** [comment]
\o/

**Comment by dlrudie** [comment]
I'm not sure why you would ever downgrade Spotify.  Feel free to upgrade to the latest version of Spotify and Snip.
