### ISSUE TITLE
Winamp set up as readme file says, but still output doesn't update

### ISSUE THREAD

**Issue by ReeshaDovahSil** [dlrudie/Snip#58]
I have been through the readme several times and made sure every option is set up as stated in the Winamp section, including the formatting. Snip is correctly generating the Snip.txt file to read Title - Artist. However, nothing I do in Output Format has any effect on anything. If I add characters, quotes, spaces, change the separator, whatever, nothing changes. I can even delete every line in Output Format, leaving everything blank, and upon saving, still nothing changes in the way Snip.txt is being generated.

In addition to that, Snip_Album.txt, Snip_Artist.txt, and Snip_Track.txt remain empty (Save Information Separately is checked in Snip).

I've tried shutting down and restarting everything after making changes, to no avail.

I'm not sure what I can be doing wrong. The readme file is very simple to follow.

I'm using Winamp v5.63 (x86), Windows 7, and Snip v5.1.0.

Any suggestions? I'm happy to provide more information if needed.

**Comment by dlrudie** [comment]
I'll need to reinstall Winamp to test this out further.

**Comment by bart1ebee** [comment]
I was having a similar problem  and it all had to do with the" – ". I copied the dash from the readme and put it in the advanced title for winamp and set in the output format Set Separator format to " – " (with out the quotes) and it fixed being able to change anything in the output format. Thanks dlrudie for making this awesome app.

**Comment by dlrudie** [comment]
No updates.
