### ISSUE TITLE
iTunes music information not showing up?

### ISSUE THREAD

**Issue by ckabjp** [dlrudie/Snip#59]
Everything is up-to-date (Snip, iTunes and OBS) and despite having Snip set to iTunes as per the instructions, and having the Snip file selected as text in OBS. I'm not having any text show up in my OBS. Can you check to see if everything is working? The Snip.txt file is blank no matter what. What's going on?

**Comment by dlrudie** [comment]
I just tested on my system and it works fine.  I think the only time I managed to get Snip to not output anything is when I dropped a WAV file on iTunes that had no metadata of any kind.

**Comment by ckabjp** [comment]
Strange. I have files that all have titles, tracks, and artists.

**Comment by ckabjp** [comment]
https://gyazo.com/d791ee919a5814f188f6aca0caf833c7 

Here's a screen of the metadata for a test song.

**Comment by dlrudie** [comment]
What settings are you using with Snip?

**Comment by ckabjp** [comment]
Everything is default except for the program selection, which is set to iTunes.

**Comment by dlrudie** [comment]
Is the file local on your computer or through Apple Music or internet radio?

**Comment by ckabjp** [comment]
An MP3 on the computer's hard drive.

**Comment by ckabjp** [comment]
Nothing is showing up at all when playing the song in the Snip.txt file either.

**Comment by dlrudie** [comment]
Even using all of the options in Snip it works for me.

![yduvmllk](https://cloud.githubusercontent.com/assets/1780069/9982769/442cdc1a-5fac-11e5-9bfe-723b3b515c53.png)
![rm9zypwe](https://cloud.githubusercontent.com/assets/1780069/9982770/46f05b3e-5fac-11e5-8a0d-d1d29f26afd5.png)

**Comment by ckabjp** [comment]
What the hell...

**Comment by ckabjp** [comment]
My Snip.txt and all the files similar to it never change.

**Comment by ckabjp** [comment]
What the?! 

I enabled all the options and now it works. What??

**Comment by dlrudie** [comment]
Well that shouldn't be happening. Try playing with the settings individually to see if you can narrow down which option allows it to work and which doesn't.

**Comment by ckabjp** [comment]
I think it might have to do with my iTunes files sometimes having numbers like "003. Justice - Newlands" in the title and no album or artist names in the info.

**Comment by ckabjp** [comment]
This file, for example, doesn't work unless I edit the file and fix the artist name in the information.

https://i.gyazo.com/3265114aaac9228b3a953eee1211b3ba.png

**Comment by ckabjp** [comment]
It seems that the program require the files to have artist names in the information or it won't show anything at all.

**Comment by dlrudie** [comment]
Snip does indeed require the Artist and Track fields to be set.

**Comment by dlrudie** [comment]
I'll look into adding fall-back support to just showing the filename if no track or artist fields are present. It all depends on what information iTunes itself provides through its API as to what I can get out of it.

**Comment by ckabjp** [comment]
I'd also really love it if there was a way to switch the track and artist names' positions. Right now it always goes (Track name - Artist name), but that seems backwards from the traditional (Artist name - Track name) that most YouTube videos or compilations have. Maybe I'm just a dummy with my formatting of the output format, but I just feel like it would be more intuitive and commonplace to see the Artist name and THEN the track name.

**Comment by bessiq** [comment]
ckabjp, you can re-order by simply changing the variables in the output format. Just ignore the field names and put the variables where you want. I put $a (artist) in the track field, and $t (track) in the artist field. I added a separator in the artist field too, but that is not necessary.

![screenshot 2015-10-24 10 16 17](https://cloud.githubusercontent.com/assets/7315505/10710871/42139120-7a38-11e5-81d4-162f22492570.png)
