### ISSUE TITLE
AIMP Support

### ISSUE THREAD

**Issue by matthewgrzegorczyk** [dlrudie/Snip#61]
Do you plan to support AIMP as well? It would be great IMO, I am mainly using spotify, but sometimes I listen to music in AIMP and then I cannot use snip for it.

**Comment by dlrudie** [comment]
I'll look into this in the future.

**Comment by DJDavid98** [comment]
AIMP3 is my main player, would love to see it supported!

**Comment by dlrudie** [comment]
No plans on my part. Sorry.

**Comment by BlueWolfKenji** [comment]
2025 here, ten years later, still looking for Aimp support (Or normal Windows Media API support, since my Aimp has a plugin that reports to windows what's playing, including cover). I can't find any alternatives ...

**Comment by murko69** [comment]
Snip used to support a various types of players but finally decided to close support for all but Spotify and iTunes a few years back!
Sadly the development of Snip kinda came to a halt later on - still using it though and works fine for me.
