### ISSUE TITLE
Not displaying the correct album cover

### ISSUE THREAD

**Issue by ErraticFox** [dlrudie/Snip#62]
I noticed it doesn't always display the correct album covers. I know it's possible, because GetSpotify does it correctly, but it only has a tiny 160x160 only, album display and the project was disconnected. Could you please add in the larger album picture sizes? Other than that, it's perfect.

**Comment by dlrudie** [comment]
GetSpotify uses a different API that connects directly to the web helper to get the track ID. It can use this track ID to get the exact album art for that song.  However, Snip simply uses the track title and artist name, queries it against Spotify's own information, and uses the album art provided.  It may not always match exactly but it's pretty accurate from my own tests.

**Comment by ErraticFox** [comment]
It doesn't sound like you do, but do you have plans to implement the API GetSpotify uses? It only increases the program about by 400kb. It'd be really cool if so, it'd perfect the program (from the users end) and would be extremely cool if you could at least do implement something like that so it's right every time. :)
