### ISSUE TITLE
"VLC isn't working right now"

### ISSUE THREAD

**Issue by Krenagh** [dlrudie/Snip#64]
Hi there
First, thanks for that great tool!
Unfortunately, I got an issue where Snip told me that "VLC isn't working right now", even when I'm listening some music with VLC. Here's a picture:
![vlc sn t working](https://cloud.githubusercontent.com/assets/15180676/10563922/6998c5b0-759e-11e5-87b7-9011c1cd8df0.png)

If you have any idea how to fix that, I'll be really thankful.

**Comment by dlrudie** [comment]
This is a result of the titlebar being in a different language.

Snip looks for "VLC media player" while yours does not have that.

I'm not sure of a workaround for this.  It would be impractical to check for every possible language combination that VLC can be in.

**Comment by dlrudie** [comment]
I guess I could scan for a vlc.exe process and pull the title using the PID.
