### ISSUE TITLE
Snip not working upon launch

### ISSUE THREAD

**Issue by Lgeme84** [dlrudie/Snip#65]
So I downloaded snip and when I attempt to run snip.exe it automatically stops working/crashes. 
I'm running Windows 7.  

I had trouble even launching it/finding the .exe file until I browsed through the issues section and found a tip to move the download into "documents". Once I did that I found the .exe and tried to launch it but it just auto crashes. 

Any thoughts?

**Comment by kamijoutouma** [comment]
What program do you have open that snip uses? Do you have a song playing in that program? Have you tried closing all applications and opening snip and then reopening each application one by one until still crashes?

These 3 answered and a debug log (if possible) would help me to better answer your question.

**Comment by dlrudie** [comment]
Over two months and no follow-up. Closing.
