### ISSUE TITLE
Only shows first artist from Spotify

### ISSUE THREAD

**Issue by uncajesse** [dlrudie/Snip#66]
If a track has multiple artists, it only shows the first artist. Assuming you're still getting the Artist and Track from the window title, then it's Spotify's fault. But you're getting the Album and Art from somewhere else, so it might be possible to get the additional artists.

**Comment by dlrudie** [comment]
I pull this information from the window title. When getting the JSON file there are multiple results that show up but I only use the first one because there's no way of knowing which is the correct one.
