### ISSUE TITLE
Winamp Does have album art and does support album art

### ISSUE THREAD

**Issue by belldandu** [dlrudie/Snip#70]
I noticed in your source code you noted that winamp does not support album art. This is not true, While the plugin to download custom album art no longer exists you can still set album art manually and winamp still looks for album art in the file/folder. It first looks for an image embeded in the file and if there isn't one it will look for cover.jpg and a few other things. At some point it would be nice if proper implementation of saving album art for winamp is added to snip instead of claiming winamp doesn't support album art even though it does.

**Comment by dlrudie** [comment]
It's not that Winamp doesn't support album art; it's that there's no available API that I could find that provides access to the album art.

**Comment by kamijoutouma** [comment]
Ah ok will look into making one then myself.

**Comment by fitzfuchs** [comment]
@kamijoutouma Any news about the album art api for winamp? 
I would love to switch from iTunes to winamp for sound streaming with snip.

**Comment by dlrudie** [comment]
No progress in some time
