### ISSUE TITLE
No Snip.exe File?

### ISSUE THREAD

**Issue by cabose426** [dlrudie/Snip#75]
I just downloaded the snip .zip folder and I don't see any Snip.exe file anywhere. How the heck do you run this anymore?

**Comment by kamijoutouma** [comment]
You need to extract it .... The executable has been compressed along with other files into the .zip file you see

**Comment by JAC512** [comment]
Im having the same issue. I extracted the zip and still no Snip.exe file so i cant open it.

**Comment by FNCxPro** [comment]
You probably aren't downloading the release 7z file. It isn't released as a zip. It is released as a 7z file. Go to https://github.com/dlrudie/Snip/releases and you can download the latest 7z file!

**Comment by Sumpula** [comment]
I have this exact same problem. I've downloaded the latest 7z package and there is no .exe
![snipexenotfound](https://cloud.githubusercontent.com/assets/16398990/11952157/fac13774-a89e-11e5-8393-1bf352f17822.JPG)

**Comment by FNCxPro** [comment]
@Sumpula That looks like you downloaded the source code. The link to the release is here: https://github.com/dlrudie/Snip/releases/download/v5.1.0/Snip-v5.1.0.7z.
