### ISSUE TITLE
Snip Lags Winamp when a track has unicode, japanese, chinese, etc. chars 

### ISSUE THREAD

**Issue by belldandu** [dlrudie/Snip#78]
Title says it all. Leaving this here so i don't forget to look into this later.

**Comment by dlrudie** [comment]
What do you mean it lags?

**Comment by dlrudie** [comment]
I've tested a lot of Japanese and Chinese song titles and have not been able to duplicate this concern.

**Comment by dlrudie** [comment]
I have not been able to duplicate this. I've tested this issue a bunch recently and it works just the same as a regular title. If you can explain a scenario where I can duplicate it feel free to reopen this issue.
