### ISSUE TITLE
Snip_Artwork.png never stops updating on "standby"

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#80]
Greetings dlrudie!

Dunno if this is the way things should work or not.
First of all, thanks a million for Snip. I love it!

I only use Snip with Spotify and I create separate information (text files: song/artist/album) that i sync with a ftp-program to my server manually (eg. the ftp program feels when the files change) so on song change the text files change and are then synced from local to server where I can use them any wayI want.... I've created sigature images and can also just show info on a web page for example....

So far so good....
Today (Snip 5.2.0) I added the Snip_Artwork.jpg to the same sync, just to see if I could do anything cool with it and all things works fine as long as Spotify is running. The 3 text files and the .jpg is synced with my server via FTP on every song change (and only then).

However! When I stop Spotify all sync should also stop but instead the Snip_Artwork.jpg is synced and uploaded to server more or less any other second until I either shut down Snip or shut down my FTP program completely.

Is this normal? ;)

/Michael

**Comment by dlrudie** [comment]
I was able to confirm this. It should not be doing this.
