### ISSUE TITLE
Strange chars for Swedish åäö

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#83]
Opening the textfile (Snip_Album) and seeing this: "Handen PÃ¥ HjÃ¤rtat" when playing song from the album "Handen På Hjärtat".
Can't really say when this happend since it's been a while since I listened to anything Swedish (and bothered to check) using Snip.

Something I changed locally by mistake or what happened? I know I had this working earlier. Just can't tell how long ago (how many versions ago) I checked last time

**Comment by dlrudie** [comment]
Give me Spotify links to some of these songs. I'll see if I can figure it out. It may be something they changed recently with their JSON files.

**Comment by murko69** [comment]
The album from my example (if Swedish punk rock is ok :)): 
1. https://open.spotify.com/album/4jkK3DsosziwJi8s8HMMnA
2. spotify:album:4jkK3DsosziwJi8s8HMMnA

The album itself has two of these letters and also a lot of the songs.
Dunno what type of link you wanted so you get both :)

Hope this is enough, or just shout ot and I'll give you more.

**Comment by Renkon** [comment]
Same happens with special latin characters such as á é í ó ú.

spotify:track:4gSkQz7uZitSfOmpIksZmC is an example.
