### ISSUE TITLE
Impossible to change output format

### ISSUE THREAD

**Issue by Aldebarande** [dlrudie/Snip#84]
Hi ! 
I've tried to use your soft with OBS. I made a "scrolling" text (sorry, don't know the correct word to explain", but the end of the title is imediately followed by the artist's name. I tried to add many espaces to the output format, but it never changes anything. What can I do ?

**Comment by dlrudie** [comment]
Check the text file afterwards. I promise you there will be spaces there. Perhaps whatever you're using to read the text file is stripping the spaces instead.

Keep in mind the changes you make won't take effect until you stop/start the song or switch tracks.

**Comment by zefie** [comment]
Will there be more options for customization in the future? Such as placing the artist before the title?

**Comment by dlrudie** [comment]
You can kind of do that now by swapping the artist and track fields in the boxes.

I may just eventually make a single text box that has the output format as a whole in it.

**Comment by SavageDrago** [comment]
Cant change format output. Tried with VLC, Foobar2k, nothing. Is it a know bug? Plans for fixing it? Thanks!
