### ISSUE TITLE
Swedish and other characters are displayed wrong

### ISSUE THREAD

**Issue by VidyaViking** [dlrudie/Snip#85]
Text is displayed like "“BrÃ¤nnmÃ¤rkt” ― Raubtier"

Supposed to be Brännmärkt

Im not sure how the resources work but the Swedish resources are there. 

Also, japanese/Chinese characters cant be properly viewed either. This problem only exists when using spotify, no idea why. But the text is output correctly when I open in winamp for example.

I phrased everything terribly because it's now 04.30 in the morning. Sorry for that.

**Comment by dlrudie** [comment]
This was fixed already. Did you upgrade?

**Comment by VidyaViking** [comment]
Huh, when was this fixed? Downloaded new verson with OS reinstall like 2 weeks ago. Works like a charm now. Latest release?

Anyways, nice, guessing this can be closed then! Cheers :)
