### ISSUE TITLE
5.3.0 - Invalid JSON string w/ Spotify

### ISSUE THREAD

**Issue by NHDriver4** [dlrudie/Snip#87]
Hello. Spotify updated and ever since then I'm getting this error message.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///D:/Stream_Stuff/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.114.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by NHDriver4** [comment]
Just a quick note too.. If I close spotify and run Snip, it loads just fine. The moment I play a track, it crashes again with the same error.

**Comment by dlrudie** [comment]
Can you post your Spotify version? Mine has not asked me to update to any newer version and it's still working for me.

**Comment by NHDriver4** [comment]
![capture](https://cloud.githubusercontent.com/assets/49725/13238506/78ed762a-d9a1-11e5-864f-dcf9765a741e.PNG)

**Comment by HalcyonFury** [comment]
Just chiming in that I'm having the exact same issue, same version of Spotify

**Comment by dlrudie** [comment]
Try this file and screenshot any error boxes that pop up.

[Snip-v5.3.0-test.zip](https://github.com/dlrudie/Snip/files/149531/Snip-v5.3.0-test.zip)

**Comment by dlrudie** [comment]
I have not been able to duplicate this issue.

**Comment by NHDriver4** [comment]
Is there anything that we can do to assist in determining the cause?

**Comment by NHDriver4** [comment]
Sorry, didn't see that.I'll try it tomorrow when I'm home. Thanks again!

**Comment by HalcyonFury** [comment]
Using the file you linked, I'm able to use it with Spotify on stream flawlessly.

**Comment by dlrudie** [comment]
That's weird. I literally changed nothing other than added one try-catch exception to display a messagebox instead of crashing.

**Comment by Kenpachi10** [comment]
I am still getting this error as well, with the one try-catch exception added, I receive a ton of messages boxes that are near endless until I quit snip.

**Comment by dlrudie** [comment]
You probably will.  What do they look like?

**Comment by Kenpachi10** [comment]
![snipissue](https://cloud.githubusercontent.com/assets/13564649/13377776/24672f4c-dda7-11e5-9f0f-c5ef0c765dd5.jpg)

It continues until I close snip from icon area.

**Comment by dlrudie** [comment]
It looks like you can't access Spotify's web server.

I can't either right now. They might be doing some maintenance or something.

**Comment by Kenpachi10** [comment]
Fair enough. Will keep you updated if it continues past the next few hours. You need a packet trace or anything?

**Comment by dlrudie** [comment]
For the record, the 503 Server Unavailable error is different than the original issue. The original issue is about invalid JSON, not server unavailability. If you can re-test to see if you can duplicate the issue that would be great.

In the meantime I think I'll use this issue to implement better error catching and fall-backs.

**Comment by NHDriver4** [comment]
@dlrudie Sorry for the delay in testing. Your test files work just fine. I confirmed the current release is still giving me the same error.

**Comment by dlrudie** [comment]
I still have no answer for this.

**Comment by Giulio1708** [comment]
I solved the issue with the version you provided just above, but my antivirus (BitDefender) says that it's a virus.
That's not a big deal, I added the app in exceptions, but it for someone it can be a problem.

**Comment by Kenpachi10** [comment]
I'm still experiencing this issue, however its extremely intermittent.

**Comment by jan422** [comment]
I have too this problem and link dlrudie send I no can open this snip in my PC

**Comment by Blizzardo1** [comment]
Looks like when it tries to parse the JSON, it doesn't know how to handle null or empty data. It looks like it was coming from Spotify.cs at Line 76, There's not a check to see if the download is null or empty, thus causing that error. I'm testing your source in one of my development projects, and that particular line got brought to my attention. I hope this helps you.

**Comment by dlrudie** [comment]
There are definitely some bugs in regards to this. Most noticeably is when Spotify's site simply does not provide the JSON to you. I've ran into this randomly where I'll request the JSON from their site and it will simply reply with a blank result. When I submit it a second time exactly the same way it returns successfully. While I have never seen this issue with my own use of Snip... I can see where it could potentially happen to some users if, for example, Spotify throttles responses to users within a broad IP range.

Snip could definitely use better error handling and I do intend to implement just that in the future.

**Comment by FluxMonkey92** [comment]
Hello, thought i'd leave a comment regarding this issue..

This exception is still occurring in Snip v5.5.0 with Spotify version 1.0.38.171.g5e1cd7b2
I've come across exactly one song in all my playlists which causes the exception every time it plays, which i hope will aid you in finding a resolution;

https://open.spotify.com/track/3vZO25GdYuqFrR1kzZADnp
spotify:artist:2WKdxPFRD7IqZvlIAvhMgY

It occurs whether i rapidly skip through playlists or not, so it's not a rate-limit issue or the like from Spotify.

Cheers for Snip!

**Comment by dlrudie** [comment]
Great! As soon as I get off of work today I'll take a look at it. Thank you.
