### ISSUE TITLE
Not working iTunes Toolbar / Snip's registry files

### ISSUE THREAD

**Issue by EpicGamingVideos** [dlrudie/Snip#88]
If i launch Snip iTunes with snip when i minimize it to the toolbar on the taskbar the toolbar doesn't work.
If i launch iTunes on its own the toolbar works fine.
And also can anyone tell me the location of Snip's registry files or something because when i first time run it it gave me a setup screen but when i deleted it and reinstalled it didn't.

**Comment by dlrudie** [comment]
Hello.

I do not know what you mean by toolbar.

Snip has and will never have a setup screen. The registry entries are located at: HKEY_CURRENT_USER\SOFTWARE\David Rudie\Snip

There will be an entry for each version you've used. Whenever a new version comes out and you run Snip all of the settings will be at their defaults and you just need to change them.

I may eventually write in some code to clean up and re-use existing settings if found.

**Comment by EpicGamingVideos** [comment]
I found the registry files and deleted them and it was still not working, then i tried downloading the 5.1.0 version and with that the toolbar worked fine. And the toolbar kind of looks like this, but this is an older version. [http://i.stack.imgur.com/1sEXy.jpg](http://i.stack.imgur.com/1sEXy.jpg). And it is an official "extension" made by apple, not i downloaded it. And i found another bug i think, if i play a song that has no artist or title info all the the other songs artist and title info will not show up in OBS. I haven't tested it if it's OBS's fault or the output file would not update after that song. Maybe you can check it out, and thanks for the help.

**Comment by dlrudie** [comment]
I'm closing this issue because the original issue was not an issue.

I recommend opening a separate issue for the problems you listed in the third post.
