### ISSUE TITLE
Unable to extract 7z file after download

### ISSUE THREAD

**Issue by xInsomniAntx** [dlrudie/Snip#93]
I'm not the most computer savvy person out there but I've downloaded 7zip and when it goes to open the file it tells me its unable to open due to file may be corrupted.  I'm not sure what I'm doing wrong.  Can anybody lend me a hand?

**Comment by ghostalphabravo** [comment]
Same here.

**Comment by dlrudie** [comment]
Tested downloading the file from GitHub and extract with 7-Zip v15.14 and it worked fine.
