### ISSUE TITLE
Cannot open and install Snip

### ISSUE THREAD

**Issue by ghostalphabravo** [dlrudie/Snip#95]
When I download the newest first of it, it doesn't let me open it at all.

**Comment by ghostalphabravo** [comment]
Everytime I try to double click the download, it asks me to open in an app.

**Comment by dlrudie** [comment]
You'll need [7-zip](http://www.7-zip.org/) to extract the archive.

**Comment by FyreFlyGJh** [comment]
I responded in another thread that was closed for being thought to be related to this, but I and another person are not having any issues with needing to use the unzip. We aren't even getting anything to download in the first place from github for Snip. There isn't a zipped folder being downloaded in the first place to extract from when clicking the download. When clicking download, it only downloads a blank white document icon labeled with the current Snip version and nothing else.

**Comment by dlrudie** [comment]
It should be Snip-version.7z. You simply extract this archive file and everything will be in there. The files on the site are all correct and all work fine.

**Comment by FyreFlyGJh** [comment]
Thanks for the reply, I'll figure out what's going on on my end. And, again thanks you for Snip :)

**Comment by kittykatnightcore** [comment]
I had the same problem at first, try using this link!
https://github.com/dlrudie/Snip/releases/tag/v6.9.5
