### ISSUE TITLE
Output Format not recognized

### ISSUE THREAD

**Issue by Web-Macher** [dlrudie/Snip#96]
Changes in the "output format" menu are not applied.
It is not possible to add characters before or after the markers. Everything what is filled is not displayed in the text-file. Only default settings are displayed.
Example:   12. Title - Artist12. Title - Artist12. Title - Artist
Should by: 12. Title - Artist 12. Title - Artist 12. Title - Artist

**Comment by dlrudie** [comment]
Check the readme file. If there is no actual separation of artist, track, etc. then Snip doesn't know what's what and can't change the output. The readme explains how to separate for some applications but not all can be done.
