### ISSUE TITLE
Snip 5.3.1 needs an app to open and I by mistake set it to open with internet explorer 

### ISSUE THREAD

**Issue by Saluichi** [dlrudie/Snip#97]
How do to fix the initial issue as well as undoing my screw up??

**Comment by dlrudie** [comment]
Duplicate of #95.

When you install 7-Zip it can re-associate files for you.

**Comment by Saluichi** [comment]
so when I re associate files do I just run the ico as an application? do I just run it as an admin and it will run as normal??
