### ISSUE TITLE
Snip_Artwork different size for some songs - iTunes

### ISSUE THREAD

**Issue by fitzfuchs** [dlrudie/Snip#99]
Hi there,
I'm using Snip 5.3.1 with iTunes 12.3.3.17. I want to put the Snip_Artwork into my Twitch stream with OBS. But the image size of the Snip_Artwork is sometimes different and then the image size on my stream for the album artwork looks bad.
Is this maybe a bug? Because I can choose the size of the Snip_Artwork. But whatever I use, the size of the picture will change for some songs like before. Is there a chance I can tell Snip that he shrinks every album artwork to tiny or maybe small?

with best regards
FitzFuchs

**Comment by entombor2** [comment]
I had something similar, the latest itunes resized for me a lot then I updated both snip and itunes and now all I get is a tiny 2 pixel image i attached that won't change ever. Don't know if it's a permissions issue or itunes changed something but it's broken either way
![snip_artwork](https://cloud.githubusercontent.com/assets/18562492/14658648/8821b8c4-0663-11e6-9cbb-40c55fd2c734.jpg)

**Comment by entombor2** [comment]
I found a non-snip solution for you in the OBS-studio program at least, haven't checked old OBS but it's always a good time to update. If you right click the album art and then go "Transform->Edit Transform" you can choose options in the bottom area such as "Scale to inner bounds," any option in the second, and then equal amounts in the bounding box size you won't have to worry about snip.

**Comment by dlrudie** [comment]
The artwork size selection only applies to Spotify sinc For iTunes it will use whatever artwork is stored in the song file.

**Comment by fitzfuchs** [comment]
Thx @entombor2 that works for me. :+1:

**Comment by Holylambs** [comment]
i Got the Same problem for my Twitch Channel ! Using iTunes i Fixed it by Adding a (Scaling) Filter to the Album art
